### ISSUE TITLE
google dork and duck dork scan was error

### ISSUE THREAD

**Issue by thanh125643** [epsylon/ufonet#10]

**Comment by epsylon** [comment]
Can you provide more information about your issue?

**Comment by thanh125643** [comment]
when i use dork scan trust yahoo does 
google and duck was not work 
this mess "the sever seem down"

**Comment by epsylon** [comment]
Hi,
I am updating that on next version... which will be released soon.
Duckduckgo has removed "intitle" wildcard from their API so is not possible to use it as usually.
About google, it is related with Tor. They are showing a captcha for some nodes exits. UFOnet cannot fill it by the moment, so this option can be used just using direct IP.
