### ISSUE TITLE
auto-search error

### ISSUE THREAD

**Issue by root09005** [epsylon/ufonet#102]
./ufonet --auto-search error:
[Error] - Something wrong (auto)searching...

**Comment by root09005** [comment]
[Error] - Unable to connect to yahoo

wile using 

./ufonet --auto-search -v

**Comment by trollmad3** [comment]
Are you connecting directly or using TOR?

**Comment by epsylon** [comment]
This was a problem on previous UFONet version (v.0.9). 
Which one are you currently using?
