### ISSUE TITLE
Cannot reach TOR checker system

### ISSUE THREAD

**Issue by muricawashere** [epsylon/ufonet#105]
Im running the command
`./ufonet --proxy='http://127.0.0.1:9050' --check-tor`

and get the response

> Sending request to: https://check.torproject.org
> 
> Cannot reach TOR checker system!. Are you correctly connected?

I get the same error when I run it with the port at 9150 I have tor running in the background using the `service tor start` command

https://gyazo.com/11b6e2836a16e77fbb540b810dde6c24
https://gyazo.com/5390576bea1141a0c4de392190c62c0d

**Comment by epsylon** [comment]
Tor depends a lot on how you configure it. 
Btw, I recommend you to install a transparent proxy (ex: privoxy, polipo, etc...). and use it for apps (even to add it to your env shell) that normally is listening at port: 8118

UFonet is working correctly with Tor:

"""
./ufonet --check-tor
"""
"""
[SNIPPED]
UFONet - (DDoS botnet + DoS tool) via Web Abuse - by psy 

===========================================================================

Sending request to: https://check.torproject.org

Congratulations!. Tor is properly being used :-)
"""

**Comment by muricawashere** [comment]
is it possible i can have an example for how to set tor up
