### ISSUE TITLE
Problem at the installing

### ISSUE THREAD

**Issue by YETTIyt** [epsylon/ufonet#107]
I clicked at setup.py and it opend and closed itself quick... I don´t know if it should be like that... Because i don´t know in what i should write the commands... (Sorry that im not so good in english)

**Comment by epsylon** [comment]
@YETTIyt setup.py is an script that requires some commands. 
In your case, you need to open a shell and try: **python setup.py install**
Take a look to the FAQ to view an example of how is used: 
https://ufonet.03c8.net/FAQ.html
