### ISSUE TITLE
ImportError: No module named UFONet

### ISSUE THREAD

**Issue by Trey133** [epsylon/ufonet#110]
Installed on Kali
I keep getting this import error. I tried to reinstall but that didn't help and all Python packages are installed

**Comment by trollmad3** [comment]
Post the full error here.

**Comment by Trey133** [comment]
On Jun 18, 2018 5:49 PM, "trollmad3" <notifications@github.com> wrote:

Post the full error here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/epsylon/ufonet/issues/110#issuecomment-398219465>, or mute
the thread

**Comment by Trey133** [comment]
It only happens if ufonet is ran from /usr/local/bin. Problem solved by using it from the dl'd repo from github
