### ISSUE TITLE
how to resolve this?

### ISSUE THREAD

**Issue by lancyJD** [epsylon/ufonet#111]
Trying 'blackhole': 176.28.23.46

Vortex: FAILED!
------------

[Error] - Unable to download list of 'zombies' from this 'blackhole'. ;(

**Comment by epsylon** [comment]
Is your connection ok?. Try it again.

**Comment by Hisoka503** [comment]
remove ufonet then download it ,, 
i had this issue before when i close ufonet when it works

**Comment by epsylon** [comment]
This is not an issue related with client side (or code). 
Sometimes server side (mothership), almost this one provided by default, has thousands of socket requests (ex: to download provided zombies as example) open and fails when trying a new one. 
Just wait a bit for processing other tasks and will work again.
