### ISSUE TITLE
403 and other errors are counted as working

### ISSUE THREAD

**Issue by mcmailman** [epsylon/ufonet#113]
When testing bots, 403 errors are allowed even though they don't allow connections. I haven't researched other errors but I've gotten many such as 412 which also don't allow you to use the zombie. I'm unfamiliar with the code but may release a request if it goes unchanged for too long

**Comment by epsylon** [comment]
Let's check it. 
Can you provide more info?. Which kind of bots are failing  (GET, POST, XML-RPC, All..)?. Are these bots passing (-t option) tests?... 
Also you can attach more info about command execution, logs, etc..
P.D: there is a roadmap practically ready for UFONet v1.1

**Comment by mcmailman** [comment]
I ran a test-offline test while running Tor. Currently I'm only getting the error on Zombies, though I'm running the test again to see if it changes anything. The actual command ran is

./ufonet --test-offline

I have several hundred zombies.

Here is one example:

//other logs n' stuff
Name: www.google.com
Type: [ Zombie ]
Vector: https://www.google.com/interstitial?url=
HTTP Code: 403
STATUS: ONLINE!

I have several hundred zombies in case that might change something

**Comment by mcmailman** [comment]
Also off topic but I tried running --test-all and it did not work

error: can't start new thread

**Comment by epsylon** [comment]
Well... UFONet is checking this replies as ONLINE: main.py#L2392

./ufonet --test-offline

It is used just to test if zombies are online (not to test if they are working). To test that, you should use (-t option). Did you tried (--attack-me) to check if bots are really working?.
About this issue: 
error: can't start new thread 
Please read FAQ: https://ufonet.03c8.net/FAQ.html

**Comment by epsylon** [comment]
./ufonet -t "botnet/zombies.txt"

**Comment by mcmailman** [comment]
[Error] - Something wrong testing!

error: can't start new thread
double free or corruption (out)
Aborted

**Comment by epsylon** [comment]
> error: can't start new thread

FAQ: https://ufonet.03c8.net/FAQ.html
