### ISSUE TITLE
ImportError: No module named _ssl

### ISSUE THREAD

**Issue by wlals10117** [epsylon/ufonet#115]
roota@ubuntu:~/ufonet-master$ ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/roota/ufonet-master/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, string
  File "/usr/local/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

**Comment by trollmad3** [comment]
Run
```
apt-get install openssl
apt-get install libssl-dev
```

**Comment by wlals10117** [comment]
`root@ubuntu:/home/roota#` apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.0.2g-1ubuntu13.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

root@ubuntu:/home/roota# apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.0.2g-1ubuntu13.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not `upgraded.`

**Comment by wlals10117** [comment]
```
root@ubuntu:/home/roota# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.0.2g-1ubuntu13.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

root@ubuntu:/home/roota# apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.0.2g-1ubuntu13.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by trollmad3** [comment]
@wlals10117 Now re run ufonet.

**Comment by wlals10117** [comment]
The issue was not resolved.

**Comment by epsylon** [comment]
@wlals10117
1.This is not an issue related with UFONet code:
https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl
2. This has been previously reported: https://github.com/epsylon/ufonet/issues/49
3: UFONet/FAQ "Installation" is explaining you some requeriments, as for example, that you need Python >2.7.9. Please, check it: https://ufonet.03c8.net/#installation

**Comment by saydulk** [comment]
I am using UBuntu 16.04 and I am facing same problem 
![Screenshot from 2019-04-08 01-44-31](https://user-images.githubusercontent.com/1058663/55688891-e6e5c200-599f-11e9-863f-02ac1fd278ec.png)

**Comment by epsylon** [comment]
@saydulk take a look to the comment on your image, when importing SSL:
> # if we can't import it, let the error propagate
Solution: sudo apt-get install libssl-dev 
Btw, in your case, looks that it is a problem related with your docker configuration. You should try to install libssl-dev correctly on it.
