### ISSUE TITLE
Ufonet --gui

### ISSUE THREAD

**Issue by Scorpio2410** [epsylon/ufonet#116]
Hello Founder Ufonet. I use UFOet on Backtrack5R3 with the command line ./ufonet --gui, and the error is: /usr/lib/gio/modules/libgiogconf.so: wrong ELF class: ELFCLASS64
Lỗi nạp module: /usr/lib/gio/modules/libgiogconf.so
/usr/lib/gio/modules/libgvfsdbus.so: wrong ELF class: ELFCLASS64
Lỗi nạp module: /usr/lib/gio/modules/libgvfsdbus.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: wrong ELF class: ELFCLASS64
Lỗi nạp module: /usr/lib/gio/modules/libgioremote-volume-monitor.so

I tried Google, it was slightly related to Java, so I updated the Java version, but it still failed.
I ran Backtrack5r3 on the VM and Backtrack installed the necessary libraries for Ufonet. Please show me how to fix this.
And sorry I'm Vietnamese so I have to use Google Translate to write this message for you so if the words you do not understand then you sympathize for slightly because my language is not English. Thank you

**Comment by epsylon** [comment]
Hi,
I think this issue is related with your web browser (Firefox) and not with UFONet code:
https://www.linuxquestions.org/questions/linux-software-2/firefox-failed-to-load-module-errors-948913-print/
