### ISSUE TITLE
how to use --proxy=PROXY

### ISSUE THREAD

**Issue by Maitre-Oda** [epsylon/ufonet#117]
Hello to all the team.

thank you for your work.

I tried to create a docker ufonet (https://hub.docker.com/r/maitreoda/ufonet/).

My problem is that I can not use the proxy.

when I type the command --check-tor I still have the error message 

It seems that Tor is not properly set.

I tried by installing tor, privoxy, I also modify the conf file of privoxy, without success

can you help me ?

**Comment by epsylon** [comment]
Hi @Maitre-Oda
Remember that you need to use a transparent proxy (polipo, privoxy, ...), before sending your request to the Tor network. So your invokation should be like this:
./ufonet --check-tor --proxy="http://127.0.0.1:8118"
Also, you can add that proxy to your shell env, so you don't need to launch it using --proxy
Finally, you also can execute UFONet with for example: proxychains
I hope you find a value on this info.
Regards.

**Comment by Maitre-Oda** [comment]
it works perfectly now thank you

https://hub.docker.com/r/maitreoda/ufonet/

```
Sending request to: https://check.torproject.org

Congratulations!. Tor is properly being used :-)
```

**Comment by epsylon** [comment]
nice one!
many thanks to you for that docker task ;-)
