### ISSUE TITLE
[Error] - Something wrong testing ALL botnet status!

### ISSUE THREAD

**Issue by tussy2625** [epsylon/ufonet#118]
Hi, when i try to check all the zombies that error stop the test. When i start an attack, de number of zombies alway stop ant stay at 139 on the map. How can i fix it?

[Error] - Something wrong testing ALL botnet status!

Traceback (most recent call last):
  File "/root/Desktop/ufonet/core/main.py", line 701, in run
    test_all_botnet = self.testing_all()
  File "/root/Desktop/ufonet/core/main.py", line 2680, in testing_all
    rpcs_ready, num_active_rpcs, num_failed_rpcs = self.testing_rpcs(rpcs)
  File "/root/Desktop/ufonet/core/main.py", line 2491, in testing_rpcs
    rpc_vulnerable, rpc_pingback_url = self.search_rpc(rpc_host)
  File "/root/Desktop/ufonet/core/main.py", line 2353, in search_rpc
    return rpc_vulnerable, rpc_pingback_url
UnboundLocalError: local variable 'rpc_pingback_url' referenced before assignment

**Comment by trollmad3** [comment]
What version are you currently running?

**Comment by tussy2625** [comment]
De lastest version of ufonet(i do check update) on the lastest version on kali linux (freshly installed)

**Comment by epsylon** [comment]
Hi @tussy2625
I think that it is related with some XML-RPC zombies that are starting to fail (after last release) and UFONet is not making that unit-pass propertly on that task. I will review it. 
Thanks for your report.

**Comment by epsylon** [comment]
Fixed: https://github.com/epsylon/ufonet/commit/a19bb42a1ca9bfae3a364435b31b356e5c4e95e1
