### ISSUE TITLE
Number of zombies always stop at 139

### ISSUE THREAD

**Issue by tussy2625** [epsylon/ufonet#121]
Hi, on the map windows the number of zombies always stop connecting at 139, i guess the problem is the connection of the140th zombies? How can i fix it? 
I have already test all zombies, redownload the zombies from the blackhole and reinstall ufonet, nothing works.

The 140th zombies is http://validator.w3.org/nu/?doc=... 

And the command  " --sa " just dosnt work, it just restart ufonet and resend me to the starting "ufonet" drawing 

Im on the lastest update of ufonet and the most recent distributions of kali linux

**Comment by trollmad3** [comment]
The link you sent in your issue does not work.

**Comment by tussy2625** [comment]
Is the link of the last zombie loading on the map screen when i attack

**Comment by trollmad3** [comment]
Type in `./ufonet -t 'botnet/zombies.txt'` and post the results on here.

**Comment by tussy2625** [comment]
OK: 616 Fail: 6
==================

-------------------------

========================
Working 'zombies': 616
========================

Want to update your army? (Y/n)y
-------------------------

[Info] - Botnet updated! ;-)

**Comment by tussy2625** [comment]
another probleme ONLY when i use a VPN, in the graphic windows just get stuck at "Waiting for attacking results..." when i attack.  and the map windows just dont connect and dont load. but in the terminal all process run corectly. those 2 problems just happen wen i use a VPN

**Comment by trollmad3** [comment]
@tussy2625 When it says `OK: 616` did your botnet list get updated or is it stuck at 139?

**Comment by tussy2625** [comment]
My list update but when it load in the map screan, its always get stuck at 139/616

**Comment by trollmad3** [comment]
Disconnect from your VPN and try again. This could be a VPN problem.

**Comment by tussy2625** [comment]
When i turn off the vpn, the problem persist

**Comment by trollmad3** [comment]
@tussy2625 Can you create this problem again and take a screenshot of it and post it here?

**Comment by tussy2625** [comment]
![screenshot from 2018-08-23 19-52-55](https://user-images.githubusercontent.com/42327400/44550138-d899ad00-a712-11e8-87e5-d7eb4514c5e0.png)

in this image the number just get stuck to 110 since i have upload my zombies list

**Comment by epsylon** [comment]
It is curious that behavior about number 139, just because every time that you realize an attack with UFONet the entire botnet makes a suffle to evade probabilistics methods on IDS.
Btw, I am advancing code to a new release (v1.1) so I will add this issue as a review task.
Thanks for report it.

**Comment by epsylon** [comment]
Fixed: https://github.com/epsylon/ufonet/commit/7d328c507c114324b9d263306fdff41e085f6e10
