### ISSUE TITLE
GeoIP issue

### ISSUE THREAD

**Issue by DoomDogtheMiner** [epsylon/ufonet#124]
Hey, im trying to use UFONet on Kali 2018.03. everything is fine, but when i try to open the map, the following error comes up:
                      Error importing: pygeoip lib. 

                      On Debian based systems:

                      $ 'sudo apt-get install python-geoip' or 'pip install geoip')

Ive tried both options. APT is just saying that the package is already installed, and pip is outputting:            Requirement already satisfied: geoip in /usr/lib/python2.7/dist-packages
I dont know what the problem is!!

Thx for every help!

**Comment by DoomDogtheMiner** [comment]
i fixed the problem, but now the console isnt locating anything

**Comment by epsylon** [comment]
@DoomDogtheMiner : "but now the console isnt locating anything" -> What that mens?. 
Btw, remember that it takes a bit of time. Try it again and wait..

**Comment by DoomDogtheMiner** [comment]
I fixed this problem with a few tricks. Now im tryin to fix the problem, that the location of the zombies stops at around 230

**Comment by epsylon** [comment]
OK!
About that 'issue' related with map: https://github.com/epsylon/ufonet/issues/121#issuecomment-417150937
