### ISSUE TITLE
New version 1.1 still stuck at 139

### ISSUE THREAD

**Issue by Klapkaak078** [epsylon/ufonet#125]
Hello there Psy Epsylon

its still stuck at 139 zombies loading on the map, 
[Info] Adding zombie: http://validator.w3.org/nu/?doc=...

I trough this problem will got solved in the new update but stil exist.

I hope you can solve it!

Cheers Klapkaak078

**Comment by trollmad3** [comment]
What version are you at?

**Comment by Klapkaak078** [comment]
Hey Thanks for reply, have delete the older version, and download the New version 1.1 Quantum Hydra, but i got still the same problem as before in the 1.0 version, i have download All things that needed but it stay always stil on 139 zombies, loaded.

**Comment by trollmad3** [comment]
This should be fixed with https://github.com/epsylon/ufonet/commit/7d328c507c114324b9d263306fdff41e085f6e10

**Comment by Klapkaak078** [comment]
Yo, i already download All the things that a requered, there are more people with the dame problem, do you have the same problem?

**Comment by trollmad3** [comment]
@Klapkaak078 No I don't, I stopped using ufonet a while ago but I still help with peoples problems on the repository. Could you do `./ufonet -s 'proxy.php?url='` then screenshot what it says?

**Comment by Klapkaak078** [comment]
Hello Sir, 

![screenshot 160](https://user-images.githubusercontent.com/43372755/46109896-34f45e80-c1e2-11e8-992a-13c6c6f59884.png)

When i did the comment i get did i get this.

**Comment by epsylon** [comment]
hey @Klapkaak078
I haven't this issue during my tests. Let's check it again.
Tell me some things:
   - Which Os are you using for? (Kali...)
   - Do you have installed pygeoip? (ex: pip install python-geoip)?
   - When is happening? (attacking... re-creating botnet on /botnet panel...)
   - Are you using 'zombies' provided by community?
   - Do you have any clue about which 'zombie' is failing?
   - Did you tried to increase number of threads used by your OS?
   - [...]

**Comment by epsylon** [comment]
Ok. I have it!.

139 is the number of "zombies" from the Community List (~750) that are being resolved by "python-geoip" on the map. Rest are replying something like: "location cannot be solved"

For example, if you open "Map console" during map refreshing, you can see the URLs of those that are working. But, if we remove them from our list (botnet/zombies.txt) and refresh map again, we will see that not any other will be deployed (0/~600).

That means that:
   - UFONet code is working, almost on map deployment
   - python-geoip should be reviewed
   - GeoMap database should be reviewed

**Comment by epsylon** [comment]
related: https://dev.maxmind.com/geoip/legacy/geolite/

**Comment by Klapkaak078** [comment]
Hi there,

I have tried to update everything but so far no success.
i use kali linux in virtual box, and os version I do not know where to find it. the default version of python is 2.7.15

May I know which system you have ufonet on?

thanks for the quick response!
@ trollmad3 & @epsylon

Klapkaak078

**Comment by trollmad3** [comment]
@Klapkaak078 I stopped using ufonet. Due to @epsylon identifying the problem, can you do `sudo apt-get remove python-geoip` then do `sudo apt-get install python-geoip -y`?

**Comment by trollmad3** [comment]
@Klapkaak078 What happened when you re-installed `python-geoip`?

**Comment by Klapkaak078** [comment]
> @Klapkaak078 What happened when you re-installed `python-geoip`?

Hello sir, 

i get normal reaction when i install it.

root@kali:~# pip install python-geoip
Collecting python-geoip
  Downloading https://files.pythonhosted.org/packages/23/91/ca12b671f11cf774ab851d68770d9a0b2f29b1f1888da8b946faf8d3f2eb/python_geoip-1.2-py27-none-any.whl
Installing collected packages: python-geoip
Successfully installed python-geoip-1.2
root@kali:~# 

but still hangs in 139. its nor the problem from 
the community zombies i dont know what the problem is, try alot but thanks for the help!
gonna try to delete the kali and do a new install.

Klapkaak078

**Comment by epsylon** [comment]
This issue, at some point, is exclusively related with external libs. 
I will take a look but, by the moment, I close it.

**Comment by epsylon** [comment]
Thanks @r0kford !
I have added for next release (v1.2) a control system on the map that try to evade that situation, just plotting only valid zombies.
