### ISSUE TITLE
[Suggestion] Can I make a video?

### ISSUE THREAD

**Issue by trollmad3** [epsylon/ufonet#126]
Can I make a video demonstrating how to use ufonet and set it up? This could help new people using ufonet. 

EDIT: The video will be on here, for previews.

EDIT 2: Video is [https://streamable.com/p3n9v](https://streamable.com/p3n9v)

**Comment by epsylon** [comment]
nice one!

**Comment by trollmad3** [comment]
@epsylon Is it okay if I put it in the readme?

**Comment by epsylon** [comment]
replied: https://github.com/epsylon/ufonet/pull/127
