### ISSUE TITLE
a stop function would be cool 

### ISSUE THREAD

**Issue by crypto-maniac** [epsylon/ufonet#132]
Hello Ufonet , could you add please a stop function ?
./ufonet stop 

thanks you

**Comment by trollmad3** [comment]
I don't see why this is needed when you can just `Ctrl + C`.

**Comment by epsylon** [comment]
Hi,
@crypto-maniac maybe you can explain a bit more your request.
Which kind of stop function do you want?.

**Comment by LulzRose** [comment]
> Hi,
> @crypto-maniac maybe you can explain a bit more your request.
> Which kind of stop function do you want?.

I believe that maniac is saying he wants a way to stop the zombie searching without ending the program. Basically stop the search and immediatly start working on the head check.

**Comment by trollmad3** [comment]
@LulzRose This is _probably_ what he meant. If he has `htop` then cant you just use that to stop it?

**Comment by crypto-maniac** [comment]
hello , yes i was playing with the toy and i release there where fiew process launched when i do  top command, so yes i stoped them via kill but when we do a scan and want to stop it with  Ctr + c  the tool continue to run as far i can see

**Comment by trollmad3** [comment]
@crypto-maniac Do you have `htop` installed? If you dont, type in `apt-get install htop -y` then run `htop`. I think its F9 or F10 that is kill. Press the button that is labeled **KILL** in the tool. Find ufonet on the list and kill it.

**Comment by epsylon** [comment]
sometimes, when Crt + c isn't working... you can try to abort it with: Crt + z
btw, I will check that functionallity for next release.
thanks!
