### ISSUE TITLE
When i type anything its showing the start page...

### ISSUE THREAD

**Issue by yoerithor** [epsylon/ufonet#137]
When i type anything its showing the start page... Like if i type ./ufonet —gui , its showing me the start page... How to solve this? Thanks...

**Comment by yoerithor** [comment]
https://imgur.com/a/GrXasN0

**Comment by trollmad3** [comment]
You typed `./ufonet -help` into that box, not `./ufonet --gui``. Please take the image again with `./ufonet --gui`

**Comment by yoerithor** [comment]
My keyboard was just doing a weird rhong, of 2 '-' it made one. You mau close this post

**Comment by trollmad3** [comment]
@yoerithor Since you created this issue, you have to or @epsylon can.

**Comment by trollmad3** [comment]
@epsylon Please close this issue, as he said its fixed. He is not active and this issue will remain open if you do not close it.

**Comment by epsylon** [comment]
@trollmad3 roger that!
