### ISSUE TITLE
Windows Compatibility issues with GeoIP

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#139]
Hello, 
I am attempting to run ufonet on my Windows 10 device due to better specs than my old linux thinkpad and am having issues when installing ufonet. I cloned it fully but when running setup.py I get this at the end of the programming. Do you know of any fix to setup geoip correctly. `Searching for GeoIP>=1.3.2
Reading https://pypi.python.org/simple/GeoIP/
Downloading https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz#sha256=a890da6a21574050692198f14b07aa4268a01371278dfc24f71cd9bc87ebf0e6
Best match: GeoIP 1.3.2
Processing GeoIP-1.3.2.tar.gz
Writing c:\users\kurtm\appdata\local\temp\easy_install-cgvb_i\GeoIP-1.3.2\setup.cfg
Running GeoIP-1.3.2\setup.py -q bdist_egg --dist-dir c:\users\kurtm\appdata\local\temp\easy_install-cgvb_i\GeoIP-1.3.2\egg-dist-tmp-bhze7t
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
warning: no files found matching 'ChangeLog'
cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasing'
py_GeoIP.c
py_GeoIP.c(23) : fatal error C1083: Cannot open include file: 'GeoIP.h': No such file or directory
error: Setup script exited with error: command 'C:\\Users\\kurtm\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2`

**Comment by trollmad3** [comment]
Is your firewall or antivirus blocking it?

**Comment by LulzRose** [comment]
Attempted to run with all firewalls disabled and antivirus off and got the exact same error.
System Info:
Windows 10 Home 64bit Build 17134

**Comment by LulzRose** [comment]
Is there any way to replace geoip with pygeoip since geoip is technically legacy

**Comment by trollmad3** [comment]
Your better off running UFOnet on Linux to help with the errors your facing.

**Comment by LulzRose** [comment]
Ok I decided to attempt the Windows Linux Subsystem and things seem to be working properly

**Comment by trollmad3** [comment]
That's good. Are you going to close this issue now? @LulzRose
