### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by DarkGohst** [epsylon/ufonet#14]
Hi Guys,
When I type ./ufonet it came:
/Schreibtisch/ufonet-v0.7/ufonet $ ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/user/Schreibtisch/ufonet-v0.7/ufonet/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
ImportError: No module named requests

What can I do?
Thanks for Help!
p.s :My English is Bad :-(

**Comment by SharDX** [comment]
Are you using windows ?

**Comment by epsylon** [comment]
http://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by DarkGohst** [comment]
Thank you for The Support
p.s Im using linux Mint. Which operating system you can suggest me?
