### ISSUE TITLE
Error when testing zombies from humans.txt

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#140]
After a long auto search Hitting upwards of 100k results I moved the data from humans.txt to zombies.txt in order to check them as working. When I ran this I received an error at both 400k zombies to test and 40k zombies to  test. Here is the error:

`

===========================================================================
Are 'they' alive? :-) (HEAD Check):
===================================
Trying: 42107
---------------------

[Error] - Something wrong testing!
Traceback (most recent call last):

  File "/home/rose/ufonet/core/main.py", line 769, in run
    test = self.testing(zombies)
  File "/home/rose/ufonet/core/main.py", line 2842, in testing
    reply = self.connect_zombies(zombie)
  File "/home/rose/ufonet/core/main.py", line 970, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
>>>
`

**Comment by trollmad3** [comment]
What version are you running UFONet on?

**Comment by LulzRose** [comment]
The newest version (Pulled all yesterday)

**Comment by trollmad3** [comment]
Could you run the command again with `-v` added then post the results?

**Comment by LulzRose** [comment]
hmm seems to have repaired itself

**Comment by trollmad3** [comment]
that's weird....maybe it was a network problem.
