### ISSUE TITLE
Issue I Always Have

### ISSUE THREAD

**Issue by Animebammer** [epsylon/ufonet#141]
So whenever I attempt using Ufonet, randomly when I'm attacking or updating my botnet (with all the search engines via the GUI) it just stops functioning or becomes really slow. Any way this can be fixed? (I'm 100% sure I installed it correctly)

**Comment by trollmad3** [comment]
Can you add `-v` to the command and post the results here?

**Comment by epsylon** [comment]
Hi,
Which versions are you using (OS, python, UFONet...)
Do you have any output or traceback to be reviewed?
How are you managing to measure that UFONet is "getting slow" ?
Are you trying UFONet over a container (VM, docker..)?
[...]
Please, answer to those questions to have more info about.

**Comment by Animebammer** [comment]
> 
> 
> Hi,
> Which versions are you using (OS, python, UFONet...)
> Do you have any output or traceback to be reviewed?
> How are you managing to measure that UFONet is "getting slow" ?
> Are you trying UFONet over a container (VM, docker..)?
> [...]
> Please, answer to those questions to have more info about.

https://drive.google.com/file/d/1WG4fyCVYH06K5hsKftjiMSKPNiE97qi0/view?usp=sharing

**Comment by epsylon** [comment]
Please, try to add your reports here (not using external services, google, etc..) almost if you want to be helped. Thanks.

**Comment by trollmad3** [comment]
@Animebammer Please describe the error in more detail here, not google drive.
