### ISSUE TITLE
How to boot IPs?

### ISSUE THREAD

**Issue by trollmad3** [epsylon/ufonet#142]
As an example, the IP will be `172.27.0.54` 

How would I target an IP but not a host? I  tried to do `./ufonet -a 172.27.0.54` but it said the host was down. I also tried to do IP 2 HOSTNAME and target the hostname, but that did nothing also.

**Comment by epsylon** [comment]
Try, directly:
http://xxx.xx.xx.xx or using SSL, https://xxx.xx.xx.xx
