### ISSUE TITLE
Ufonet "Something Wrong" Error

### ISSUE THREAD

**Issue by 3rt4nm4n** [epsylon/ufonet#144]
Hello,

Recently I have begun to use ufonet experimentally to develop my knowledge on cyber security. 
When I tried to recruit my bots with "./ufonet --auto-search" on kali after a little while I kept on receiving an output saying " [Error] - Something Wrong..... auto searching"

[https://snag.gy/tVTikY.jpg](url)

Can you please help me solve this problem?

Note: Ufonet is v1.1
Not using Tor since it is forbidden in my location and when tried to be used Internet speed drops to 10kbps

**Comment by epsylon** [comment]
Hi,
I have reciently fixed, for new code that will be released soon (Ufonet v1.2), a problem related with locations and Yahoo search engine. Is that you case?
