### ISSUE TITLE
Error importing: scapy lib

### ISSUE THREAD

**Issue by ofbahar** [epsylon/ufonet#148]
Hi,
i have just installed ufonet and i'm using kali linux.
i ran pip install scapy.
then i ran ./ufonet and  than the error shows up:

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python-scapy' or 'pip install scapy'

then i ran 'pip install scapy' it shows:

Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages/scapy-2.4.2-py2.7.egg (2.4.2)
so what should I do

**Comment by trollmad3** [comment]
Type `pip freeze` into terminal and post the results here.

**Comment by ofbahar** [comment]
``Warning: cannot find svn location for chirp===daily-20190104
IPy==0.83
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==1.0.0.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
atomicwrites==1.1.5
attrs==18.2.0
autobahn==17.10.1
Automat==0.6.0
Babel==2.6.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.1.0
BBQSQL==1.0
bcrypt==3.1.5
bdfproxy==0.0.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.3
BlindElephant==1.0
blinker==1.4
boltons==18.0.1
capstone==3.0.5
cbor==1.0.0
certifi==2018.8.24
chardet==3.0.4
Cheetah3==3.1.0
CherryTree==0.38.5
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20190104
clamd==1.0.1
Click==7.0
click-plugins==1.0.4
cluster==1.3.3
colorama==0.3.7
ConfigArgParse==0.13.0
configobj==5.0.6
configparser==3.5.0b2
constantly==15.1.0
construct==2.8.16
couchdbkit==0.6.5
cryptography==2.3
cycler==0.10.0
Cython==0.28.4
d2to1==0.2.12
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.3.0
defusedxml==0.5.0
deprecation==2.0.6
dhcpig==0.0.0
dicttoxml==1.7.4
dissy==9
distorm3==3.4.1
dnslib==0.9.7
dnspython==1.16.0
docutils==0.14
easygui==0.96
EasyProcess==0.2.3
ecdsa==0.13
EditorConfig==0.12.1
Elixir==0.7.1
entrypoints==0.2.3
enum34==1.1.6
esmre==0.3.1
esptool==2.5.1
et-xmlfile==1.0.1
feedparser==5.2.1
filedepot==0.5.2
filteralchemy==0.1.0
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Restless==0.17.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
FormEncode==1.3.0
funcsigs==1.0.2
fuse-python==0.3.1
future==0.15.2
futures==3.2.0
fuzzywuzzy==0.17.0
GDAL==2.4.0
GeoIP==1.3.2
geoip2==2.9.0
geojson==2.4.1
gevent==1.3.7
gitdb2==2.0.5
GitPython==2.1.11
greenlet==0.4.15
guess-language-spirit==0.5.2
h2==3.0.1
Hackersh==0.2.0
halberd==0.2.4
hpack==3.0.0
html2text==2018.1.9
html5lib==1.0.1
http-parser==0.8.3
httplib2==0.11.3
httpretty==0.9.5
hyperframe==5.1.0
hyperlink==17.3.1
icalendar==4.0.3
idna==2.6
impacket==0.9.17
incremental==16.10.1
ipaddress==1.0.17
ipython==5.8.0
ipython-genutils==0.2.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.10
jsbeautifier==1.6.4
jsonpickle==0.9.5
jsonrpclib==0.1.7
keepnote==0.7.8
keyring==17.1.1
keyrings.alt==3.1.1
killerbee==1.0
kiwisolver==1.0.1
ldap3==2.4.1
lxml==4.2.5
lz4==1.1.0
M2Crypto==0.31.0
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
marshmallow==3.0.0b3
marshmallow-sqlalchemy==0.14.1
matplotlib==2.2.3
maxminddb==1.4.1
mechanize==0.2.5
mercurial==4.8.2
metaconfig==0.1.4a1
mimerender==0.6.0
mockito==0.5.2
more-itertools==4.2.0
msgpack==0.5.6
msgpack-python==0.5.6
mysqlclient==1.3.10
nassl==0.12
ndg-httpsclient==0.5.1
netaddr==0.7.19
NetfilterQueue==0.6
networkx==2.2
NfSpy==1.0
nltk==3.4
nose==1.3.7
nplusone==1.0.0
numpy==1.16.0rc2
olefile==0.46
openpyxl==2.4.9
OWSLib==0.17.0
packaging==18.0
PAM==0.4.2
paramiko==2.4.2
passlib==1.7.1
Paste==3.0.5
PasteDeploy==2.0.1
PasteScript==2.0.2
pathlib2==2.3.3
pathtools==0.1.2
pcapy==0.10.8
pdfminer==20140328
peepdf==0.4.2
pefile==2018.8.8
pexpect==4.6.0
phply==1.2.5
pickleshare==0.7.5
Pillow==5.3.0
pluggy==0.8.0
ply==3.11
prettytable==0.7.2
prompt-toolkit==1.0.15
psutil==5.4.8
psycopg2==2.7.6.1
py==1.7.0
py-ubjson==0.12.0
pyaes==1.6.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pybloomfiltermmap==0.3.15
pycairo==1.16.2
pycrypto==2.6.1
pycryptodomex==3.6.1
pycryptopp==0.7.1
pycurl==7.43.0.2
pydns==2.3.6
pydot==1.4.1
pyenchant==2.0.0
pygeoip==0.3.2
PyGithub==1.23.0
Pygments==2.2.0
PyGObject==3.30.4
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.7.1
pymssql==2.1.3
PyNaCl==1.3.0
PyOpenGL==3.1.0
pyOpenSSL==18.0.0
pyotp==2.2.6
pyparsing==2.2.0
pypcap==1.2.2
pyPdf==1.13
PyPDF2==1.26.0
pyperclip==1.6.4
pyproj==1.9.6
pyrit==0.5.1
pyrtlsdr==0.2.9
pyscard==1.9.7
pyserial==3.4
pyshp==2.0.1
PySide==1.2.2
PySimpleSOAP==1.16.2
pysmi==0.3.2
pysnmp==4.4.6
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.8
pyspatialite==3.0.1
pysqlite==2.7.0
pytesseract==0.2.5
pytest==3.10.1
python-apt==1.7.0
python-dateutil==2.6.1
python-debian==0.1.33
python-debianbts==2.8.2
python-editor==1.0.3
python-Levenshtein==0.12.0
python-magic==0.4.16
python-mimeparse==0.1.4
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.4
python-slugify==1.2.5
python-snappy==0.5.3
python-whois==0.7.1
pythonaes==1.0
Pythonect==0.6.0
PyTrie==0.2
pytz==2018.7
pyusb==1.0.2
PyV8==1.0.dev0
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.13
pyzmq==17.1.2
qrcode==6.0
qt4reactor==1.0
reportbug==6.6.6
requests==2.20.0
restkit==4.2.2
rfcat==1.0
rfidiot==1.0
roman==2.0.0
rsa==4.0
rtlsdr-scanner==1.3.1
ruamel.ordereddict==0.4.13
scandir==1.9.0
scapy==2.4.2
scgi==1.13
scipy==1.1.0
SecretStorage==2.3.1
selenium==3.14.1
service-identity==16.0.0
Shapely==1.6.4
shodan==1.10.4
simplegeneric==0.8.1
simplejson==3.15.0
singledispatch==3.4.0.3
sipvicious==0.2.8
six==1.12.0
slowaes==0.1a1
smmap2==2.0.5
smoke-zephyr==1.4.0
SOAPpy==0.12.22
socketpool==0.5.3
speaklater==1.3
specan==0.0.0
SQLAlchemy==1.2.15
sqlalchemy-schemadisplay==1.3
stopit==1.1.0
subprocess32==3.5.3
tblib==1.3.2
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==5.1.1
tqdm==4.28.1
traitlets==4.3.2
trollius==2.0.1
Twisted==18.9.0
txaio==2.10.0
typing==3.6.6
tzlocal==1.5.1
u-msgpack-python==2.1
ua-parser==0.8.0
ufonet==1.2
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.24
urwid==2.0.1
user-agents==1.1.0
uTidylib==0.5
vinetto==0.7b0
visvis==1.11.1
volatility==2.6
vulndb==0.1.1
watchdog==0.9.0
wcwidth==0.1.7
webargs==4.0.0
webencodings==0.5.1
websocket-client==0.53.0
webunit==1.3.10
Werkzeug==0.14.1
whois==0.7
Whoosh==2.7.4
wifite==2.2.5
wsaccel==0.6.2
wstools==0.4.3
WTForms==2.2.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.8.0
zenmap==7.70
zim==0.68
zope.interface==4.3.2

**Comment by ofbahar** [comment]
Warning: cannot find svn location for chirp===daily-20190104
IPy==0.83
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==1.0.0.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
atomicwrites==1.1.5
attrs==18.2.0
autobahn==17.10.1
Automat==0.6.0
Babel==2.6.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.1.0
BBQSQL==1.0
bcrypt==3.1.5
bdfproxy==0.0.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.3
BlindElephant==1.0
blinker==1.4
boltons==18.0.1
capstone==3.0.5
cbor==1.0.0
certifi==2018.8.24
chardet==3.0.4
Cheetah3==3.1.0
CherryTree==0.38.5
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20190104
clamd==1.0.1
Click==7.0
click-plugins==1.0.4
cluster==1.3.3
colorama==0.3.7
ConfigArgParse==0.13.0
configobj==5.0.6
configparser==3.5.0b2
constantly==15.1.0
construct==2.8.16
couchdbkit==0.6.5
cryptography==2.3
cycler==0.10.0
Cython==0.28.4
d2to1==0.2.12
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.3.0
defusedxml==0.5.0
deprecation==2.0.6
dhcpig==0.0.0
dicttoxml==1.7.4
dissy==9
distorm3==3.4.1
dnslib==0.9.7
dnspython==1.16.0
docutils==0.14
easygui==0.96
EasyProcess==0.2.3
ecdsa==0.13
EditorConfig==0.12.1
Elixir==0.7.1
entrypoints==0.2.3
enum34==1.1.6
esmre==0.3.1
esptool==2.5.1
et-xmlfile==1.0.1
feedparser==5.2.1
filedepot==0.5.2
filteralchemy==0.1.0
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Restless==0.17.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
FormEncode==1.3.0
funcsigs==1.0.2
fuse-python==0.3.1
future==0.15.2
futures==3.2.0
fuzzywuzzy==0.17.0
GDAL==2.4.0
GeoIP==1.3.2
geoip2==2.9.0
geojson==2.4.1
gevent==1.3.7
gitdb2==2.0.5
GitPython==2.1.11
greenlet==0.4.15
guess-language-spirit==0.5.2
h2==3.0.1
Hackersh==0.2.0
halberd==0.2.4
hpack==3.0.0
html2text==2018.1.9
html5lib==1.0.1
http-parser==0.8.3
httplib2==0.11.3
httpretty==0.9.5
hyperframe==5.1.0
hyperlink==17.3.1
icalendar==4.0.3
idna==2.6
impacket==0.9.17
incremental==16.10.1
ipaddress==1.0.17
ipython==5.8.0
ipython-genutils==0.2.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.10
jsbeautifier==1.6.4
jsonpickle==0.9.5
jsonrpclib==0.1.7
keepnote==0.7.8
keyring==17.1.1
keyrings.alt==3.1.1
killerbee==1.0
kiwisolver==1.0.1
ldap3==2.4.1
lxml==4.2.5
lz4==1.1.0
M2Crypto==0.31.0
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
marshmallow==3.0.0b3
marshmallow-sqlalchemy==0.14.1
matplotlib==2.2.3
maxminddb==1.4.1
mechanize==0.2.5
mercurial==4.8.2
metaconfig==0.1.4a1
mimerender==0.6.0
mockito==0.5.2
more-itertools==4.2.0
msgpack==0.5.6
msgpack-python==0.5.6
mysqlclient==1.3.10
nassl==0.12
ndg-httpsclient==0.5.1
netaddr==0.7.19
NetfilterQueue==0.6
networkx==2.2
NfSpy==1.0
nltk==3.4
nose==1.3.7
nplusone==1.0.0
numpy==1.16.0rc2
olefile==0.46
openpyxl==2.4.9
OWSLib==0.17.0
packaging==18.0
PAM==0.4.2
paramiko==2.4.2
passlib==1.7.1
Paste==3.0.5
PasteDeploy==2.0.1
PasteScript==2.0.2
pathlib2==2.3.3
pathtools==0.1.2
pcapy==0.10.8
pdfminer==20140328
peepdf==0.4.2
pefile==2018.8.8
pexpect==4.6.0
phply==1.2.5
pickleshare==0.7.5
Pillow==5.3.0
pluggy==0.8.0
ply==3.11
prettytable==0.7.2
prompt-toolkit==1.0.15
psutil==5.4.8
psycopg2==2.7.6.1
py==1.7.0
py-ubjson==0.12.0
pyaes==1.6.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pybloomfiltermmap==0.3.15
pycairo==1.16.2
pycrypto==2.6.1
pycryptodomex==3.6.1
pycryptopp==0.7.1
pycurl==7.43.0.2
pydns==2.3.6
pydot==1.4.1
pyenchant==2.0.0
pygeoip==0.3.2
PyGithub==1.23.0
Pygments==2.2.0
PyGObject==3.30.4
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.7.1
pymssql==2.1.3
PyNaCl==1.3.0
PyOpenGL==3.1.0
pyOpenSSL==18.0.0
pyotp==2.2.6
pyparsing==2.2.0
pypcap==1.2.2
pyPdf==1.13
PyPDF2==1.26.0
pyperclip==1.6.4
pyproj==1.9.6
pyrit==0.5.1
pyrtlsdr==0.2.9
pyscard==1.9.7
pyserial==3.4
pyshp==2.0.1
PySide==1.2.2
PySimpleSOAP==1.16.2
pysmi==0.3.2
pysnmp==4.4.6
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.8
pyspatialite==3.0.1
pysqlite==2.7.0
pytesseract==0.2.5
pytest==3.10.1
python-apt==1.7.0
python-dateutil==2.6.1
python-debian==0.1.33
python-debianbts==2.8.2
python-editor==1.0.3
python-Levenshtein==0.12.0
python-magic==0.4.16
python-mimeparse==0.1.4
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.4
python-slugify==1.2.5
python-snappy==0.5.3
python-whois==0.7.1
pythonaes==1.0
Pythonect==0.6.0
PyTrie==0.2
pytz==2018.7
pyusb==1.0.2
PyV8==1.0.dev0
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.13
pyzmq==17.1.2
qrcode==6.0
qt4reactor==1.0
reportbug==6.6.6
requests==2.20.0
restkit==4.2.2
rfcat==1.0
rfidiot==1.0
roman==2.0.0
rsa==4.0
rtlsdr-scanner==1.3.1
ruamel.ordereddict==0.4.13
scandir==1.9.0
scapy==2.4.2
scgi==1.13
scipy==1.1.0
SecretStorage==2.3.1
selenium==3.14.1
service-identity==16.0.0
Shapely==1.6.4
shodan==1.10.4
simplegeneric==0.8.1
simplejson==3.15.0
singledispatch==3.4.0.3
sipvicious==0.2.8
six==1.12.0
slowaes==0.1a1
smmap2==2.0.5
smoke-zephyr==1.4.0
SOAPpy==0.12.22
socketpool==0.5.3
speaklater==1.3
specan==0.0.0
SQLAlchemy==1.2.15
sqlalchemy-schemadisplay==1.3
stopit==1.1.0
subprocess32==3.5.3
tblib==1.3.2
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==5.1.1
tqdm==4.28.1
traitlets==4.3.2
trollius==2.0.1
Twisted==18.9.0
txaio==2.10.0
typing==3.6.6
tzlocal==1.5.1
u-msgpack-python==2.1
ua-parser==0.8.0
ufonet==1.2
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.24
urwid==2.0.1
user-agents==1.1.0
uTidylib==0.5
vinetto==0.7b0
visvis==1.11.1
volatility==2.6
vulndb==0.1.1
watchdog==0.9.0
wcwidth==0.1.7
webargs==4.0.0
webencodings==0.5.1
websocket-client==0.53.0
webunit==1.3.10
Werkzeug==0.14.1
whois==0.7
Whoosh==2.7.4
wifite==2.2.5
wsaccel==0.6.2
wstools==0.4.3
WTForms==2.2.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.8.0
zenmap==7.70
zim==0.68
zope.interface==4.3.2

**Comment by trollmad3** [comment]
It appears you have `scapy==2.4.2` installed already. Type `pip uninstall scapy` and then type `pip install scapy` again.

**Comment by ofbahar** [comment]
Unfortunately, it's not working

**Comment by trollmad3** [comment]
Could you post the error that it gives *when* you try to install it?

**Comment by epsylon** [comment]
Did you tried: sudo apt-get install python-scapy ?

**Comment by epsylon** [comment]
Btw, try first:
python setup.py install

---------------------

required: scapy >= 2.3.3
scapy 2.4.2 -> https://pypi.org/project/scapy/

**Comment by ofbahar** [comment]
> Did you tried: sudo apt-get install python-scapy ?

Yes i tried this. But it say "python-scapy is already in the newest version"

**Comment by ofbahar** [comment]
> Btw, try first:
> python setup.py install
> 
> required: scapy >= 2.3.3
> scapy 2.4.2 -> https://pypi.org/project/scapy/

I already did it

**Comment by ofbahar** [comment]
![ekran goruntusu-20190127123353-734x498](https://user-images.githubusercontent.com/46934606/51799273-8cf2ae80-2230-11e9-8474-8dad807dfd46.png)
![ekran goruntusu-20190127123158-734x498](https://user-images.githubusercontent.com/46934606/51799278-9d0a8e00-2230-11e9-866e-e2a1f2d5a678.png)

**Comment by epsylon** [comment]
"using IPython 5.8.0" -> check this... looks something wrong on you python libs package manager.

**Comment by ofbahar** [comment]
I SOLVE IT!
Problem from dist-upgrade welded.
I run "apt-get install matplotlib" for mitmf. And mitmf fixed but ufonet gave scapy error.
Than i run "apt-get remove matplotlib" and problem fixed!

**Comment by epsylon** [comment]
Nice one!

**Comment by 0wna** [comment]
Can anybody help ne please ,same problem only another lib ,cryptography İs installed but ufonet1.41 can not load the lib. :/ I want use the ufonet gui

**Comment by 0wna** [comment]
😂😂😂😂i fixed it..

**Comment by gokuLc2127** [comment]
Same problem can anyone please help me . Error importing scapy lib . I did everything and I don't no what's the problem pls help

**Comment by epsylon** [comment]
@gokuLc2127 -> https://github.com/epsylon/ufonet/issues/274

**Comment by FrankensteinEvil0069** [comment]
> I SOLVE IT!
> Problem from dist-upgrade welded.
> I run "apt-get install matplotlib" for mitmf. And mitmf fixed but ufonet gave scapy error.
> Than i run "apt-get remove matplotlib" and problem fixed!

but it didnt solve the problem in my case

**Comment by epsylon** [comment]
@FrankensteinEvil0069 -> https://github.com/epsylon/ufonet/issues/274#issuecomment-748386563 ?

**Comment by FrankensteinEvil0069** [comment]
> @FrankensteinEvil0069 -> [#274 (comment)](https://github.com/epsylon/ufonet/issues/274#issuecomment-748386563) ?

root@shreyas-kali-linux:~/ufonet# apt-get remove matplotlib
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package matplotlib

root@shreyas-kali-linux:~/ufonet# python3 ufonet --download-zombies

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy

**Comment by Core0712** [comment]
Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'
ive already done everything i could think of and it still wont work

**Comment by epsylon** [comment]
@Core0712 try this: **pip3 install scapy-python3**

**Comment by Badpower3569** [comment]
Error importing: scapy lib.

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'



I need help

**Comment by Aholicknight** [comment]
> Error importing: scapy lib.
> 
> To install it on Debian based systems:
> 
> $ 'sudo apt-get install python3-scapy'
> 
> I need help

@Badpower3569 Create your own new issue instead of commenting on an issue that's closed since 2019.
