### ISSUE TITLE
[Error] [AI] Something wrong (auto)searching...

### ISSUE THREAD

**Issue by nameless4687** [epsylon/ufonet#149]
I got this error when use auto searching, is anyway to fix it ?

**Comment by epsylon** [comment]
Hi,
Is that related with 'Bing' search engine?. Can you try it again but using -v (--verbose) mode?

**Comment by Yaguaa** [comment]
Hi,
I tried this (--auto-search -v) (--verbose --auto-search) and I got the same error at each command.
Do you have an issue ?

**Comment by Aholicknight** [comment]
@Yaguaa Repeat the same command you did with `-v` and post the results here.
