### ISSUE TITLE
Backhole fail ?

### ISSUE THREAD

**Issue by DarkGohst** [epsylon/ufonet#15]
Hi Guys,
My friend have another problem when he try to download zombies.
It came:

===========================================================================

Downloading list of 'zombies' from server ...

======================

Trying 'blackhole': 176.28.XX.XX

Vortex: IS READY!
------------

[Error] - Something wrong downloading!
Not a gzipped file

Thanks for help

**Comment by SharDX** [comment]
lol i dont know how to fix this but you can just send him the zombies.txt
and aliens.txt 
till dev replies 
also he can search for zombies

**Comment by DarkGohst** [comment]
ok. Thanks

**Comment by epsylon** [comment]
maybe 'blackhole' was not working on this time... so your friend cannot reach *.txt.gz files. 
try it again...

**Comment by christianhito** [comment]
the issue may be closed, but it is important to remind that sometimes there is blackhole issue with python older than 2.7. i got my issue fixed with python 2.7
