### ISSUE TITLE
Privoxy/UFONET and "Something Wrong" Error 

### ISSUE THREAD

**Issue by MrTuxx** [epsylon/ufonet#151]
Hi, Im starting to use UFONET and I have some doubts:

1 - I have read that is convenient use UFONET with a transparent proxy, like privoxy (I have taken as reference,  https://03c8.net/ and others webs) and connect it to TOR. So i did:

![image](https://user-images.githubusercontent.com/48191819/53833395-49ead000-3f80-11e9-9ee4-930808982317.png)
![image](https://user-images.githubusercontent.com/48191819/53833436-6a1a8f00-3f80-11e9-9db2-04f94fbf584b.png)

But when I do:

![image](https://user-images.githubusercontent.com/48191819/53833605-d9907e80-3f80-11e9-801d-048d3a1ad2ae.png)

Appears my publi IP and it tells me that it is not properly configurated. Instead if I use Proxychains, sometimes it works and other doesn’t, but when works correctly you can see:

![image](https://user-images.githubusercontent.com/48191819/53833803-528fd600-3f81-11e9-9bc7-fdb4bb4c6e48.png)
![image](https://user-images.githubusercontent.com/48191819/53833815-5ae81100-3f81-11e9-964e-7c83ce199a1c.png)

Shown all this, What can I be doing wrong so UFONET doesn’t work for me with privoxy? Would be “safe” to use it with Proxychains as seen in the image (question 2 arises using proxychains)?

2 - When I make a search of zombies without using any proxy, I usually complete every phase, that is, looking for with dorks, store possible zombies in humans.txt and validate them to update zombies.txt. Although, sometimes, in some of these phases it shows me that if I want to change my browser or that something went wrong because I can't connect to Yahoo or Bing. I've also noticed that the more content I have in humans.txt, the more I see this kind of messages, I suppose this happens because I'm not using a proxy that blocks my IP, am I right?

![image](https://user-images.githubusercontent.com/48191819/53834015-dfd32a80-3f81-11e9-93db-61e4fcba422d.png)
![image](https://user-images.githubusercontent.com/48191819/53834029-ec578300-3f81-11e9-9adb-56c6fd1451c3.png)

However, when I do the search using Proxychains (I use this as a reference of the first question), usually, it doesn't show me any message like the previously commented (I think it is because using the proxy connected to TOR is harder to block my IP, I don't know if my theory is right) but when I validate the possible zombies, all of them always fail because none of them responds and in verbose, you can't see the header to see if it has a 200 or not, is it a proxichains problem? Am I missusing the searches?

![image](https://user-images.githubusercontent.com/48191819/53834237-6425ad80-3f82-11e9-8144-b52ba7f9fe60.png)
![image](https://user-images.githubusercontent.com/48191819/53834243-6982f800-3f82-11e9-8c17-a370793a3ea9.png)

Or sometimes it doesn’t even get to perform the validation because the following happens:

![image](https://user-images.githubusercontent.com/48191819/53834281-828ba900-3f82-11e9-9ca1-f49b7112bdb5.png)

Any idea why I get this?

Thanks!!

**Comment by almaromr** [comment]
Exactly the same thing happens to me, I'm doing human searches of almost 1M but I never reach the end.

**Comment by almaromr** [comment]
Exactly the same thing happens to me, I'm doing human searches of almost 100k but I never reach the end.
![ufonet](https://user-images.githubusercontent.com/36208512/53950121-cb02ae00-40cb-11e9-9308-18db56370294.PNG)

**Comment by epsylon** [comment]
Hi,
1) I think this is related with a problem with your shell env. You haven't exported them correctly, which means that you aren't using proxy when spelling new commads. For example:
HTTP_PROXY=http://127.0.0.1:8118
HTTPS_PROXY=http://127.0.0.1:8118
http_proxy=http://127.0.0.1:8118
https_proxy=http://127.0.0.1:8118
all_proxy=http://127.0.0.1:8118
ALL_PROXY=http://127.0.0.1:8118
You can try to export it with, ex:
export http_proxy=http://127.0.0.1:8118
This probably will make that when you spell UFONet like:
./ufonet --check-tor (without the need to enter proxy as command) it will return a sucess..
1b) You can use proxychains as well, but remember that you need to tunnel also DNS traffic at your conf to evade DNS-leaks problems.
2) Yep, when using a proxy and making so much request to search engines, these tries to block you, sometimes (and mostly) using a captcha. A trick: If you open a browser manually and fill that captcha, your automatic requests will work again.
2b) I think is related with a bad configuration on your side (when using a transparent proxy). Probably fixing that you will haven't again that problems with auto-search.

**Comment by epsylon** [comment]
Ok. I have seen another problem on your conf.
Try to don't use IPv6 (or to deactivate it) if you don't need it, because you are having problems to complete DNS requests. Look at figure 3:
DNS-requests ::1
[DNS-RESPONSE] ::1 doesnt exits
Your TOR+Privoxy isn't working as expected.
