### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Vdevv** [epsylon/ufonet#152]
Something on new version is broken after a long time of auto search for zombies the zombies.txt is empty and the zombies are written in humans.txt also some of the other files for example rpcs.txt are empty.

**Comment by trollmad3** [comment]
Can you post the output ufonet gives?

**Comment by Vdevv** [comment]
There is no error message or something i just noticed that some of the files got totally empty. I dont know if that happened cause i updated to new version from an old one that i had.

**Comment by trollmad3** [comment]
@Vdevv I'm not talking about the error message. When you do the UFOnet command, what does it output? Can you post that?

**Comment by Vdevv** [comment]
Tried to reproduce that today with no luck it seems working correctly now although the --sa is not working tried -sa and it works.
