### ISSUE TITLE
DUDE your system is down

### ISSUE THREAD

**Issue by philosofonusus** [epsylon/ufonet#153]
Your site is down

**Comment by philosofonusus** [comment]
ufonet is down

**Comment by epsylon** [comment]
Is UP again! ;-)
Btw, try to email me for this kind of reports because that machine is not only serving ufonet stuff and can be related with other projects...
Thanks for your report!

**Comment by trollmad3** [comment]
@philosofonusus Site was down for some brief minutes but it is now back.

**Comment by epsylon** [comment]
https://github.com/epsylon/ufonet/issues/154

**Comment by mehedimec** [comment]
seems the site is down.

**Comment by epsylon** [comment]
@mehedimec roger...btw, try also to review for other reasons, such as: firewall, ISP blocking, etc.. Not always is an issue related with server side...
See also: https://github.com/epsylon/ufonet/issues/169
On the other hand, UFONet can share "zombies" using P2P methodologies. So, if you have problems to reach "Turina Server", you always can try to serve content by yourself. Or even, access to the "blackholes" of other members of the Community,,,

**Comment by Aholicknight** [comment]
@mehedimec were you using a VPN when you were connecting to the website?

**Comment by mehedimec** [comment]
@Aholicknight I am not using any VPN but I have tried it from an academic network and there may be firewall issue as mentioned in #169 
I am using the command 
" ./ufonet --download-zombies " and got the error: 
[AI] Trying [Blackhole]: 176.28.23.46
[AI] [Control] [Blackhole] Reply: [VORTEX FAILED!]
------------
[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] -> [Exiting!]

**Comment by Aholicknight** [comment]
@mehedimec Use a VPN or tor then post the results.
