### ISSUE TITLE
Zombies not downloading

### ISSUE THREAD

**Issue by blockyTj995** [epsylon/ufonet#154]
I Got UFONet last night and i tried to download some zombies.
Then I got an error Saying  "AI] [Control] [Blackhole] Reply: [VORTEX FAILED!]

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] -> [Exiting!]"

Im using vbox with security parrot.

**Comment by trollmad3** [comment]
what version are you running and what does it say when you add `-v` to it?

**Comment by epsylon** [comment]
-> VORTEX FAILED!]
This is because server has been down for some hours. We were experiencig a lot of visits ;-)
Try it again..

**Comment by phhonepyaesonemaung** [comment]
it is happening again
