### ISSUE TITLE
low power

### ISSUE THREAD

**Issue by mbxex** [epsylon/ufonet#158]
How can I increase the power of packets sent?
/path/big.jpg as related to this? where should I put this folder (in a jpg folder with a weight of 100mb)

**Comment by epsylon** [comment]
Hi,
@mbxex if you are using latest code, you can try: ./ufonet --examples to have an idea of some different attacks and try to manage those values to increase your power (for example, using more threads)..

> /path/big.jpg as related to this? 

Isn't it. This is used to place your attack on a specific point, for example, a video, a flash movie, etc.. All your zombies will reload it.
