### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Hrenaz** [epsylon/ufonet#159]
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/data/data/com.termux/files/home/ufonet/core/main.py", line 146
    print "                                             0===============================================0"
                                                                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("                                             0===============================================0")?
(I use Termux)

**Comment by trollmad3** [comment]
As I am aware, UFONET does not work on termux due to the limitations.

**Comment by Hrenaz** [comment]
Thank you very much

**Comment by trollmad3** [comment]
@Hrenaz Close this issue if you got the answer you were looking for.

**Comment by XaviTorello** [comment]
@Hrenaz which version of Python are you using? It looks like you're using python3, maybe try to execute it over python2.7 helps you

**Comment by trollmad3** [comment]
@Hrenaz Did you watch this video: [https://www.youtube.com/watch?v=2XKgqmQDww8](https://www.youtube.com/watch?v=2XKgqmQDww8)
