### ISSUE TITLE
Compatible with windows?

### ISSUE THREAD

**Issue by Beyarz** [epsylon/ufonet#16]
Hi, How do you run Ufonet on windows 10?

I've tried to run Ufonet on windows 10 but I can't get it to work, I've installed every single required software but I still get errors like:

\ufonet\core\main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
ImportError: No module named requests

It would be wonderful If Ufonet worked on windows.

**Comment by epsylon** [comment]
Hi,
Try to install "requests" module as follow (Windows):
stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by Beyarz** [comment]
Installed all the require modules (Requests module & PyCurl module), It's fully working now!
