### ISSUE TITLE
error in the terminal when i try to get ufonet zombies from comunity

### ISSUE THREAD

**Issue by Arcai666333999** [epsylon/ufonet#161]
When I try to download botnet, I get this mistake,
how can resolve it?
![Schermata a 2019-05-28 18-54-09](https://user-images.githubusercontent.com/24968126/58488720-2479f680-816a-11e9-882e-19a080e73abd.png)

**Comment by Nekai** [comment]
I haven't checked if it's been updated but I had to manually fix some of
the code to host and download zombies

**Comment by epsylon** [comment]
@Arcai666333999 this is not an error. The client is just telling you that the server isn't temporally working correctly. This can be for many different reasons, for example, that the server is "out of service", or your IP has been firewelled, etc.. Btw, try it again now, because it looks up.
