### ISSUE TITLE
DoS/DDoS not starting [Potential GeoIP issue]

### ISSUE THREAD

**Issue by TeamMurf** [epsylon/ufonet#162]
**Hi there, I'd like to take a moment to thank you for continuing to update and support UFONet, please don't stop doing it. Happy 6 years!**

I'm currently having an issue with when I start an attack, nothing seems to occur, other then it being stuck on the host being online with a response 200-OK.

![Screenshot_23](https://user-images.githubusercontent.com/34534416/58519436-71f56400-8168-11e9-81fe-e6891d5c2f0f.png)

I can wait a long time for nothing to occur, if I try with the map active, this happens:

![Screenshot_22](https://user-images.githubusercontent.com/34534416/58519453-83d70700-8168-11e9-97cc-5c8171db0186.png)

![Screenshot_21](https://user-images.githubusercontent.com/34534416/58519456-86396100-8168-11e9-844f-bd6ccfd4873e.png)

I waited for nothing different to appear, furthermore, I have a feeling it has to do with the GeoIP not working, as I may have the wrong version or it can't find it, maybe.

It says "look for consoles for errors" , there are no errors, just that 200-OK message.

Lastly, I can confirm that I have GeoIP installed, and I have tried other solutions proposed. Examples:

sudo pip install geoip
sudo pip install pygeoip

Neither of these worked, sadly, so! I have to come to you for help! :)

Running Latest Kali Linux in Virtualbox machine, wired internet connection (seems to cause an issue)

--

EDIT (1) : I switched virtualbox from Bridged Adapter => NAT and this seemed to allow proper DOS/DDOS attacks to commence without issue?

The thing is, nothing seems to happen to the website I'm attacking, do consider that I can take it down by myself with HOIC/LOIC but can't take it down using 1000 zombies.. how can I guarantee something is working?

Map is also still not appearing with anything, I think maybe the GeoIP my kali has is too new or isn't compatiable with ufonet.. what can I do from here?

**Comment by trollmad3** [comment]
Could you add `-v` to the attack and post the results here? Thanks.

**Comment by TeamMurf** [comment]
> Could you add `-v` to the attack and post the results here? Thanks.

I edited my post with some things I figured out.

I added -v to the attack and it gave some information that you would normally expect from an attack.

"Attacking from ..."

"reply http code 200" 

"x-rpcs attacking.." etc etc.

Seems fine there, although read my updated post with new 'issue' :)

**Comment by epsylon** [comment]
So @TeamMurf, your problem is that the zombies are not loaded on the map?. Which python version are using?. Which geoip version is installed on it?...
> t I can take it down by myself with HOIC/LOIC but can't take it down using 1000 zombies.
Are these zombies working correctly?. Are you sure that other issues in your network are correctly working?

**Comment by TeamMurf** [comment]
> So @TeamMurf, your problem is that the zombies are not loaded on the map?. Which python version are using?. Which geoip version is installed on it?...
> 
> > t I can take it down by myself with HOIC/LOIC but can't take it down using 1000 zombies.
> > Are these zombies working correctly?. Are you sure that other issues in your network are correctly working?

Correct. It says 0/1000 blah blah zombies, and never loads. And when the attack starts, it doesn't seem to actually work or "attack" anything. When the attack finishes it purges all zombies from my list :(

Python version: 2.7.16
GeoIP version: 1.3.2
PyGeoIP version: 0.3.2

The internet is working fine, but again, through virtualbox it's a wired connection, not wan. Not sure if this causes problems. 

![Screenshot_24](https://user-images.githubusercontent.com/34534416/58589923-dc191200-8217-11e9-8ccf-8fd29ff683a2.png)

**Comment by epsylon** [comment]
I see @TeamMurf
>  When the attack finishes it purges all zombies from my list :(
That means that something is wrong with your network. It is so strange that you cannot reach any zombie. Are you using TOR or any other kind of proxy?. You can connect to internal WAN/LAN but, can you reach public IP's?[..]

**Comment by trollmad3** [comment]
@epsylon exactly what I was going to say. I'm starting to think that his router is _probably_ blocking website's and known IP's that are malicious or he's just firewalled.

**Comment by TeamMurf** [comment]
> > That means that something is wrong with your network. It is so strange that you cannot reach any zombie. Are you using TOR or any other kind of proxy?. You can connect to internal WAN/LAN but, can you reach public IP's?[..]

@epsylon I am not using any Proxy / TOR, just Kali Linux right out of the box with no changes other then of course cloning this github, running the setup.. 

It's just odd because I CAN do attacks and sometimes they work fine, and other times they don't work. But of course they never seem to appear on the map geoip thing, and, maybe it could be firewall? I'm not sure.

Also, what do you mean by can I reach public IPs? Sorry, just some clarification.

**Comment by trollmad3** [comment]
@TeamMurf 
| what do you mean by can I reach public IPs Sorry, just want some clarification 
Is your router, firewall, or service provider blocking the IPs? Go on this website https://www.blocked.org.uk/check to test if it's being blocked.

**Comment by TeamMurf** [comment]
> Is your router, firewall, or service provider blocking the IPs? Go on this website https://www.blocked.org.uk/check to test if it's being blocked.

I did some tests there and on connecting and all that, it does seem to be fine / nothing blocked. 

It's odd, because again attacks do work sometimes and sometimes not, but the actual GeoIP does not seem to work. 

I reviewed my Routers firewall, disabled it, tried it, nothing changed. Turned firewall back on, same result. No zombies appear :(

**Comment by epsylon** [comment]
You can check also for your Public IP by spelling:
./ufonet --network

**Comment by TeamMurf** [comment]
> You can check also for your Public IP by spelling:
> ./ufonet --network

/ufonet --network does seem to pull the proper info up.

It however fails to put the right info up if I try to 'attack me' .. which I don't know if that has a problem to do with anything. :/

**Comment by epsylon** [comment]
--attack-me option requires special NAT configuration. You need to port-forwarding at your router (on a homelab scenario) to allow your zombies to "attack" your Public IP. Try to review that.
