### ISSUE TITLE
Geoip error in Windows

### ISSUE THREAD

**Issue by DDDuccie** [epsylon/ufonet#163]
i keep getting this error, i tried everything i could think of (Installing it from the website, doesn't work, redownloading Ufonet, doesn't work, Reinstalling it, doesn't work, rebuilding it, doesn't work.)
Woops forgot the image, here
![Screenshot_292](https://user-images.githubusercontent.com/41547586/58728928-497b9d00-83e8-11e9-97b2-0bf7db539c21.png)

**Comment by epsylon** [comment]
Hi @DDDuccie
Something wrong at your python environment...
> C:\Python27\lib\distutils\dis.py:267: .... 'bugtrack_url'

**Comment by epsylon** [comment]
1) https://stackoverflow.com/questions/29441711/error-unknown-distribution-option-bugtrack-url
2) https://github.com/andrix/python-snappy/issues/48
