### ISSUE TITLE
Feature Request: IP gather/collector option

### ISSUE THREAD

**Issue by kimocoder** [epsylon/ufonet#164]
Would have been nice feature to add, save IP's to a db or a file, for simplier usages with other tools.

**Comment by trollmad3** [comment]
I would like this.

**Comment by epsylon** [comment]
Hi @kimocoder
Which IP's do you require for your request?.
I don't understand, because you have at /botnet/ folder, some files that contains domains/IPs of "zombies" (included "aliens", "droids"). You can use them with other tool, easily,

**Comment by kimocoder** [comment]
Ah, I'll take a look at it. Thanks for your work anyhow :1st_place_medal:
