### ISSUE TITLE
Commands launch auto update

### ISSUE THREAD

**Issue by oda-alexandre** [epsylon/ufonet#165]
Hello psy,

I come out my [dockerfile ufonet](https://hub.docker.com/r/alexandreoda/ufonet) to put a little update. (https://hub.docker.com/r/alexandreoda/ufonet)
Here is the part that I wish to improve to have a container has day with each startup

`sudo service tor start && sudo service privoxy start && ./ufonet --check-tor --proxy="http://127.0.0.1:8118" && ./ufonet --gui`

To add the update of the dork & zombies I have to add what to order ?

thank you again for your work.

**Comment by epsylon** [comment]
hey @oda-alexandre,
Firstly, nice work. Yes, for that update you should add:
./ufonet --download-zombies
This will update zombies, but also content at GUI such as: News, Missions, etc..

**Comment by oda-alexandre** [comment]
> hey @oda-alexandre,
> Firstly, nice work. Yes, for that update you should add:
> ./ufonet --download-zombies
> This will update zombies, but also content at GUI such as: News, Missions, etc..

thank you

**Comment by epsylon** [comment]
I am thinking @oda-alexandre that maybe you need also to add: --force-yes ("set 'YES' to all questions") to your spelling so your command will bypass some questions related to updating processes...

**Comment by epsylon** [comment]
So, finally:
sudo service tor start && sudo service privoxy start && ./ufonet --check-tor --proxy="http://127.0.0.1:8118" && ./ufonet --gui && ./ufonet --download-zombies --force-yes

**Comment by oda-alexandre** [comment]
and you also make coffee? lol, thank you very much
