### ISSUE TITLE
How to configure tor for ufonet

### ISSUE THREAD

**Issue by ToxicKill97** [epsylon/ufonet#166]
How to configure tor for ufonet and im using kali linux on windows. How to set it up? @epsylon

**Comment by epsylon** [comment]
Hi @ToxicKill97
Well, this config can be used for UFOnet, but also for other tools. I have tried to explain it on a video-example at this link: https://03c8.net/wg/1.html
You need TOR, but also a transparent proxy such as: polipo, privoxy, etc..
