### ISSUE TITLE
Error [Error] [AI] Something wrong searching using: bing

### ISSUE THREAD

**Issue by Assaslay1998** [epsylon/ufonet#167]
I have a error when i use this:  ./ufonet --sd "botnet/dorks.txt" --sa --sn 5 -v

The error: [Error] [AI] Something wrong searching using: bing

**Comment by epsylon** [comment]
Hi,
Which version of UFONet are you trying?. Are you using Tor?. Is it correctly working?..
Here, using a copy from scratch, Bing search engines is working like a charm (really fast). Remember that sometimes, you reach max requests allowed, or your geolocation has restrictions, etc..
Btw, try this spelling for your tests:

./ufonet -s "proxy.php?url=" --se "bing" -v

[....]

[AI] Searching for zombies using: bing
--------------------------------------------
Query used: https://www.bing.com/search?q=instreamset%3A%28url%29%3A%22proxy.php%3Furl%3D%22&first=0

+Victim found: https://xxx.xxx.xx.edu/proxy.php?urlproxy.php?url=
------------
+Victim found: http://198.23.xxx.xxx/plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?urlproxy.php?urlurlproxy.php?url/RK/RKproxy.php?url=

--------------------------------------------
- Victims found: 9 
    - Restored: 0
    - Dorked: 9

**Comment by Assaslay1998** [comment]
I use the Version 1.3 and i dont use Tor. I try to load ufonet on a Debian 9 vps Server

**Comment by epsylon** [comment]
Try this:
./ufonet -s "proxy.php?url=" --se "bing" -v

**Comment by Assaslay1998** [comment]
but that's not much

**Comment by epsylon** [comment]
Well, but it shows you a lot of stuff. For example, that the regular expressions that we are using has a "hack" for that search engine are still working. Also that doesn't look a problem with code, etc..

You should try now to repeat (debug) the process of your error and see on details on it. For example, if Bing is always stoping to work at same point. Of if there are some "zombies" that are causing problems, etc..

**Comment by Assaslay1998** [comment]
Should I then show the error here as a picture?

**Comment by Assaslay1998** [comment]
how can I get more rpc's

**Comment by Aholicknight** [comment]
@Assaslay1998 You asked to fix that problem, not get more RPC's. Is the issue fixed?
