### ISSUE TITLE
can't run ./ufonet

### ISSUE THREAD

**Issue by guude3** [epsylon/ufonet#168]
If i'm going to make a post, why not kill 2 birds with 1 stone,
Issue #1 Kali Linux isnt replying to any commands but instead with "-bash: (command): command not found" or "-bash: (command):  No such file or directory" 
I tried git clone in kali linux but only got the error of "-bash: git: command not found" If you know how to help, please do so.
Issue #2 I'm using git bash because kali linux is being a bitch, but besides form that, I git cloned ufonet and did everything normally but when i tried "./ufonet" it didn't work and I got the error

 Error importing: pycurl lib.

 To install it on Debian based systems:

 $ 'sudo apt-get install python-pycurl' or 'pip install pycurl'

Any help?

**Comment by Aholicknight** [comment]
Issue 1: Are you running the commands as sudo?

**Comment by guude3** [comment]
> Issue 1: Are you running the commands as sudo?

I'm new to coding and programming so i'm not used to all this setup shit like sudo. I just downloaded and followed a bunch of tutorials. I'm not sure what sudo is also.

**Comment by Aholicknight** [comment]
Read http://pycurl.io/docs/7.19.5.1/install.html

**Comment by guude3** [comment]
> Read http://pycurl.io/docs/7.19.5.1/install.html

so i fucked up a bit and my python 2.7.10 wasn't installing and since i've been working on this for god knows how long, i got fed up and i just deleted all the python files (including the python27 file) and i can't seem to get it back no matter what i do.
UFOnet says it needs >2.7.9 python and i tried installing the latest version of python (3.7.3) and i never recieved the python27 file n shit. hoping you might be able to help.

**Comment by guude3** [comment]
> Read http://pycurl.io/docs/7.19.5.1/install.html

I'm back where i started 4 hours ago. I keep getting this error message when doing
 'sudo apt-get install python-pycurl python-geoip python-whois python-crypto python-request'

'Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-request'
Thing is, i have python request downloaded on my pc (3 times actually) and i went through the ufonet link to get it and it's still not working.

**Comment by guude3** [comment]
> Read http://pycurl.io/docs/7.19.5.1/install.html

So I'm back at square 1. 
My pycurl isn't working. I've installed it and for reassurance i git cloned it. 
I'm still getting the error message of my original post.

**Comment by Viz38** [comment]
I had the same problem with git bash. I tried it with kali on  vm and it worked fine for me.

**Comment by guude3** [comment]
> I had the same problem with git bash. I tried it with kali on vm and it worked fine for me.

like i said, im new to this so can you link me to the kali linux (and whatever vm is?)

**Comment by Viz38** [comment]
> > I had the same problem with git bash. I tried it with kali on vm and it worked fine for me.
> 
> So i downloaded Kali Linux VMware 64-Bit 7z and i dont know how to set it up.....

https://www.youtube.com/watch?v=BCCiEZ9VJ2g
