### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by rezasri** [epsylon/ufonet#17]
ufonet works fine for me but when i lunch my DDos attack it will give me an error and i can't lunch my attack correctly , please help me.

thanks

RezaSri

**Comment by Pr0xy671** [comment]
Post the errors you get. That helps a lot. Describing what happens, in more detail, also help.

**Comment by rezasri** [comment]
this is a screenshot of step before attack gets start:
https://i.imgsafe.org/285f7869bb.jpeg
and this is a screenshot of error which its gives me while i try to attack
https://i.imgsafe.org/286c9495d0.jpeg
.....................................................................................................
sorry for bad english

thanks a lot for your help

RezaSri

**Comment by epsylon** [comment]
**If you have this problem, probably you need to update your 'zombies' list.** 
this issue has been described at Ufonet FAQ ("Error: can't start new thread"):
https://ufonet.03c8.net/FAQ.html
Please check it before to report.

**Comment by rezasri** [comment]
Thanks for your help

Please tell me:
 how to update my zombie list?
And
How reduce my zombies list to those that really works?
..................................................
Thanks a lot for your help

RezaSri

**Comment by epsylon** [comment]
Zombies are links on text files at "botnet" folder... you can manipulate this manually to your choice.
also you can use -t option to "test" if they are valid.

PD: Ufonet community is a bit chaotic on respecting some rules such as for example, create threads on "issues" to concrete themes than can help to other users. Also repeating again and again same questions. Maybe is need mor information.
Btw, please, don't ask me stuff here like on a personal chat system. Try to contribute to others also creating nice supporting tickets.

Thanks for your questions.
