### ISSUE TITLE
Multiple operations return "Something wrong"

### ISSUE THREAD

**Issue by Deathtanium** [epsylon/ufonet#170]
When I run some operations from the ufonet GUI, two of them return the "something wrong [action]" message. These actions are: 

- Testing the botnet on myself (something wrong getting public IP address; note: I'm not using TOR)
- Testing the botnet with the ALL button from the botnet testing section (Something wrong testing ALL botnet status)

**Comment by Aholicknight** [comment]
Could you post the exact commands you used?

**Comment by Deathtanium** [comment]
I used the GUI buttons from the latest version.

**Comment by Aholicknight** [comment]
@Deathtanium Try to repeat the same process again with the commands. It will be easier to help with the commands that you used.

**Comment by Aholicknight** [comment]
Or you can take a screenshot of the output from the GUI.

**Comment by epsylon** [comment]
Hi @Deathtanium 

`Testing the botnet on myself (something wrong getting public IP address; note: I'm not using TOR)`

This can be related with your NAT configuration. Are you using a VM?. Is your router (exit node) supporting correctly port-forwarding?..etc...

As @Aholicknight has told you, it is much better for help you to us if you can provide more info (screenshots, logs, shell outputs,..) about the issue.
