### ISSUE TITLE
I can't attack

### ISSUE THREAD

**Issue by Akenixd** [epsylon/ufonet#171]
Hi, i can't attack with ufonet
http://prntscr.com/ok2jnj
i'm using python 2.7.13

**Comment by Aholicknight** [comment]
Can you do this attack again with `-v` (verbose) enabled and post the results? Thanks.

**Comment by epsylon** [comment]
@Akenixd ??... this capture is showing you that you are correctly attacking to a target and:
 1- some zombies are failing
 2- your target is still up
