### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by JoeTheNoob12** [epsylon/ufonet#173]
So im very new to this i dowloaded python 2.7.9 and all the extention things and ufo net what do i do now im so lost? if you can help add me on discord JoeFxckedU#8983 thanks

**Comment by Aholicknight** [comment]
We can only provide you with help on GitHub such as bugs and other problems with the program. If you need help _using_ the program please goto forums or look at youtube videos to help.

**Comment by epsylon** [comment]
Thanks @Aholicknight
@JoeTheNoob12 if you can read English or Spanish, you should try start reading the manual. You have a /docs folder and some interesting texts in which are examples for installing it and so on. Also you have it, online: https://ufonet.03c8.net/#installation
On the other hand, you have really nice videos at some other platforms and in many different languages (and with more or less crazy music on the background, hehe). So you can check it also this way...
