### ISSUE TITLE
Something wrong searching using: any browser

### ISSUE THREAD

**Issue by Hauntex** [epsylon/ufonet#174]
Having an issue:
When searching I consistently run into the issue where it says that something wrong searching, which results in the entire thing being scrapped and me incapable of doing anything related to searching.

**Comment by Stellar404** [comment]
This seems to be related to the Bing search engine. If you add -v (verbose) to your command you will see where it is failing.
@epsylon Is there any way to auto-search, excluding Bing?

**Comment by epsylon** [comment]
Hi @Hauntex,
Bing is working from here... Btw, @Stellar404 has reason when is saying you that it seems something related with the search engine. 
This "non-privacy/non-freesearching" related search engines are continuously trying to block some requests by introducing some limitors. This is done, for example, to provide some content to ones but different to others depending of the origin of the requests (so, firstly, check/remember that if you are using TOR). As you can understand, this messures are not directly related with security issues and more related to censorship, etc..
Also, Bing (Microsoft Inc.) has a time-request contrameasure, that only allows to external APIs to make a few number of requests by minute, so, sometimes requests sent by UFONet aren't arriving propertly to destiny. 
My suggestion is that you should try: -v (verbose, as @Stellar404 told you) but also to introduce a bit of delay (--delay). 
@Stellar404 Nope. But it looks a good idea to be introduced as a new option for the tool. Thanks!
