### ISSUE TITLE
Cant download Zombies.

### ISSUE THREAD

**Issue by IMAFRUITDE** [epsylon/ufonet#175]
Always the same error message : 
[AI] [Control] [Blackhole] Reply: [VORTEX FAILED!]
------------
[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] -> [Exiting!]

**Comment by Aholicknight** [comment]
Can you please do the same command again but with `-v` (verbose) and post the results here? Thanks.

**Comment by IMAFRUITDE** [comment]
> Can you please do the same command again but with `-v` (verbose) and post the results here? Thanks.

I had use the gui mode :/ So i try only with command?

**Comment by Aholicknight** [comment]
@IMAFRUITDE Do the same thing you did with the GUI into commands or add verbose to the GUI. Then take a screenshot or copy the output and put it here.

**Comment by epsylon** [comment]
Sometimes "vortex" (Community Server) can fail because of multiple reason, mostly related with server side configuration, as for example, firewall, network requests, etc.. Try it again after some time.
