### ISSUE TITLE
fix print-ing in the main.py

### ISSUE THREAD

**Issue by 4ntil0l** [epsylon/ufonet#176]
as i know the code runs in python2 
i got a fresh arch install installed needed tools and stuff and first thing i wanted to do was use the gui thingy but when i try to visit ``http://127.0.0.1:9999/blackholes``  i get this dumb thingy 
``  File "/home/lol/Desktop/scripts/scripts/ufonet/core/main.py", line 192
    print "\n[AI] Making a unique drawing using 'Turtle' (Feurzig & Papert - 1966) -> [OK!]\n"
``
just wtf isnt this shit running on python2 
why am i getting this?

**Comment by epsylon** [comment]
python2.7.x... btw, you don't need to enter any URL manually...

**Comment by 4ntil0l** [comment]
ok i rewrite the whole mine .
