### ISSUE TITLE
stuck in GeoIP data download in progress...  

### ISSUE THREAD

**Issue by CoolCyclo** [epsylon/ufonet#177]
I am using mac os to use ufonet, but when I open map it doesn't show any bots location and in the log it says "GeoIP data download in progress..." I tried in Kali Linux too, but that doesn't work. I have waited 2-3 hours and still nothing, can someone please help me?I have geoip installed and i have python3
![Screen Shot 2019-10-29 at 19 32 38](https://user-images.githubusercontent.com/54942798/67788170-e2d7d980-fa82-11e9-837a-0a2c64afeee6.png)

**Comment by epsylon** [comment]
Hi @CoolCyclo 

The visual geo-representation of zombies on the map is made thanks to a couple of variables. 

Check that they are correct on your system:

1) GeoIP library: You should have correctly installed **python-geoip2**. Check this for more info about installation and requirements: https://ufonet.03c8.net/#installation (you can also try to auto-install all required libs via setup.py)

2) Map Databases: When the process of downloading maps is finished, you will have to relaunch UFONet to make it work. In addition, you should have a folder called "Maps", at the root of the program, with data. Check that it exists.

**Comment by epsylon** [comment]
Ok. These files are empty. They are used to download maps. I think that you had a network connection error, so cannot download the propertly

Download again map databases. You can borrow them, directly, from the following url:
https://turina.space/bordercheck/maps.tar.gz

After that, uncompress it and move content to a folder named "Maps" at the root path of the tool. 

Finally, check that you have next file sizes. 
 - GeoIPASNum.dat : ~3.8M
 - GeoLiteCity. ~19.3M

Relaunch GUI: ./ufonet --gui

**Comment by CoolCyclo** [comment]
OK,Fixed it
