### ISSUE TITLE
Problems attacking

### ISSUE THREAD

**Issue by Krypt1kk** [epsylon/ufonet#180]
sort of a newbie to Ufonet, and idk if you've gotten this one yet but there seems to be a problem with connection. check the pic
![github](https://user-images.githubusercontent.com/57334946/68096312-eeaa0e00-fe7d-11e9-912d-713cb1e15ccd.png)

**Comment by Aholicknight** [comment]
Could you post the command you used? If you did not already, please add `-v` to the same command and post the results here.

**Comment by Krypt1kk** [comment]
i used ./ufonet -a http://example -r{}, after adding -v im getting a reply from the bots im assuming this worked, thanks!

**Comment by epsylon** [comment]
@Krypt1kk It looks like a temporal connectivity problem from your station. Or, that your target was down! ;-)
