### ISSUE TITLE
 Unable to download list of [Zombies] from this [Blackhole]

### ISSUE THREAD

**Issue by TheYellinFrs** [epsylon/ufonet#182]
[AI] Trying [Blackhole]: 176.28.23.46

[AI] [Control] [Blackhole] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] -> [Exiting!]

**Comment by Aholicknight** [comment]
Could you post the command that you used to get the blackhole? With `-v`

**Comment by epsylon** [comment]
This is related to server-side (as I have explained before in some other similar "issues"). Maybe you are firewalled. Try it again, after sometime..

**Comment by azamet90** [comment]
> This is related to server-side (as I have explained before in some other similar "issues"). Maybe you are firewalled. Try it again, after sometime..

i dont have firewall but same thing is happening what about that?
