### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by 130805** [epsylon/ufonet#183]
When i typ in ./ufonet --gui it says

Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/*****/ufonet/core/main.py", line 1128, in run
    self.create_web_interface()
  File "/home/****/ufonet/core/main.py", line 2101, in create_web_interface
    from webgui import ClientThread
  File "/home/****/ufonet/core/webgui.py", line 13, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

and there is nothing popping up i hope someone has a fix for this

**Comment by epsylon** [comment]
Hi @130805
Please, next time before come here with an issue, try to check the Internet for solutions.
https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher
Try removing both crypto and pycrypto with pip:
_sudo pip uninstall crypto
sudo pip uninstall pycrypto_
And reinstalling pycrypto:
**sudo pip install pycrypto**

**Comment by philly-vr** [comment]
still says no module, running from chromebook with everything need to be installed and updated in their proper states.

**Comment by epsylon** [comment]
try this: **python3 -m pip install pycrypto**
