### ISSUE TITLE
issue while running ufonet

### ISSUE THREAD

**Issue by incognito55** [epsylon/ufonet#185]
hey i have try to setup botnets in ufonet but while running this error is occurring [Error] [AI] Something wrong searching using: bing

**Comment by incognito55** [comment]
[Info] [AI] NOT any NEW victim(s) found for this query!

**Comment by Aholicknight** [comment]
Could you post `-v` on the same command  and post the results here?

**Comment by epsylon** [comment]
@incognito55 this is not an error. Is an [Info] message. This means mostly that the "dork" that you have provided for your searching, or because of some other related networking issues, is'n providing any results. Take a look when spelling a dork with: " ' "
