### ISSUE TITLE
Failed > Cannot Connect

### ISSUE THREAD

**Issue by rlxfilms** [epsylon/ufonet#186]
Hello,

Am a new user to UFONET. Having a few issues on actually attacking. Keep getting 'cannot connect' everytime time I run the script. 
Have read a few other posts with the same issue. I have Python2.7 and all the necessary plugins to run UFOnet. Using GUI

**Comment by epsylon** [comment]
Hi @rlxfilms,
That behavior can occur for several reasons. For example, that your connection has stopped working (do you use TOR?). Also that your target has a firewall / IDS / NIDS or even, that you have achieved that the service is down.
127/5000
You need to share more detailed information about your issue. Perhaps this guide for reporting can help you: https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
