### ISSUE TITLE
num_results

### ISSUE THREAD

**Issue by indigopsy** [epsylon/ufonet#19]
hi 
i tried to search a lot of results on bing and there is no difference between 
`./ufonet --sd 'botnet/dorks.txt' --sa --sn 20 --threads 20`

and 

`./ufonet --sd 'botnet/dorks.txt' --sa --sn 200000000000 --threads 20`

i allways get around 200 posible zombies
can you check your code and see where is error

**Comment by epsylon** [comment]
Well.. that means that you are reaching max results provided by search engine...
