### ISSUE TITLE
cannot connect to black hole plz help

### ISSUE THREAD

**Issue by ddosdawn** [epsylon/ufonet#190]
not abductions.txt.gz file in /var/www/ufonet/
[Error] not troops.txt.gz file in /var/www/ufonet/
[Error] not robots.txt.gz file in /var/www/ufonet/
[Error] not drones.txt.gz file in /var/www/ufonet/
[Error] write access denied for abductions file in /var/www/ufonet/
[Error] write access denied for troops file in /var/www/ufonet/
[Error] write access denied for robots file in /var/www/ufonet/
[Error] write access denied for drones file in /var/www/ufonet/

**Comment by Aholicknight** [comment]
Can you please do the same command with `-v` then post the results here?

**Comment by epsylon** [comment]
You haven't correct permissions to write: [Error] write access denied for...
