### ISSUE TITLE
gui mode works but not terminal mode

### ISSUE THREAD

**Issue by azamet90** [epsylon/ufonet#192]
on gui mode the zombies are working but if i try without gui the target is down it says ...

**Comment by epsylon** [comment]
hey @azamet90 are you looking for attention or what?. 

What kind of reports are you doing?. 

https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

https://github.com/epsylon/ufonet/issues/191

Do you think that UFONet has special behavior ONLY with your environment?.  Maybe you should look at that point..

Do you think that I am here to waste my time attending to general mental issues/inmature kids?.. or just want me to be here talking shit with/like a troll?..

**Comment by azamet90** [comment]
> hey @azamet90 are you looking for attention or what?.
> 
> What kind of reports are you doing?.
> 
> https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> #191
> 
> Do you think that UFONet has special behavior ONLY with your environment?. Maybe you should look at that point..
> 
> Do you think that I am here to waste my time attending to general mental issues/inmature kids?.. or just want me to be here talking shit with/like a troll?..

first of all i dont know how old you are but me 30 ...
thanks for giving this tool for free i understand but you are very rude boy and dont worry i will not post again just remove that tool is much better and easier then feeling angry to you  i think have a nice day

**Comment by epsylon** [comment]
@azamet90 perfect!.. if is failing so much as you said.. easy, don't use it... ciao!
