### ISSUE TITLE
[Error] [AI] Something wrong (auto)searching..

### ISSUE THREAD

**Issue by Dany-LF** [epsylon/ufonet#194]
When i type:
python2 ufonet --auto-search --sa

He search but at one moment:
[Error] [AI] Something front (auto)searching...

This is a problem in the script or this is in my side ?

**Comment by Aholicknight** [comment]
Can you do the same command and add `-v` to it then post it here? Thanks.

**Comment by Dany-LF** [comment]
> Can you do the same command and add `-v` to it then post it here? Thanks.

Yes wait

**Comment by Dany-LF** [comment]
> Can you do the same command and add `-v` to it then post it here? Thanks.

Yes wait

> Can you do the same command and add `-v` to it then post it here? Thanks.

Same, at one moment he say: [Error] [AI] Something wrong (auto)searching....

**Comment by Aholicknight** [comment]
@Dany-LF You did not do what I said. I want you to repeat the same command and put `-v` into it so I can fully see what the error is. Then, once you repeat the command with `-v` put it into here or upload it to https://www.pastebin.com then put the link here.

**Comment by Dany-LF** [comment]
Oh okay wait

**Comment by Dany-LF** [comment]
https://hastebin.com/ofohupaget.diff

**Comment by Aholicknight** [comment]
@Dany-LF Your paste has expired and that link does not work anymore. use pastebin.

**Comment by Dany-LF** [comment]
http://hast.tk/dany|ZlSPPz1rud

**Comment by Aholicknight** [comment]
@Dany-LF I keep telling you to use pastebin but sure, that URL works fine. What search engine are you using + are you using a VPN? Sometimes the search engines will temporary block the searches due to it thinking your a spam bot.

**Comment by Dany-LF** [comment]
Default in ufonet(bing) without vpn

**Comment by epsylon** [comment]
hey @Dany-LF... Bing is working, the problem is other. It looks like @Aholicknight said that is blocking you. Try to control number of results with --sn=NUM_RESULTS (Set max number of results for engine) and/or change your IP periodically..

**Comment by Dany-LF** [comment]
Okay i test this thank you

**Comment by Dany-LF** [comment]
Resolved

**Comment by epsylon** [comment]
I have added to the new release of code, that will be deployed soon (python3-ufonet_v1.4), the possibility to "exclude" some search engines when they are failing, as was suggested on this thread: https://github.com/epsylon/ufonet/issues/174
With this option and the [AI] discarding requests that do not arrive automatically, there are practically no errors in searches... by the moment, hehe...

**Comment by epsylon** [comment]
New code (v1.4) has been released: https://github.com/epsylon/ufonet/commit/46ad8efeb3e58af235fa1e02b1137d13aa632a37
