### ISSUE TITLE
Dead/Useless Tool

### ISSUE THREAD

**Issue by TNTBOMBOM** [epsylon/ufonet#195]
Python-GeoIP is corrupted (cant be installed) thus corrupting/hinder the installation of uf0. 

Tested on Kali.

**Comment by epsylon** [comment]
I know it... GeoIP (now: pygeoip-0.3.2) is again working at the new release (#UFONet v1.4) which is under development. Just stay tuned...

**Comment by TNTBOMBOM** [comment]
Alright! Thanks :)

**Comment by Aholicknight** [comment]
@TNTBOMBOM Please quit creating useless issues. This is meant to fix bugs and not complain how it was created. GitHub forks exist so you can create your own fork and make any edits you want without harming or editing the original code.

**Comment by epsylon** [comment]
UFONet v1.4 (with new geoip supported) has been released: https://github.com/epsylon/ufonet/commit/46ad8efeb3e58af235fa1e02b1137d13aa632a37
