### ISSUE TITLE
Python2.x is dead Migrate to Python3 

### ISSUE THREAD

**Issue by TNTBOMBOM** [epsylon/ufonet#196]
Since python 2.x is [deprecated ](https://www.python.org/doc/sunset-python-2/) refresh the code with python 3.x . 

Thx!

**Comment by epsylon** [comment]
UFONet is being ported to Python3.x.y... Also I have refactorized code for some functions (thinking on scalability and compatibility with previous remote streams messages). Code now is faster and much more clear (~13K lines). But also hard to build, remember, on me free time... Please. be patient..

**Comment by Aholicknight** [comment]
This is saying to get rid of half of the programs on the internet because its deprecated. There is a lot of old programs on the internet that people find useful.

**Comment by epsylon** [comment]
A new release (v1.4) of the tool with code correctly ported to Python3.x.y, has been commited: https://github.com/epsylon/ufonet/commit/46ad8efeb3e58af235fa1e02b1137d13aa632a37
