### ISSUE TITLE
Wishlist: Add UFONet to Debian/Kali/Parrot repository 

### ISSUE THREAD

**Issue by TNTBOMBOM** [epsylon/ufonet#197]
Its nice (if this tools still active) to have it uploaded to the repositories of penetration testings distros whether through uploading it to Debian (which most pentest distros based on) or add it to kali/parrot repos. 

ThX!

**Comment by epsylon** [comment]
Should be nice!..hehe...For that... I have reduced/changed some methods to download modules. For example, now maps (and databases) are provided with main package, so users don't need to auto-download it from remote server. This is better (even more secure) for this kind of distros. But, now package is a bit more size (~25Mb)...
