### ISSUE TITLE
[Error] [AI] Unable to upload list of [Zombies] to this [Blackhole] -> [Exiting!]

### ISSUE THREAD

**Issue by Muckls** [epsylon/ufonet#198]
every time I try to download zombies form Blackhole it gets me this Error
[Error] [AI] Unable to upload list of [Zombies] to this [Blackhole] -> [Exiting!]
I tried this in many different versions,it still doesnt seem to work
Hope for your help soon
Blackhole IP:176.28.23.46

**Comment by Muckls** [comment]
pastebin link is here :https://pastebin.com/DycNGbHv

**Comment by epsylon** [comment]
@Muckls the "Vortex uplink" is working... maybe you have been firewalled. Wait some time an try it again.

**Comment by samsap1oI** [comment]
[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [server]
-------------------------------------------------------------------------------------
Hello! Help please :)
I tried with vpn, without vpn, with using tor, without using tor, all times I got this error, can you help me? Or just tell  is the ufonet still working today? I use kali linux, mb you can recommend a linux distribution which I should use?

**Comment by epsylon** [comment]
@samsep1oI -> https://github.com/epsylon/ufonet/issues/333#issuecomment-904537970
