### ISSUE TITLE
sudo python3 setup.py install ERROR

### ISSUE THREAD

**Issue by thedarkknight197** [epsylon/ufonet#199]
Warning: 'classifiers' should be a list, got type 'tuple'
warning: no files found matching 'ChangeLog'
py_GeoIP.c:23:10: fatal error: GeoIP.h: File o directory non esistente
   23 | #include "GeoIP.h"
      |          ^~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Aholicknight** [comment]
For Python 2.x use:

`sudo apt-get install python-dev`
For Python 2.7 use:

`sudo apt-get install libffi-dev`
For Python 3.x use:

`sudo apt-get install python3-dev`
For Python 3.4 use:

`sudo apt-get install python3.4-dev`
For Python 3.7 use:

`sudo apt-get install python3.7-dev`

This should fix the problem.

**Comment by epsylon** [comment]
@thedarkknight197 please, report if fixed and close if required.

**Comment by andreviewnxtv** [comment]
Hi, i've make the cmd above and allways getting:

Running GeoIP-1.3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-izmm_bnp/GeoIP-1.3.2/egg-dist-tmp-d1kkmonr
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
warning: no files found matching 'ChangeLog'
py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory
 #include "GeoIP.h"
          ^~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by epsylon** [comment]
@andreviewnxtv try to install GeoIP directly from pip. 

For example:

ventiska% python3 --version
Python 3.7.2

ventiska% python3.7 -m pip search GeoIP 
```

GeoIP (1.3.2)                            - MaxMind GeoIP Legacy Database - Python API
python-geoip (1.2)                       - Provides GeoIP functionality for Python.
  INSTALLED: 1.2 (latest)
```

ventiska% python3.7 -m pip install **python-geoip**

**Comment by epsylon** [comment]
To fix this error:

**sudo apt-get install python3-geoip libgeoip-dev libgeoip1**
