### ISSUE TITLE
Harden uf0net

### ISSUE THREAD

**Issue by TNTBOMBOM** [epsylon/ufonet#201]
uf0net gui application needs some love (nothing major/critical, thus worth adding it)

check out the report: 

https://anonfile.com/rbM1XaW1nb/uf0net_html

and this is for uf0net website: 

https://anonfile.com/78N5X3Wan9/uf0netwebsite_html

Note: These reports produced using [zaproxy](https://www.zaproxy.org/) webapp scanner.

**Comment by Aholicknight** [comment]
These are not critical and do not need to be fixed. If you scan any other site, you would find the same errors and they work fine.

**Comment by epsylon** [comment]
@TNTBOMBOM Looks like we've done a good job, it doesn't look so bad.
a) Remember that the GUI is launched in localhost.
b) Even the website is quite safe. Just a medium-level vulnerability related to: "X-Frame-Options Header" -> https://tools.ietf.org/html/rfc7034 (which isn't really required on standard)
So, many thanks for your work. Now we know that we are moving safely...
