### ISSUE TITLE
Error importing: pycurl lib

### ISSUE THREAD

**Issue by destiny-creates** [epsylon/ufonet#202]
when I keep trying to launch with python 3 it tells me: 
Error importing: pycurl lib.

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-pycurl'

I already installed python3 pycurl and uninstalled python 2 even and it still wont work

**Comment by epsylon** [comment]
It is not a code failure. It is a mistake of your environment. Thanks to port Python3, I am sure that these failures will be triggered.

Try the following:

```
ventiska% python --version
Python 3.7.2
ventiska% python3.7 -m pip search pycurl
pycurl (7.43.0.5)            - PycURL -- A Python Interface To The cURL library
  INSTALLED: 7.43.0.3
  LATEST:    7.43.0.5
```
If isn't installed, then:
**python3.7 -m pip install pycurl --user**

**Comment by destiny-creates** [comment]
it is installed, however it still says its not installed

reinstall python?

**Comment by epsylon** [comment]
Wait... What about **python3-pycurl**?. Do you have it?. 
How many Python3 versions are installed/working on your box?.

**Comment by destiny-creates** [comment]
I am using kali subsystem for windows. I have uninstalled python all versions completely and deleted all files of it, then reinstalled just python 3. then cloned your script, install python3-pycurl, then installed your script. all done from root and using sudo command. still tells me it not installed

**Comment by epsylon** [comment]
> then reinstalled just python 3.
There are many versions for Python3... and they have different libraries. So try to be concrete. When you try: python --version, what is the result?. Also, try to provide me shell outputs...not your words...
On the other hand.. Did you tried setup.pu (auto-install) script?. You can run it just like:
**sudo python3 setup.py install**

**Comment by destiny-creates** [comment]
I have tried using the setup.py script. and it installs everything needed. I personally am a python coder in python 3 but your script is too massive to try and fix lol. its python 3.7.5

**Comment by epsylon** [comment]
Probably yes.. you are too much for this _~13.000 lines of code_..."script"... We will try to fix it without you, then...

**Comment by epsylon** [comment]
> Also, try to provide me shell outputs...not your words...

blablabla...  your script is too massive ..blablabla...  its python 3.7.5

**Comment by rickgds80** [comment]
To fix the error during libcurl import error try this:
http://pycurl.io/docs/latest/install.html

**Comment by CyberFlo2005** [comment]
I too use the Kali Linux subsystem, and got the same error. During the installation, I saw a warning from pycurl. It said its not in PATH, and I couldn´t use it. I Ignored the waring, but now I think it caused this error. Sadly, I forgot the path, so I cant add it

**Comment by epsylon** [comment]
@CyberFlo2005 -> https://dannyda.com/2020/05/19/how-to-fix-kali-linux-2020-pip3-command-not-found/

**Comment by ipaidthebills** [comment]
Same issue here. Followed all the above plus everything I could google on the subject.
-----------------------------------------------------------------------------------------
root@kali:~/pentest/ufonet# python3 ./ufonet

Error importing: pycurl lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-pycurl'
----------------------------------------------------------------------------------------

 $ 'sudo apt-get install python3-pycurl' Doesn't work either. ufonet was working fine last time I used it.

**Comment by epsylon** [comment]
@ipaidthebills try it using pip -> sudo pip3 install pycurl (or python3 -m pip install pycurl --user)

**Comment by epsylon** [comment]
@kingstar788 try this -> https://github.com/epsylon/ufonet/issues/202#issuecomment-869509551
