### ISSUE TITLE
BotNet Generation Error

### ISSUE THREAD

**Issue by mcgregol** [epsylon/ufonet#203]
When I try to search for a botnet using the GUI, I get an error telling me that Python2 is no longer supported, but I ran the script using `python3 ufonet --gui`.  Then, when I go back to the terminal I get an error in line 22 as if it tried to run the script in Python2.  Does anyone know a fix for this?  Thanks.

**Comment by osgo1115** [comment]
Yeah, i have the same issue. I am trying to launch the zombies

**Comment by epsylon** [comment]
`This is related to your python environment configuration... Look at this video of the tool, working under Python3.7: https://ufonet.03c8.net/ufonet/ufonet-timewars.ogv`

BTW, I will try to add a patch soon: https://github.com/epsylon/ufonet/issues/204#issuecomment-586502773

**Comment by epsylon** [comment]
This should be fixed after this commit: https://github.com/epsylon/ufonet/commit/d19096004e99a7e9ab6f43ca584c3953828be9ac
+info: https://github.com/epsylon/ufonet/issues/204#issuecomment-586575447
