### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by osgo1115** [epsylon/ufonet#206]
When I try to launch ufonet, it says  "Try to run the tool with Python3.x.y (ex: python3 ufonet)" although it is installed python3. how can I launch ufonet? btw i tried "python3 ufonet" but i didnt work for me.

**Comment by osgo1115** [comment]
when i try to launch ufonet (python3 ufonet), it says "Error importing: pycurl lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-pycurl'

and I tried to install it by using the command but, if i try to launch ufonet, the same error appears.

**Comment by epsylon** [comment]
@osgo1115 let's check first some stuff:
0) HOW TO REPORT: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
1) Did you installed UFONet after latest commit? (https://github.com/epsylon/ufonet/commit/d19096004e99a7e9ab6f43ca584c3953828be9ac)
2) What version do you have on your box, after run:` python --version`
3) Run: `pip3 search pycurl`
```
pycurl (7.43.0.5)            - PycURL -- A Python Interface To The cURL  library
  INSTALLED: 7.43.0.3
  LATEST:    7.43.0.5
```
So, if it isn't installed, then run:` pip3 install pycurl --user` (or sudo pip3 install pycurl)
4) Did you run setup.py as root? (ex: sudo pip3 install setup.py)

**Comment by rickgds80** [comment]
To fix the error during libcurl import error try this:
http://pycurl.io/docs/latest/install.html

The error are in your python 3 installation, If you make a python code with the follow source: "import libcurl" and running in your python session, you Will receive the same error. Try to reinstall libcurl with this link instructions.
