### ISSUE TITLE
Use proxy list when finding bots via dorks?

### ISSUE THREAD

**Issue by Vepth** [epsylon/ufonet#207]
Hello epsylon,

Would you consider adding an option to use a proxy list when finding bots with dorks. This way when script shows `cannot connect to duck/yahoo/bing` to switch the proxy and continue the search? 

Also, it would be good when `[Info] [AI] NOT any NEW victim(s) found for this query!` so it changes proxy to find from other location?

Second good thing would be to add separate `Are 'they' alive? :-) (HEAD Check):` option so I can check "humans" that I have in `/botnet/humans.txt` to add them to the army?

Of course, my alternative is to do `python3 ufonet -s a?` and when it does it's job on one dork, I just continue with 'are they alive'.

Here is one error that I get on specific bots when they try to connect. used `-v` [pastebin](https://pastebin.com/uC93hr51)
Note: I did try with different VPNs and connections.

**Comment by epsylon** [comment]
Hi @Vepth 

1) Well, that kind of options can be easily realized nowadays with external tools or simple scripts. For example, you can use ProxyChains(or many others: Storm proxies, etc..), to "chain" a list and even rotate it. You can use paranoid solutions that make a different request with each IP, etc. And all of them, usually allow some transparency with the APIs of other tools, such as UFONet.

2) You can test that other 'zombies' just adding path to option: --test (ex: ufonet -t "botnet/humans.txt". And --no-head, to pass of this HEAD checks...

3) pastebin error: `UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 121: ordinal not in range(128)`

I see.. target has illegal characters: `Banverket �vergripande` on it. This can be easily bypass with just a try/exception at **/core/zombie.py#L48** in do_connect. I will do it.

Thanks!

**Comment by epsylon** [comment]
`3. pastebin error: UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 121: ordinal not in range(128)`

Should be fixed after this commit: https://github.com/epsylon/ufonet/commit/2276c68231cac794bb964376d722ceec9f57dd24

**Comment by Vepth** [comment]
Thanks @epsylon for your reply.

I've also tried to use TOR proxy for .onion sites, but 'proxy=127.0.0.1:8118/8080'  seems to be a SOCKS Tor proxy and doesn't want to connect with UFONet.

Is there a way to set up HTTP/S SOCKS Tor?

**Comment by epsylon** [comment]
Thanks to you @Vepth ;-)

I have advanced a bit more that url_encode parsing at this commit: https://github.com/epsylon/ufonet/commit/a3bb1ce86aab8c53551499f4f4266e26f8beade9

Sure there is. You can try a HTTP transparent proxy, such as Privoxy or polipo (etc..)

**Comment by Vepth** [comment]
I will try your new commit and will notify you, @epsylon .

For everyone who also wants to use UFONet on TOR network ( .onion ), you can use another GitHub script "TorGhost". Works great with this script!
