### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by Abdelrhaman2** [epsylon/ufonet#208]
Error Importing : install scapy lib
Proof : https://gyazo.com/4d4c91e1932f011733575c4dba518aa2

**Comment by Abdelrhaman2** [comment]
How to fix just download the older python 2 of that
https://gyazo.com/c0aa8700db736eb198a672e322c2443e
https://ufonet.03c8.net/

**Comment by epsylon** [comment]
**sudo apt-get install python3-scapy** (pip3 install scapy)

**Comment by Abdelrhaman2** [comment]
thanks

**Comment by blank29** [comment]
hello i'm having the same problem after linux kali update. and I already have the scapy lib
![scapy](https://user-images.githubusercontent.com/19747388/101662741-3c377800-3a8d-11eb-89e8-b023a811df64.png)
oh yes, I just installed Scamav yesterday.

**Comment by epsylon** [comment]
@blank29 if isn't working, try it from pip3...

ex: **pip3 install scapy-python3**

**Comment by ElmoRunsAgain** [comment]
Stil doesnt work

**Comment by epsylon** [comment]
@ElmoRunsAgain you mean, that you don't want to read on the Internet how to solve this...

1) Try to review which Python version are you using: **python3 --version**
_Python 3.7.3_

2) Fetch the lib using that version: **pip3.7 install scapy-python3**
_Requirement already satisfied: scapy-python3_
