### ISSUE TITLE
another ASCII error please help :D

### ISSUE THREAD

**Issue by trained** [epsylon/ufonet#210]
`root@devilsden:~/ufonet# python3 ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 13, in <module>
    app = UFONet()
  File "/root/ufonet/core/main.py", line 81, in __init__
    self.mothership_baptism() # generating static name/id for your mothership ;-)
  File "/root/ufonet/core/main.py", line 146, in mothership_baptism
    motherships = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
root@devilsden:~/ufonet#
`

**Comment by epsylon** [comment]
added anti-cheating for mothership naming -> https://github.com/epsylon/ufonet/commit/78541d040273ec4562417c034b4a0b1be7f112f5 ;-P

**Comment by trained** [comment]
can you delete this please im tryna clean up my github profile

**Comment by epsylon** [comment]
@trained this issue can help to others. Just confirm that you want to delete it. Thanks!
