### ISSUE TITLE
Hate being that guy but yet another error >.< 

### ISSUE THREAD

**Issue by trained** [epsylon/ufonet#211]
Am I doing something wrong? can you keep this ticket open while I get this figured out?

`
root@devilsden:~/ufonet# python3 ufonet
Traceback (most recent call last):
  File "ufonet", line 13, in <module>
    app = UFONet()
  File "/root/ufonet/core/main.py", line 81, in __init__
    self.mothership_baptism() # generating static name/id for your mothership ;-)
  File "/root/ufonet/core/main.py", line 146, in mothership_baptism
    motherships = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
root@devilsden:~/ufonet#

`

**Comment by trained** [comment]
since you last updated it im now getting this @epsylon 
`

root@devilsden:~/ufonet# python3 ufonet
===========================================================================

888     888 8888888888 .d88888b.  888b    888          888
888     888 888        d88PY888b  8888b   888          888
888     888 888       888     888 88888b  888          888
888     888 8888888   888     888 888Y88b 888  .d88b.  888888
888     888 888       888     888 888 Y88b888 d8P  Y8b 888
888     888 888       888     888 888  Y88888 88888888 888
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)}

===========================================================================
Traceback (most recent call last):
  File "ufonet", line 14, in <module>
    options = app.create_options()
  File "/root/ufonet/core/main.py", line 170, in create_options
    self.options = self.optionParser.get_options(args)
  File "/root/ufonet/core/options.py", line 290, in get_options
    print('\n  '+"\u25BC "+self.version+" \u25BC"+' {/Al13n_PerSYSt-[T4]Hunt1ng/}20++ '+"\u25BC"+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character '\u25bc' in position 3: ordinal not in range(128)
root@devilsden:~/ufonet#

`

**Comment by epsylon** [comment]
Hey @trained no problem...

It is normal to have this kind of encoding issues after migration to Python3...

1) Have you changed any motheship name at: core/txt/motherships.txt ?
2) Do you have any file name: shipname.txt (located at: core/txt/) ?
3) After this commit: https://github.com/epsylon/ufonet/commit/d57eb2380ec865dab814ee9ee5c7ee2fbf4d13f8. You should have a default name ID. So, should be fixed. Try it again, and close ticket if is working..

**Comment by trained** [comment]
I have not touched any sort of coding within the project, currently trying to install but seem to be having alot of troubles with ascii errors @epsylon

**Comment by epsylon** [comment]
Hi, @trained 
```
File "/root/ufonet/core/options.py", line 290, in get_options
print('\n '+"\u25BC "+self.version+" \u25BC"+' {/Al13n_PerSYSt-[T4]Hunt1ng/}20++ '+"\u25BC"+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character '\u25bc' in position 3: ordinal not in 
```
mmmhh... It looks that your environment isn't interpreting Unicode, propertly...

**Comment by trained** [comment]
I can't figure out for the life of my how to fix it.. been trying to get a proper install on centos, debian, and ubuntu, same errors everytime.

**Comment by epsylon** [comment]
`edit: yes i have a file named shipname.txt in core/txt/`
1) remove that file
2) try to update tool for apply laterst commits: python3 ufonet --update
3) re-launch

**Comment by trained** [comment]
Removed file, tried to update, got this error.

`
Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/root/ufonet/core/main.py", line 323, in run
    self.start_ship_engine()
  File "/root/ufonet/core/main.py", line 310, in start_ship_engine
    self.generate_exit_msg() # generate random exit msg
  File "/root/ufonet/core/main.py", line 216, in generate_exit_msg
    m = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1110: ordinal not in range(128)
`

**Comment by epsylon** [comment]
` been trying to get a proper install on centos, debian, and ubuntu` -> Sorry, but I cannot believe that... ;-)
Please, try to fill this form for next ticket: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by epsylon** [comment]
@trained this https://github.com/epsylon/ufonet/issues/211#issuecomment-591243270 should be fixed after: https://github.com/epsylon/ufonet/commit/f80cf83081f1495287fe74691a9138bb33a8fd14

Btw, Are you using a different encoding (UTF-8, ISOxx) for your environment?. Is it virtual?

**Comment by POSTiGA1** [comment]
I have the same problem sir, running under VPS CentOS 7
