### ISSUE TITLE
ImportError: No module named 'setuptools'

### ISSUE THREAD

**Issue by kattking16** [epsylon/ufonet#212]
┌─[✗]─[kattking16@parrot]─[~/H@x3r/network/idk/ufonet]
└──╼ $sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

**Comment by epsylon** [comment]
**sudo apt-get install python3-setuptools**

**Comment by kattking16** [comment]
same error even after i did that

**Comment by kattking16** [comment]
i have aslo tryed to reinstall it still dosent work :/

**Comment by epsylon** [comment]
hey @kattking16 
0 ) Don't waste my time with stuff that you can solve by yourself just with a single search on the Internet. Moreover, when it isn't related to UFONet code. Learn to manage your own box, buddy!
1) **pip3 install setuptools**

**Comment by kattking16** [comment]
but i have googled and tryed pip3 install setuptools i just cant get it to work i wuold not be creating a support ticket to waste your time i created one cuse i cant get it to work ;(

**Comment by kattking16** [comment]
i can use the old version that used just python and not python3 but in that version i cant use auto-search or search via the list so i cant relly find any bots

**Comment by kattking16** [comment]
i also hade the new vesrion working yeaster day but then after i canceld a search it stoped working so i tryed remove it and the download it agein but it still did not work

**Comment by Aholicknight** [comment]
@kattking16 He explained how to fix it and you keep wasting his time. Please search on google your same error and I guarantee that someone had the same problem & solution as you.

**Comment by kattking16** [comment]
> @kattking16 He explained how to fix it and you keep wasting his time. Please search on google your same error and I guarantee that someone had the same problem & solution as you.

I alredy googeld in many diffrent ways and i cant find someone with the same problem and hes not telling me how to fix it he tryed but it did not work and i am not wasting any ones time i have a issue that i wuold like to resolve but it clearly wont be happening so i will just stop wasting my time trying to fix this
