### ISSUE TITLE
How fix libcurl import error

### ISSUE THREAD

**Issue by rickgds80** [epsylon/ufonet#213]
To fix the error during libcurl import error try this:
http://pycurl.io/docs/latest/install.html

**Comment by rickgds80** [comment]
I solve this with:
apt install libcurl4-openssl-dev libssl-dev

and after i used:
pip install pycurl

and pycurl installation has done:

root@kali:~/root/ufonet/core# pip install pycurl
Collecting pycurl
  Using cached pycurl-7.43.0.5.tar.gz (216 kB)
ERROR: ufonet 1.4 requires GeoIP>=1.3.2, which is not installed.
Installing collected packages: pycurl
    Running setup.py install for pycurl ... done
Successfully installed pycurl-7.43.0.5

**Comment by rickgds80** [comment]
If doesn't works try upgrade your kali linux version with:

apt update && apt -y full-upgrade

And test running ufonet once again.

**Comment by epsylon** [comment]
@rickgds80 thanks!
