### ISSUE TITLE
botnet is only having 10 or less bots attack when my botnet is 200 or more. it also says the target is offline when bots are also attacking.

### ISSUE THREAD

**Issue by bucks9052** [epsylon/ufonet#217]
run an attack on an ip such as this one i tested on http://99.91.221.120 through the GUI with the map generated
Only 1 to 10 of my bots work when i expect at least 100 to work (my botnet has had 500 zombies with 10 working)
![image](https://user-images.githubusercontent.com/56772450/77483598-ef2c4c80-6dfe-11ea-8f61-1ebd337ed6c8.png)
ufonet version 1.4
installation method is git
OS is Linux Mint 19
python 3.6.9
No attack technique was specified when i used the attack
IP was 99.91.221.120
target was offline when i know target was online

**Comment by epsylon** [comment]
You should wait to that process for the end (sometimes takes long time because of timeouts, retries, delays..etc..). Also, sometimes GeoIP cannot resolve some locations propertly. Not so relevant "issue", mostly when mapping is just a performance of the actions made..
