### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by killerrdolphinn** [epsylon/ufonet#218]
it says Sorry, UFOnet requires Python > 3. im pretty sure i have the newest version of python 3

**Comment by epsylon** [comment]
@killerrdolphinn if you think that you have it, but it doesn't work, probably is because you have some other Python installations on your box. 

Check your alias and your virtual env path for python. 

Also, when you try: python --version, you should have an exit similar to: "Python 3.x.y"

**Comment by epsylon** [comment]
Also remember that you can launch UFONet just using: **python3 ufonet ...**

**Comment by killerrdolphinn** [comment]
how do install python 3

**Comment by killerrdolphinn** [comment]
i put python3 ufonet but when i try to run a command it says UFOnet does
not support python2

**Comment by Aholicknight** [comment]
Please quit replying on closed issues and look on google on how to install python 3. You have not provided us full details on what happens when you run it and what happens when you run it with python3. Please goto StackOverflow or any other site on how to install python3.  It's not that hard.

**Comment by killerrdolphinn** [comment]
i did install python 3 and it doesnt work still i type
cd ufonet
python3 ufonet
then i try to type a command and it says
Sorry, UFOnet does not support Python > 2

**Comment by epsylon** [comment]
@killerrdolphinn try this way: https://github.com/epsylon/ufonet/issues/219#issuecomment-611500801
