### ISSUE TITLE
Help Configure (NAT/IP)

### ISSUE THREAD

**Issue by Trillx** [epsylon/ufonet#22]
new to this ..... to keep it short i have been trying the (GUI) to set up NAT using TOR but have no clue i have skimmed through -----> http://ufonet.03c8.net/FAQ.html <---------- but do not find anything i have looked at this example  
------ >     + with proxy TOR:   ./ufonet -t 'botnet/zombies.txt' --proxy="http://127.0.0.1:8118"

pls help me set up NAT to use TOR proxie

**Comment by csong95** [comment]
Learn how to install tor first. SMH....
https://www.torproject.org/docs/debian

**Comment by Trillx** [comment]
@csong95 yeah i know mybad im still new to the linux/debian ..... dumb me man

**Comment by Trillx** [comment]
BUT NOW I HAVE A PROBLEM I GET---> ERROR<---

> [Error] You are using TOR as public IP... It's not possible to NAT!


root@kali:~/Desktop/ufonet# proxychains ./ufonet --attack-me
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| ::1 
|D-chain|-<>-127.0.0.1:9050-<>-127.0.0.1:9050-<--denied
|D-chain|-<>-127.0.0.1:9050-<><>-4.2.2.2:53-<><>-OK
|DNS-response| ::1 is 104.239.213.7
|DNS-request| ::1 
|D-chain|-<>-127.0.0.1:9050-<>-127.0.0.1:9050-<--denied
|D-chain|-<>-127.0.0.1:9050-<><>-4.2.2.2:53-<><>-OK
|DNS-response| ::1 is 104.239.213.7
=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

UFONet - DDoS Botnet via Web Abuse - by psy 

===========================================================================

Ordering 'zombies' to attack you for benchmarking ;-)

[Warning] You are going to reveal your real IP to your zombies...

Wanna continue (Y/n)y
-------------------------
======================
Mothership ID: skywalker | RND: 333628337080034806034821237729542986748
======================

Checking NAT/IP configuration:

|DNS-request| check.torproject.org 
|D-chain|-<>-127.0.0.1:9050-<>-127.0.0.1:9050-<--denied
|D-chain|-<>-127.0.0.1:9050-<><>-4.2.2.2:53-<><>-OK
|DNS-response| check.torproject.org is 138.201.14.212
|D-chain|-<>-127.0.0.1:9050-<>-127.0.0.1:9050-<--denied
|D-chain|-<>-127.0.0.1:9050-<><>-138.201.14.212:443-<><>-OK
[Error] You are using TOR as public IP... It's not possible to NAT!    <---------------------

**Comment by epsylon** [comment]
[Error] You are using TOR as public IP... It's not possible to NAT!

https://en.wikipedia.org/wiki/Network_address_translation
