### ISSUE TITLE
Error importing pycurl lib

### ISSUE THREAD

**Issue by h4ck3r-b0y** [epsylon/ufonet#221]
Hello.
I am attempting to run ufonet on MacOSX 13.6 terminal.
I've followed all the instructions perfectly till i got to "**python3 ufonet**" to run ufonet.
When i do that, i get the error, 

**Error importing: pycurl lib**

To install it on Debian based systems:

 **$ 'sudo apt-get install python3-pycurl'**

But i am using MacOSX 13.6 terminal. So i run.

**"pip install python3-pycurl"**

And i get

**Collecting python3-pycurl**
 ** ERROR: Could not find a version that satisfies the requirement python3-pycurl (from versions: none)**
**ERROR: No matching distribution found for python3-pycurl**

I try using pip3 too but i get the same error.

Then i attempt using homebrew

**"brew install python3-pycurl"**

Then i get this error,

**Updating Homebrew...
Error: No available formula with the name "python3-pycurl"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.**

Any help?

**Comment by epsylon** [comment]
https://github.com/epsylon/ufonet/issues/219#issuecomment-611500801
