### ISSUE TITLE
my net wont hit IPs

### ISSUE THREAD

**Issue by bucks9052** [epsylon/ufonet#222]
when i run "./ufonet -a https://65.190.131.127 -r 10" it says the target is offline when i know the target is online (I was talking to them over xbox and pulled their IP as a test and they said it was ok) it would say it was offline and would refuse to DDOS it can you help? I run linux mint 19 cinnamon on the latest version of ufonet (updated as of feb 26 2020)

**Comment by epsylon** [comment]
hey kid, but what do you think is this place? ... do you think you can come here and put messages with real IPs? ... do you want github to close my profile?.. what does that question have to do with the UFONet code ?. 

Do not answer me...

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by epsylon** [comment]
realed "toxic" user comments: https://github.com/epsylon/ufonet/issues/223
