### ISSUE TITLE
It keeps saying target offline

### ISSUE THREAD

**Issue by bucks9052** [epsylon/ufonet#223]
Run ./ufonet -a http://(insert IP here) -r 10
It will say target offline but when i try to hit a website such as my own it works fine
Ufonet version 1.4.1 
Installtion method was git
Python version 3.6.9
Linux Mint 19 cinnamon
I used tachyon and smurf
It was an IP i was stress testing (my own personal VPN server)
The console just told me it was offline and would refuse to attack

**Comment by epsylon** [comment]
> "It will say target offline but when i try to hit a website such as my own it works fine"
Well, differently to the most common idea, to DoS (deception) a target, it is not as easy as looks like. There are many factors to take control and others related to defense measures, such as filters or WAFs, etc..that are out of the hands of an "attacker". So, firstly, you should try to understand much more variables when trying a "pentesting" than if your target is online or not...

>  It will say target offline but when i try to hit a website such as my own it works fine
Maybe you have been firewalled. You can check this in many ways using other tools. Try this way first.

**Comment by bucks9052** [comment]
It said when offline generating exit and i sat there for a few minutes making sure that it was not waiting to attack.

**Comment by bucks9052** [comment]
I also checked i am not being firewalled

**Comment by bucks9052** [comment]
maybe i am doing the command wrong ? im entering ./ufonet -a http://(IP GOES HERE) -r 10 and it does that

**Comment by bucks9052** [comment]
![image](https://user-images.githubusercontent.com/56772450/79498805-e2fb6f80-7ff7-11ea-8a48-2db3f2d845d5.png)

**Comment by epsylon** [comment]
@bucks9052 are you kidding meb (us)?

How will it work if your target isn't even a valid IP or URL?. You are using as a target a sentence: "(IP GOES HERE"

What I'm seeing is that you don't read anything. Neither UFONet's messages, nor mine. 

Therefore, I ask you not to write again, at least, until you know what you are doing. If not, your messages will be discarded. It is clear?.

**Comment by bucks9052** [comment]
i inspected the page so it didnt show the ip i put a valid IP if u would like to know the IP i can tell you lol

**Comment by bucks9052** [comment]
i did read messages btw

**Comment by bucks9052** [comment]
i know what i am doing too

**Comment by epsylon** [comment]
It's more. From now on, all accounts like yours, which are created and the first thing they do is come here to waste my time, will from now on be **immediately ignored**.  

And if things do not change, I will directly close the account and you will seek life ...

**Comment by epsylon** [comment]
`i know what i am doing too` -> No, you don't!

**Comment by epsylon** [comment]
You are wasting my time and making Community think that UFONet is not working correctly, so intoxicating this place with your unoperance... So, you are really near to be kicked out from here..

**Comment by bucks9052** [comment]
im not trying to say it does not work it does i was just seeking help on why it would refuse to attack IPs UFONET is great and you are offering free highly secure botnets which is amazing and i inspect elemented the page as what you said in #222 showing IPs could get your account banned i am sorry and do not mean any harm

**Comment by epsylon** [comment]
So try to take more care about me, this project and this place, please, before to write whatever thing pass for your mind. Maybe you can try to ask using your native language. Or even other users can help to you with this tasks. Even, you have ~10.000 videos about UFONet, only on Youtube...

**Comment by bucks9052** [comment]
i have looked into that i am just trying to figure out when i attack an IP it says offline when my vpn server was still up and running all tutorials i have come across only attack websites and not IP addresses.

**Comment by epsylon** [comment]
maybe this was because...it was offline?.. you have more options to check your botnet. 

for example, you can try: --attack-me

**Comment by bucks9052** [comment]
this is what happened when i ran attack me 
![image](https://user-images.githubusercontent.com/56772450/79694121-6c02e880-823c-11ea-9ff0-04e23a4abd4e.png)

**Comment by bucks9052** [comment]
from what i could tell i had not configured tor properly how would i configure it? Also is tor needed for an attack?

**Comment by bucks9052** [comment]
i also ran this to make sure they are online 
![image](https://user-images.githubusercontent.com/56772450/79694972-06195f80-8242-11ea-8efa-ba75f7a9e6b7.png)

**Comment by Aholicknight** [comment]
@bucks9052 if you keep asking questions on how to use UFOnet then i don't think this program is right for you.

**Comment by bucks9052** [comment]
> @bucks9052 if you keep asking questions on how to use UFOnet then i don't think this program is right for you. It's commonsense on what the commands do.

i know how to use it i am just asking what i must be doing wrong for it not wanting to attack an IP

**Comment by def4ult7** [comment]
Hey same thinks happening me to. Can you help me ?

**Comment by Aholicknight** [comment]
> Hey same thinks

lol

**Comment by yesman983** [comment]
yeah, the target is being shown offline for me too.
can anyone help?

**Comment by Aholicknight** [comment]
> yeah, the target is being shown offline for me too.
> can anyone help?

@yesman983 this issue has been closed for a year by now, if you are still having the problem create a new one.
