### ISSUE TITLE
I can’t - -download-zombies

### ISSUE THREAD

**Issue by h1-html-h1** [epsylon/ufonet#225]
Hello, I’m writing this comment to ask you if you can help me, I have a problem with - - download-zombies command, when I write the command —download-zombies, I have this message
![image](https://user-images.githubusercontent.com/64026146/79768028-ba39e980-8319-11ea-8581-609a6bc283f9.jpg)

**Comment by Aholicknight** [comment]
Can you repeat the same command with `-v` and post the results?

**Comment by h1-html-h1** [comment]
I don’t get you @Aholicknight

**Comment by epsylon** [comment]
@h1-html-h1 maybe your IP has been firewalled... Btw, you can also download a copy similar to that Vortex at GitHub: **--download-github**

**Comment by Aholicknight** [comment]
@h1-html-h1 Do `ufonet --download-zombies -v` and post the results.
