### ISSUE TITLE
Ufonet GUI

### ISSUE THREAD

**Issue by ja-boo** [epsylon/ufonet#227]
Hello,
I am working with linux because of school work, so I Apologize for my little experience.

I can't seem to run GUI, after using command :python3 ufonet --gui
I receive this: 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(ufonet:2000): Gdk-CRITICAL **: 08:26:24.150: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

                                                0=============================================0
                                                ||                                           ||                                                                                                                                            
   ||                                     ||    ||  * Botnet -> [DDoS]:                      ||
 -(00)-                                 -(00)-  ||      /Zombies : HTTP GET bots             ||
   ||                (00)                 ||    ||      /Droids  : HTTP GET (+params) bots   ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||      /Aliens  : HTTP POST bots            ||
            |  |.''.( xx ).''.|  |              ||      /UCAVs   : Web Abusing bots          ||
            .'.'   X|'..'|X   '.'.              ||      /X-RPCs  : XML-RPC bots              ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||      /DBSTRESS: HTTP DB attack            ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||      /SPRAY   : TCP-SYN reflector         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||      /SMURF   : ICMP echo flooder         ||
        _ | ||  '-.___||___.-'  || | _          ||      /TACHYON : DNS amplificator          ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||      /MONLIST : NTP amplificator          ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||                                           ||
    | '###  |  =| | ###### | |=  |' ###  |      ||   * Close Combat -> [DoS]:                ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||      /LOIC    : Fast HTTP requests        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||      /LORIS   : Slow HTTP requests        ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       ||      /UFOSYN  : TCP-SYN flooder           ||
    .'_.-|                          |-._'.      ||      /XMAS    : TCP-XMAS flooder          ||
                                                ||      /NUKE    : TCP-STARVATION attack     ||
    + Class: UFONet / ViPR404+ (model G) +      ||                                           ||
                                                0|===========================================|0

But the GUI doesn't show up, I believe the "unable to connect" part is because I am running is at root, but I can't run it as sudo. And the firefox GUI doesn't open. 

Thanks in advance for any advice!

**Comment by epsylon** [comment]
@ja-boo it looks that you cannot open a socket port at: '9999' in your environment/box. Maybe, something related with permissions. You can try to check that on your netstat.

By the way, you can also try a workaround, by opening on a browser this url, manually: http://127.0.0.1:9999

If it doesn't work, there is indeed a problem with the socket. Either you cannot create it or another tool is using it.

**Comment by ja-boo** [comment]
Thank you!
