### ISSUE TITLE
"Running Firefox as root in a regular user's session Is not supported. ($XAUTHORITY Is /home/me/.Xauthority which Is owned by me.)"

### ISSUE THREAD

**Issue by imGris** [epsylon/ufonet#228]
When I try to get GUI of Ufonet It say me this:
"Running Firefox as root in a regular user's session Is not supported. ($XAUTHORITY Is /home/me/.Xauthority which Is owned by me.)"
How to solve this?
thanks

**Comment by epsylon** [comment]
Hi @imGris 

Currently, you don't need to run UFONet as root. Only with certain attacks in which it is necessary to open sockets. But the tool will ask you for the password. So you don't need administration permissions to make it work.

On the other hand, a workaround could be that you ignore the message and manually open a browser with your user (without privileges) and then visit the address: http://127.0.0.1:9999

Try it and tell me if it works for you.

A greeting.
