### ISSUE TITLE
Failed (cannot connect) bot issue

### ISSUE THREAD

**Issue by N04h31** [epsylon/ufonet#232]
Ok, so, i'm running ufonet in virtualization with os being parrotOS.
I connect to my virtualbox by the bridged adapter.
In parrotOS, my python version is the 3, i use tor and the only changes i did in tor configuration's profile was to change the type of proxychain (changed to dynamic) and to put a socks5 ip.
My DNS is 1.1.1.1(cloudfare)

proxychains.conf:
# defaults set to "tor"
socks4 	127.0.0.1 9050
socks5	127.0.0.1 9050

But when i run ufonet, i'm getting some issues that i can't connect to, like, 90% or 95% of my botnets and the target stay active even before the process.

P.S: i can't run GUI directly from the cmd, i have to open it directly from the browser (it wasn't working in the beginning even opening directly from the browser, until i stop tor) maybe it can be a port issue.

And i checked the status of the bots. As you can see, mostly return as ("online" but replying a invalid http code!)
![Screenshot_6](https://user-images.githubusercontent.com/30754015/82246654-78519280-991b-11ea-80c3-77ddf6305634.png)
![Screenshot_7](https://user-images.githubusercontent.com/30754015/82246658-7b4c8300-991b-11ea-96a6-85f0cea41dfc.png)

What it can be? Thanks for helping!

**Comment by Aholicknight** [comment]
Can you repeat this same command with `-v` then post the results on Pastebin or https://gist.github.com/ so we can see the logs? Thanks!

**Comment by Unreverse** [comment]
Changed to google dns now.
Here is the verbose process: https://pastebin.com/rx3qPDP2

Thx for the att

**Comment by Aholicknight** [comment]
@N04h31 it looks like the sites can't connect. Change your DNS and see if that problem is still happening.

**Comment by epsylon** [comment]
@N04h31 You need to **set a transparent proxy** (privoxy, polipo, etc..).
