### ISSUE TITLE
ufo gui

### ISSUE THREAD

**Issue by defalthek** [epsylon/ufonet#236]
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/secretive/.Xauthority which is owned by secretive.)

I facing with this problem.

**Comment by SkyBoltDom** [comment]
close this issue this a sandbox error and has nothing to do with the program.

**Comment by epsylon** [comment]
@defalthek related -> https://github.com/epsylon/ufonet/issues/228#issuecomment-626451040
