### ISSUE TITLE
It seems that tor is not properly set. Your IP appears to be xx.xx.xxx.77

### ISSUE THREAD

**Issue by Anuvab709** [epsylon/ufonet#238]
Hey Epsylon! I've configured tor in my browser. I've also installed privoxy and configured it.
Ive visited https://check.torproject.org/ and they say that i've configured. Still ufonet did'nt get it.
Moreover IP is different in the site and in ufonet
In the site xx.xx.xxx.43
Please Help

**Comment by Anuvab709** [comment]
`=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

Sending request to: https://check.torproject.org/

It seems that Tor is not properly set.

IP address appears to be: xx.xx.xxx.77
`

**Comment by Anuvab709** [comment]
> help pls

**Comment by Anuvab709** [comment]
> =========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

Sending request to: https://check.torproject.org/

It seems that Tor is not properly set.

IP address appears to be: 47.29.225.77

**Comment by Anuvab709** [comment]
`=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

Sending request to: https://check.torproject.org/

It seems that Tor is not properly set.

IP address appears to be: 47.29.225.77
`

**Comment by Anuvab709** [comment]
`=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

Sending request to: https://check.torproject.org/

It seems that Tor is not properly set.

IP address appears to be: xx.xx.xxx.77
`

**Comment by Aholicknight** [comment]
If you want help you wouldn't be spamming this asking for help. Be patient and wait.

**Comment by SkyBoltDom** [comment]
try http instead of socks proxy in config

**Comment by epsylon** [comment]
@Aholicknight @SkyBoltDom thanks!

@Anuvab709 try to take a look here, first: https://github.com/epsylon/ufonet/issues?q=is%3Aissue+is%3Aclosed+tor

ex: https://github.com/epsylon/ufonet/issues/151

**Comment by Anuvab709** [comment]
Thanks for the help!
