### ISSUE TITLE
You are using TOR as public IP.. It's not possible to NAT ->[Aborting!]

### ISSUE THREAD

**Issue by KillerTheBee** [epsylon/ufonet#239]
Hi epsylon,

 I have this problem when i try to attack me : 
![error1](https://user-images.githubusercontent.com/61102077/83696835-777f5880-a5cb-11ea-9cb5-d2681442b311.png)
 
Im using the command :  proxychains python3 ufonet --attack-me

and when i try proxychains python3 ufonet --check-tor everything seems good : 
![error2](https://user-images.githubusercontent.com/61102077/83697110-1efc8b00-a5cc-11ea-9a6c-6b53b0b731b2.png)

I have triyed it on bot Kali and Blackarch but can't make it work is there something i forgot to do?
Thanks for your read !
P.S i also looked through issues that had already been closed but couldn't find my answer there.

**Comment by epsylon** [comment]
@KillerTheBee This is not a UFONet problem, but a comprehension problem. In fact, you haven't read ANYTHING and that's why you waste my time...

How are bots going to connect to your master, if you use ToR?. 

Think about it...

**Comment by KillerTheBee** [comment]
@epsylon  woow what a terrible support you could at least tell me what i didn't read or what i didn't understand you just tell me you have a comprehension problem i read all your docs and shit on your website plus this error happen when i try too attack my website too

**Comment by epsylon** [comment]
@KillerTheBee Come on!... 

Look that even the topic of this thread (written by you) is giving the reply!. 

Or the image that you have provided. Did you read it, REALLY? ;-)

**NAT (your router) <-> TOR (other's router)**

**Comment by KillerTheBee** [comment]
Thanks for your more detailed answer i will try to fix it using these informations thanks for your time :)

**Comment by KillerTheBee** [comment]
Thanks for your answer i will try to understand it using the information you gave me
