### ISSUE TITLE
Still cant run it

### ISSUE THREAD

**Issue by Nextgenthebear** [epsylon/ufonet#24]
I ran " sudo pip install requests " and it downloaded and i still try to do " ./ufonet " and it says " Traceback (most recent call last):
File "./ufonet", line 10, in
from core.main import UFONet
File "/home/nextgen/Downloads/ufonet-v0.8/core/main.py", line 16, in
from herd import Herd
File "/home/nextgen/Downloads/ufonet-v0.8/core/herd.py", line 11, in
import zombie
File "/home/nextgen/Downloads/ufonet-v0.8/core/zombie.py", line 10, in
import pycurl, StringIO, md5, re
ImportError: No module named pycurl "

**Comment by epsylon** [comment]
Try to understand output provided by tool. 

Also try to read documentation, where is explained how to install it and which libraries you need to run it... 

http://ufonet.03c8.net/#installation

You don't pay attention (RTFM) and still wasting time of others... 

>  ImportError: No module named pycurl "

 **sudo apt-get install python-pycurl python-geoip**
