### ISSUE TITLE
i cant install ufonet

### ISSUE THREAD

**Issue by Darkbeast-glitch** [epsylon/ufonet#241]
kali@kali:~/ufonet$ sudo    pip install GeoIP
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting GeoIP
  Using cached GeoIP-1.3.2.tar.gz (20 kB)
Building wheels for collected packages: GeoIP
  Building wheel for GeoIP (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-XONtPl
       cwd: /tmp/pip-install-8kQVKc/GeoIP/
  Complete output (14 lines):
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'GeoIP' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
  py_GeoIP.c:21:10: fatal error: Python.h: No such file or directory
     21 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for GeoIP
  Running setup.py clean for GeoIP
Failed to build GeoIP
Installing collected packages: GeoIP
    Running setup.py install for GeoIP ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-UxAn_0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/GeoIP
         cwd: /tmp/pip-install-8kQVKc/GeoIP/
    Complete output (14 lines):
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
    py_GeoIP.c:21:10: fatal error: Python.h: No such file or directory
       21 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kQVKc/GeoIP/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-UxAn_0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/GeoIP Check the logs for full command output.
kali@kali:~/ufonet$

**Comment by caipenpen** [comment]
Hello , You must run python3 .

Pip must change to pip3 it will ok

**Comment by Darkbeast-glitch** [comment]
OK sir

**Comment by epsylon** [comment]
0) BUG-REPORT-TEMPLATE: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
1) FAQ: https://ufonet.03c8.net/FAQ.html
2) New code (v1.5) has been released -> Update your package!
3) READ!!! -> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as **Python 2.7 is no longer maintained**...

**Comment by spectrebsd** [comment]
Hi, I reinstalled Kali Linux, last time I finally could install it and solve all the fixes but this time I cant. Could you help me please?

  self.initialize_options()
In file included from /usr/include/python3.11/Python.h:86,
                 from src/_fastmath.c:31:
/usr/include/python3.11/cpython/pytime.h:208:60: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  208 | PyAPI_FUNC(int) _PyTime_FromTimespec(_PyTime_t *tp, struct timespec *ts);
      |                                                            ^~~~~~~~
/usr/include/python3.11/cpython/pytime.h:213:56: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  213 | PyAPI_FUNC(int) _PyTime_AsTimespec(_PyTime_t t, struct timespec *ts);
      |                                                        ^~~~~~~~
/usr/include/python3.11/cpython/pytime.h:217:63: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  217 | PyAPI_FUNC(void) _PyTime_AsTimespec_clamp(_PyTime_t t, struct timespec *ts);
      |                                                               ^~~~~~~~
src/_fastmath.c: In function ‘longObjToMPZ’:
src/_fastmath.c:74:23: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
   74 |         if (p->ob_base.ob_size > 0) {
      |                       ^
src/_fastmath.c:75:34: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
   75 |                 size = p->ob_base.ob_size;
      |                                  ^
src/_fastmath.c:78:35: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
   78 |                 size = -p->ob_base.ob_size;
      |                                   ^
src/_fastmath.c:93:36: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
   93 |                 mpz_set_ui (temp, p->ob_digit[i]);
      |                                    ^~
src/_fastmath.c: In function ‘mpzToLongObj’:
src/_fastmath.c:118:27: warning: implicit declaration of function ‘_PyLong_New’; did you mean ‘_PyLong_GCD’? [-Wimplicit-function-declaration]
  118 |         PyLongObject *l = _PyLong_New (size);
      |                           ^~~~~~~~~~~
      |                           _PyLong_GCD
src/_fastmath.c:118:27: warning: initialization of ‘PyLongObject *’ {aka ‘struct _longobject *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
src/_fastmath.c:127:18: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
  127 |                 l->ob_digit[i] = (digit) (mpz_get_ui (temp) & PyLong_MASK);
      |                  ^~
src/_fastmath.c:135:29: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
  135 |         while ((i > 0) && (l->ob_digit[i - 1] == 0))
      |                             ^~
src/_fastmath.c:138:19: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
  138 |         l->ob_base.ob_size = i * sgn;
      |                   ^
src/_fastmath.c: In function ‘rabinMillerTest’:
src/_fastmath.c:1372:57: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
 1372 |         if (mpz_fits_ulong_p (n) && (mpz_get_ui (n) - 2 < rounds))
      |                                                         ^
src/_fastmath.c:1374:23: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
 1374 |         for (i = 0; i < rounds; ++i)
      |                       ^
error: Setup script exited with error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
