### ISSUE TITLE
i cant get new zombies

### ISSUE THREAD

**Issue by tussalhorizon** [epsylon/ufonet#242]
ive been having a fair bit of problems with ufonet but those were solved by youtube and now if i try to get new zombies it wont word auto search as found 50687 zombies but it goes on for ever and if i try to get them from a blackhole it cannot connect                                                                                                          Edit: i also when i get new zombies it also doesnt add them

**Comment by epsylon** [comment]
0) BUG-REPORT-TEMPLATE: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
1) FAQ: https://ufonet.03c8.net/FAQ.html
2) A code (v1.5) has been released -> Update your package!
