### ISSUE TITLE
Error , can't detect botnet !

### ISSUE THREAD

**Issue by caipenpen** [epsylon/ufonet#243]
Hello , First time I use I search and attack use command every is ok .
but I open GUI and use GUI for search , it take over 1 day and not completed I must stop by hand .

Today I try to attack by command but It said

[Error] [AI] [Control] Cannot found [Zombies] from: 'botnet/zombies.txt' -> [Aborting!]

But If I use GUI to attack it succeed . I don't know how to fix this problem . Can you help me?

**Comment by epsylon** [comment]
0) BUG-REPORT-TEMPLATE: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
1) FAQ: https://ufonet.03c8.net/FAQ.html
2) New code (v1.5) has been released -> Update your package!
