### ISSUE TITLE
Auto remove zombies after Nuke !!!

### ISSUE THREAD

**Issue by caipenpen** [epsylon/ufonet#244]
After use Nuke attack it auto remove all my zombies . What's problems with that ?

**Comment by epsylon** [comment]
0) BUG-REPORT-TEMPLATE: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
1) FAQ: https://ufonet.03c8.net/FAQ.html
2) New code (v1.5) has been released -> Update your package!
