### ISSUE TITLE
Can't inspecting target for local resource !!!

### ISSUE THREAD

**Issue by caipenpen** [epsylon/ufonet#245]
I try with 
sudo python3 ufonet -i https;//trustsold.com and result always 0 , I also use with another site is https://martme.net and it show 0 result too . They site run woocommerce . I already download newest verison v1.5

And I want to ask I see the new DNS attack is NXNSattack . Can you import it to your tools ?

http://www.nxnsattack.com

Thank you .

**Comment by epsylon** [comment]
Hey kid, let's see ...

You created your account 2 days ago and reported 6 issues here. You are a little annoying, don't you think?

I'm telling you to use the template to make reports and you don't listen to me. Furthermore, all the problems you report, in addition to being poorly explained, have nothing to do with the code.

Do you want me to put a ban on you?
