### ISSUE TITLE
Cant access the gui of ufonet i get the following erros

### ISSUE THREAD

**Issue by Darkbeast-glitch** [epsylon/ufonet#246]
kali@kali:~/ufonet$ sudo python3 ufonet --gui 

                                                0=============================================0
                   + (XX) +                     ||                                           ||
   ||             *~~~~~~~~*              ||    ||  * Botnet -> [DDoS]:                      ||
 -(00)-          (0)      (0)           -(00)-  ||      /ZOMBIES : HTTP GET bots             ||
   ||             \| (00) |/              ||    ||      /DROIDS  : HTTP GET (+params) bots   ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||      /ALIENS  : HTTP POST bots            ||
            |  |.''.( xx ).''.|  |              ||      /UCAVs   : Web Abusing bots          ||
            .'.'   X|'..'|X   '.'.              ||      /X-RPCs  : XML-RPC bots              ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||      /DBSTRESS: HTTP Database flooder     ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||      /SPRAY   : TCP-SYN reflector         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||      /SMURF   : ICMP echo flooder         ||
        _ | ||  '-.___||___.-'  || | _          ||      /TACHYON : DNS amplificator          ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||      /MONLIST : NTP amplificator          ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||                                           ||
    | '###  |  =| | ###### | |=  |' ###  |      ||   * Close Combat -> [DoS]:                ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||      /LOIC    : Fast HTTP requests        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||      /LORIS   : Slow HTTP requests        ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       ||      /UFOSYN  : TCP-SYN flooder           ||
    .'_.-|            YY            |-._'.      ||      /XMAS    : TCP-XMAS flooder          ||
                                                ||      /NUKE    : TCP-STARVATION attack     ||
    + Class: UFONet / ViPR404+ (model H) +      ||                                           ||
                                                0|===========================================|0

Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/home/kali/ufonet/core/main.py", line 1201, in run
    self.create_web_interface()
  File "/home/kali/ufonet/core/main.py", line 2767, in create_web_interface
    tcpsock.bind((host,port))
OSError: [Errno 98] Address already in use
kali@kali:~/ufonet$ Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/kali/.Xauthority which is owned by kali.)

**Comment by epsylon** [comment]
@Darkbeast-glitch you start to be a bit annoying (https://github.com/epsylon/ufonet/issues/241) with this reports... mostly, because you don't read nothing. 

 **OSError: [Errno 98] Address already in use**

You have the socket busy, try to close it and re-run it again. Also, you don't need to use UFONet as root...

Btw, If you keep reporting this things, you will be banned from here. Ok?
