### ISSUE TITLE
"/usr/lib64/python3.6/encodings/ascii.py"

### ISSUE THREAD

**Issue by POSTiGA1** [epsylon/ufonet#247]
Hello Sir, 

Virtual Server under CentOS 7 , had the same issue with Ubuntu too

sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    long_description=open('docs/README.txt').read(),
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8353: ordinal not in range(128)

**Comment by dontbanmeplz** [comment]
Same problem

**Comment by epsylon** [comment]
@POSTiGA1 This has to do with the fact that the encoding of your box is not **UTF-8**. 

Probably because you are using a different one (Chinese, Arabic, etc.). 

You have to change the environment variable for it to work. But not only UFONet, but any other similar Python program.

**Comment by epsylon** [comment]
@dontbanmeplz Do you think I'm stupid?. 

Are you kidding me?. You do not have that codification, as I have been able to verify in other threads in which you have participated. 

You spend the day intoxicating this place, the forums and the tool. 

You have mental problems?. Do you need my attention ?. Or are you just a jerk?.

 You've earned a ban.

Imbécil!
