### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mylobi** [epsylon/ufonet#248]
Hi, i have a problem with ufonet, can you help me ? 😀 

« Running Firefox as root in regular user’s session is not supported. »  

![774164D3-C5F1-4BD3-9A2C-CC93E1D92BEA](https://user-images.githubusercontent.com/66796973/84423383-a9716a00-ac1e-11ea-90a1-651eadf3e2f2.jpeg)

**Comment by Aholicknight** [comment]
Nah. You already created an issue and creating more will not fix this.
