### ISSUE TITLE
Error ufonet

### ISSUE THREAD

**Issue by mylobi** [epsylon/ufonet#249]
![B76746AF-938C-41AB-982B-24F6C82176FE](https://user-images.githubusercontent.com/66796973/84422860-edb03a80-ac1d-11ea-8985-4891e61ceffb.jpeg)

**Comment by Aholicknight** [comment]
So do you think creating a shit ton of issues will solve your problem? Before creating a fuck load of issues I suggest you going on google and searching for your problem, they actually tell you how to fix it instead of creating issues.
