### ISSUE TITLE
error after entering command python3 ufonet --gui

### ISSUE THREAD

**Issue by neiry** [epsylon/ufonet#252]
hi, tell me. After starting the interface, it goes to the default browser. where does the connection error immediately write

**Comment by Aholicknight** [comment]
I swear, you guys can install the program all good but as soon as something goes wrong you lose your shit and demand the creator of UFONET to fix it. USE GOOGLE!

**Comment by neiry** [comment]
> I swear, you guys can install the program all good but as soon as something goes wrong you lose your shit and demand the creator of UFONET to fix it. USE GOOGLE!

you can write on the case of my question. not your tantrums?

**Comment by Aholicknight** [comment]
I already know how to fix that problem but you should repeat that same command and add `-v` onto it then copy what it said then paste into this and comment it.
