### ISSUE TITLE
just saying

### ISSUE THREAD

**Issue by bucks9052** [epsylon/ufonet#254]
The new update was great just one thing i believe should be added: in the attack section could you possibly add a dedicated box to attack an IP address. Even if you do not ufonet is great keep up the good work!

**Comment by dontbanmeplz** [comment]
the way that ufonet works is through sending GET requests through websites to other websites with rederections (corect me if i am wrong) you cant attack an ip and it would have to be running a web server. @epsylon right?

**Comment by epsylon** [comment]
@dontbanmeplz exactly! (but remembar that it is also using POST)
@bucks9052 you just need to enter your IP same way as a domain. We don't need another box for that -> ex: http(s)://IP_NUMBER
