### ISSUE TITLE
ufonet with proxychains

### ISSUE THREAD

**Issue by digitalosaurus** [epsylon/ufonet#255]
Hi,
just wanted to ask if its possible to use ufonet with proxychains. Just asking because everytime i start ufonet gui with proxychains I get an error. Thx for asnwearing.

**Comment by dontbanmeplz** [comment]
What is the error?

**Comment by epsylon** [comment]
@digitalosaurus yes, you can use it.

**Comment by digitalosaurus** [comment]
Thats ubfortunate everythime i try i cant start it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by epsylon** [comment]
@digitalosaurus So what?.. Do you think I am adivine?...You aren't providing any clue about your issue.
Proxychains is working perfectly with UFONet. You should try to review how is your configuration.
ex: **proxychains python3 ufonet --gui**

**Comment by digitalosaurus** [comment]
Oh, we habe an egy teen over here

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: psy <notifications@github.com>
Gesendet: Thursday, July 2, 2020 9:21:51 PM
An: epsylon/ufonet <ufonet@noreply.github.com>
Cc: Thomas Stinner <Thomas.Stinner@stinner-it.com>; Mention <mention@noreply.github.com>
Betreff: Re: [epsylon/ufonet] ufonet with proxychains (#255)


@digitalosaurus<https://github.com/digitalosaurus> So what?.. Do you think I am adivine?...You aren't providing any clue about your issue.
Proxychains is working perfectly with UFONet. You should try to review how is your configuration.
ex: proxychains python3 ufonet --gui
