### ISSUE TITLE
 [AI] Launching: 'Is target up?' check...  [Info] [AI] [Control] From YOU: NO -> [Target looks OFFLINE!]

### ISSUE THREAD

**Issue by Create198** [epsylon/ufonet#257]
Please help！
I can ping to the IP address of the server, but why is it offline.

After submitting the attack, the address shown in the map is incorrect. Geoip geoip 2 Python geoip and others are installed。

 “[AI] Launching: 'Is target up?' check...  [Info] [AI] [Control] From YOU: NO -> [Target looks OFFLINE!]”

**Comment by bucks9052** [comment]
i had the same issue

**Comment by dontbanmeplz** [comment]
The target is offline???

**Comment by ajunkdha** [comment]
Yah lol offline.. somtime wrong in zombie

**Comment by epsylon** [comment]
this should be fixed after this commit: https://github.com/epsylon/ufonet/commit/753904e3923c9d972997ff7b060acce38c3801f9
