### ISSUE TITLE
python3 ./ufonet --gui error

### ISSUE THREAD

**Issue by kiyamaryota** [epsylon/ufonet#258]
Firefox does not start when I run python3 ./ufonet --gui.
No error is displayed and the cause is unknown.

Is Firefox the source of the error?
Does Firefox have any special settings?

**Comment by Bobowonnell** [comment]
Same for me with chrome

**Comment by Bobowonnell** [comment]
So the problem is is that the website isnt oppening so just manually type in 127.0.0.1:9999 
(Or copy and paste that) into the search bar and you will be good

**Comment by kiyamaryota** [comment]
Thank you Bobowonnell! !

I was able to boot safely!
