### ISSUE TITLE
sudo apt-get install python3-scapy problem

### ISSUE THREAD

**Issue by Abdelrhaman2** [epsylon/ufonet#259]
okay i thin i need to remove the old package 
am I right ?

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gsettings-desktop-schemas : Breaks: mutter (< 3.31.4) but 3.30.2-7 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by dontbanmeplz** [comment]
Try 
`pip install scapy`

**Comment by Abdelrhaman2** [comment]
sudo pip install scapy
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (2.4.0)

**Comment by epsylon** [comment]
Requirement already satisfied: scapy in /usr/lib/**python2.7**/dist-packages (2.4.0) -> Python2 is not longer supported.

**Comment by Abdelrhaman2** [comment]
thank u :)
