### ISSUE TITLE
Cant start new thread on nethunter.

### ISSUE THREAD

**Issue by pahapoika** [epsylon/ufonet#26]
Hey.
I have been running this on Kali Linux.
But now i wanted to test this on Kali Nethunter. (Kali linux for Android) And i got it installed.
But when i attack to someone i get error. This is error traceback.
File "usr/lib/python2.7/threading.py" line 736, in Start error. Can't start new thread.
Can u help me?

**Comment by epsylon** [comment]
Error. Can't start new thread: http://ufonet.03c8.net/FAQ.html
