### ISSUE TITLE
No module named 'Crypto'

### ISSUE THREAD

**Issue by dimablox** [epsylon/ufonet#260]
Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/home/db/ufonet/core/main.py", line 1201, in run
    self.create_web_interface()
  File "/home/db/ufonet/core/main.py", line 2759, in create_web_interface
    from .webgui import ClientThread
  File "/home/db/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/home/db/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

please help..

**Comment by dimablox** [comment]
this is what i get when i type ufonet --gui

**Comment by epsylon** [comment]
**sudo apt-get install python3-crypto**

**Comment by Vikingo-07** [comment]
no work. --> "sudo apt-get install python3-crypto"

**Comment by epsylon** [comment]
dupe: https://github.com/epsylon/ufonet/issues/417

@Vikingo-07 -> https://github.com/epsylon/ufonet/issues/417#issuecomment-1240483016

try this:

```
sudo pip3 uninstall crypto
sudo pip3 uninstall pycrypto

sudo pip3 install pycrypto
```

**Comment by Vikingo-07** [comment]
I am do that, no work

**Comment by justsalahdev** [comment]
is esay use this 
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
