### ISSUE TITLE
not opening gui

### ISSUE THREAD

**Issue by kian-git** [epsylon/ufonet#263]
it dosent open the gui when i type python3 ./ufonet --gui

**Comment by nero9998** [comment]
pretty absurd, need help fixing something as well.
ufo is trying to open up with python2.

**Comment by epsylon** [comment]
@kian-git  you don't need that **./**
ex: **python3 ufonet --gui**
btw, you can try also to open it manually by visiting this url: **http://127.0.0.1:9999**
