### ISSUE TITLE
will layer 4 support ever be added?

### ISSUE THREAD

**Issue by bucks9052** [epsylon/ufonet#264]
just a question

**Comment by epsylon** [comment]
good question @bucks9052 

technically, it is implemented, since UFOSYN is performing a SYN Flood attack, which is exactly in the OSI model, at the transport layer or layer 4.

btw, do you have something different in mind?

**Comment by bucks9052** [comment]
im talking layer 4 support without running a web application running. From my understanding (correct me if i am wrong) UFONET can not launch a DDOS attack on the layer 4 network without the IP running a web application.

**Comment by epsylon** [comment]
You can do it, just ignoring "Failed Connect" msg from layer 7 and previous check "Is Alive". 
A good method to see how the tool really works at this other layers is to use Wireshark with it.

Ex: **python3 ufonet -a "http://123.123.123.123" --no-head --ufosyn 10000**

```
[Info] [AI] TCP SYN Flooder (UFOSYN) is ready to fire: [ 1000 quantum hooks ]
[Info] [Zombies] https://thebelmontstore.com/logout?redir= -> FAILED (cannot connect!)
[Info] [AI] [UFOSYN] Firing 'quantum hook' [1] -> [FLOODING!]
```

**Comment by epsylon** [comment]
![dfasfasdfadsfasd](https://user-images.githubusercontent.com/499387/88245525-0aad4400-cc87-11ea-9f1e-ad1cb43ab940.png)

**Comment by l7nc7** [comment]
hi. he means if he can attack ips like: 23.94.13.194 without http(s);// ex: in the picture 
<img width="960" alt="layer4" src="https://user-images.githubusercontent.com/62824658/145378555-bee1f176-41c6-41e6-9765-58ea8e8c43e4.png">

**Comment by l7nc7** [comment]
<img width="960" alt="lay4" src="https://user-images.githubusercontent.com/62824658/145378607-0f6b8974-1045-407e-981e-6e6e397fb31e.png">

**Comment by l7nc7** [comment]
cuz when i tried python3 ufonet -a http://8.8.8.8. its says the target looks offline something like that. but we are asking if we can attack ipv4 servers like home connection or games severs or voice & vpns severs. hope u understand

**Comment by l7nc7** [comment]
i know im tooo late

**Comment by l7nc7** [comment]
sometimes we don't want just attacking websites. sometimes we need to attack ipv4. that dont have a website its just a alone server

**Comment by l7nc7** [comment]
its seems ur tool just supports attacks on ( websites ) i hope u add Layer 4 for ipv4 servers that we can enjoy into it

**Comment by dontbanmeplz** [comment]
This is not the way ufonet works
It cannot attack ips because it uses websites redirecting to send requests to websites
Please close this issue and buy a botnet to do this yourself
