### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by jetski300** [epsylon/ufonet#268]
Hello!
It seems like a nice project, everything seems to work, unfortunately http site cannot be taken offline. I'm using the command: python3 ufonet -a http://xxxxxx.xxx -r 100 --threads 500
Am I doing something wrong?
Thanks

**Comment by dontbanmeplz** [comment]
The GUI is a bit easyer to use. The that

**Comment by dontbanmeplz** [comment]
Also you might just not have enough bots or the site may be too strong. This is a cool tool and it works but you need to gather bots. It’s not point and click

**Comment by jetski300** [comment]
Thanks for the quick response!
I am using it via termux ubuntu. I've tried the gui but it doesn't work in my browser seems.
The site is certainly not too strong, I can get it offline with 120 socks5. 
Which command do you recommend to me with ufonet
Greetz

**Comment by dontbanmeplz** [comment]
`./ufonet —gui`

**Comment by dontbanmeplz** [comment]
That’s 2 dashes

**Comment by jetski300** [comment]
![Screenshot__Termux](https://user-images.githubusercontent.com/70169454/91665471-20b7eb00-eaf6-11ea-949d-49df7900c07f.jpg)

... nothings happen

**Comment by jetski300** [comment]
> ![Screenshot__Termux](https://user-images.githubusercontent.com/70169454/91665471-20b7eb00-eaf6-11ea-949d-49df7900c07f.jpg)
> 
> ... nothing happens

**Comment by jetski300** [comment]
I think the gui is working now i try further
thanks

**Comment by jetski300** [comment]
Gui works. All looks nice 
BUT it DOESN'T work at all!  Very Pity

**Comment by epsylon** [comment]
@jetski300 FAQ: http://ufonet.03c8.net/FAQ.html
