### ISSUE TITLE
Error trying to search automatically for Botnets etc. 

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#269]
How to fix this error? I'm trying to search automatically for botnets while using all search engines 
Also I have an error downloading botnets in the community but in the github I can...
<img width="506" alt="botnet" src="https://user-images.githubusercontent.com/68110223/91875455-2a6f5900-ec84-11ea-8f88-31e302929467.PNG">

**Comment by dontbanmeplz** [comment]
`pip3 install numpy`

**Comment by MiChaelinzo** [comment]
<img width="353" alt="botnet3" src="https://user-images.githubusercontent.com/68110223/91876847-df564580-ec85-11ea-997a-bd0f50c76dd7.PNG">

**Comment by epsylon** [comment]
python3 -m pip install numpy

**Comment by MiChaelinzo** [comment]
> python3 -m pip install numpy

<img width="329" alt="botnet4" src="https://user-images.githubusercontent.com/68110223/91972890-019ea080-ed24-11ea-9c18-17c4ad6a4c28.PNG">

**Comment by epsylon** [comment]
Your numpy package for Python3.8 looks pretty old. 

https://stackoverflow.com/questions/54721703/modulenotfounderror-no-module-named-numpy-core-multiarray-umath-while-insta

Please, try to update it to a more recent version.

python3.8 -m pip search numpy

```
numpy (1.19.1)                            - NumPy is the fundamental package for array computing with Python.
  INSTALLED: 1.19.0
  LATEST:    1.19.1
```

On the other hand, Did you tried to install the tool using provided setup.py?

EX: **sudo python3.8 setup.py install**

Or even to install numpy directly from the OS repos?

**sudo apt-get install python3-numpy**

**Comment by MiChaelinzo** [comment]
I did sudo apt-get remove python3-numpy
and installed it again run pip3 show numpy
Version 1.15.2 
I also did this sudo pip3 install --upgrade numpy
<img width="370" alt="botnet5" src="https://user-images.githubusercontent.com/68110223/91994284-1dfc0680-ed3f-11ea-9113-0af2069a847c.PNG">

**Comment by epsylon** [comment]
@MiChaelinzo numpy version 1.15.2 is deprecated... it doesn't support "multiarray_umath" function. You should try to upgrade your repositories first, and after, upgrade that lib.

**Comment by epsylon** [comment]
> You should try to upgrade your repositories first, and after, upgrade that lib.
1) **pip3 install --upgrade pip**
2) **pip3 install numpy**
