### ISSUE TITLE
GUI ship.links, ship.streams, global.net are not working

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#270]
The GUI is very friendly but some of the features are not working. I'm in the latest version etc. I tried opening /clicking several times but they just won't display data or do anything...
<img width="426" alt="botnet2" src="https://user-images.githubusercontent.com/68110223/91876414-517a5a80-ec85-11ea-8098-6412c3b7791d.PNG">

**Comment by dontbanmeplz** [comment]
What are you trying to do exactly

**Comment by MiChaelinzo** [comment]
> What are you trying to do exactly

read/decrypt news, forums, watch streams, send links and submit settings etc. none of them are displaying anything except missions and games, etc.

**Comment by epsylon** [comment]
@MiChaelinzo this is probably because your connection has been firewalled... Service is up and running!. 

Try it with a different IP (ex: TOR), or just wait to be unbanned...

**Comment by MiChaelinzo** [comment]
> @MiChaelinzo this is probably because your connection has been firewalled... Service is up and running!.
> 
> Try it with a different IP (ex: TOR), or just wait to be unbanned...

Blackhole already using different ip from mine and submit update it. I'll try to use vpn

**Comment by epsylon** [comment]
@MiChaelinzo you mean to "upload" or "download" content to/from this sections, that you are pointing on your previous messages?

**Comment by MiChaelinzo** [comment]
Yes those included

**Comment by MiChaelinzo** [comment]
is 176.28.23.46 the default blackhole for everyone?

**Comment by epsylon** [comment]
@MiChaelinzo but, upload or download?. Both can be related with your firewalled IP, but if is Upload, this can be because the server is not accepting/listening for new content and maybe the script should be restarted.

**Comment by epsylon** [comment]
@MiChaelinzo you were right. Something was wrong with grider.py when uploading content. 
I have patched it here: https://github.com/epsylon/ufonet/commit/d9980f21822570672bd4195f9790adef8ef2f1b6
Now should be fixed: 
![35y254yw](https://user-images.githubusercontent.com/499387/93596787-7ec74800-f9a9-11ea-841f-a3a364cd7832.png)
Thanks!
