### ISSUE TITLE
on executing gui

### ISSUE THREAD

**Issue by rijinrij** [epsylon/ufonet#271]
home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_target_dec is not "":
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 0: # not any data (or decryption allowed) on grid so discard
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2373: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 1: # add this player as a rookie
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2376: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 2: # add this player as a mercenary
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2379: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 3: # add this player as a bandit
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2382: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 4: # add this player as a ufommander
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:2385: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 5: # add this player as a ufoleet
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:4222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:4249: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not "":
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:4328: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:4390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:5501: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # stream creation + encryption + package send
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:5712: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_enckey is not "": # stream creation + encryption + package send
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:5778: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_enckey is not "": # stream creation + encryption + package send
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:5842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_enckey is not "": # stream creation + encryption + package send
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:5913: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_enckey is not "": # stream creation + encryption + package send
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6073: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if news_key is not "": # news decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6095: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if missions_key is not "": # missions decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6202: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "": # board decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:6281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # grid decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:7033: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_deckey is not "": # wargames decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:7177: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_deckey is not "": # links decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:7227: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_deckey is not "": # streams decryption
/home/mrcyguru/Desktop/script/ufonet/core/webgui.py:7279: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_deckey is not "": # globalnet decryption

**Comment by epsylon** [comment]
@rijinrij UFOnet not longer support Python 2.x.. you should try it with Python3 (ex: **python3 ufonet --gui**)
