### ISSUE TITLE
Import libraries issue MacOS Catalina 10.15.6

### ISSUE THREAD

**Issue by Jafifa** [epsylon/ufonet#272]
Im trying to set up ufonet on a macOS system and im having some trouble with the libraries, i tried all 3 commands to install it, if i use the setup.py, the download goes correctly until an error message pops out:
 py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found

if i try pip3: 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycurl in /Users/jamonfarol/Library/Python/3.8/lib/python/site-packages (7.43.0.6)

and the apt-get won't work as its not a "Debian based system"

i also may add im kinda new to python so this may be a dumb issue

**Comment by epsylon** [comment]
hey @Jafifa try this way:
`python3.8 -m pip install pygeoip python-geoip`

**Comment by Jafifa** [comment]
it does work, but the main issue comes when i execute `python3 ufonet` 
Error importing: pycurl lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-pycurl'
and yes, i did `python3.8 -m pip install pycurl python-pycurl`

**Comment by Jafifa** [comment]
i tried to make a vm with kali linux but as my pc is comparable to a potato it won't run two os with half the amount of RAM

**Comment by dontbanmeplz** [comment]
Use wsl

**Comment by Jafifa** [comment]
whats wsl

**Comment by Jafifa** [comment]
anyway, discord will be faster and safer than this, dm me to Jafifa1605#9897 and if necessary, a report will be posted here with the solution

**Comment by dontbanmeplz** [comment]
Windows subsystem for linux

**Comment by Jafifa** [comment]
im on macOS, can't execute vms neither for windows or for linux because apple's products are potato and can't handle 2 os at the same time

**Comment by epsylon** [comment]
To fix this error:

**sudo apt-get install python3-geoip libgeoip-dev libgeoip1**

**Comment by Jafifa** [comment]
I appreciate your help, however I recently got a new computer strong enough to handle a linux vm
