### ISSUE TITLE
Question about running

### ISSUE THREAD

**Issue by muppley** [epsylon/ufonet#273]
ive installed everything, but there are so many files to open idk which one to run.

**Comment by MiChaelinzo** [comment]
Install setup.py & make ufonet executable and your done!

**Comment by MiChaelinzo** [comment]
> ive installed everything, but there are so many files to open idk which one to run.

After you installed setup.py and make ufonet executable

You can do this command:

```
python3 ufonet -h (to view all command list)
python3 ufonet --examples (to view command examples)
python3 ufonet --gui (to go web gui, you need to refresh your refresh your browser alot to make it work tho)
```

**Comment by muppley** [comment]
have you tested all of these and made sure they worked?

**Comment by MiChaelinzo** [comment]
> have you tested all of these and made sure they worked?

I wouldn't be commenting this if I didn't

**Comment by MiChaelinzo** [comment]
It all worked for me just fine etc.

**Comment by muppley** [comment]
one more thing. when i run the starting command it says:
/usr/bin/python3: can't find '__main__' module in 'ufonet'

how do i fix

**Comment by epsylon** [comment]
@muppley something goes wrong with your path. 
Try to clone again the tool and install it following this: https://ufonet.03c8.net/#installation
