### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by GreyHat2** [epsylon/ufonet#277]
When i run ufonet i get this error ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

**Comment by MiChaelinzo** [comment]
$ sudo pip3 show numpy 
If there is nothing do:
$ sudo pip3 install numpy 
If there is do:
$ sudo pip3 install --upgrade numpy

**Comment by GreyHat2** [comment]
> $ sudo pip3 show numpy
> If there is nothing do:
> $ sudo pip3 install numpy
> If there is do:
> $ sudo pip3 install --upgrade numpy

pip3 show numpy says i have numpy installed
