### ISSUE TITLE
Regrading The Web Gui

### ISSUE THREAD

**Issue by SmokinSpectre** [epsylon/ufonet#278]
Hey @epsylon I Just Installed Ufonet And I Use It To Simulate Attacks On My Server But The Thing Is I Want To Use The GUI Of Ufonet But I Cant Use It As I Am Using Ssh To Connect To My Web Server Where Ufonet Is Installed And The _**Gui Gets Hosted On The Local Host Address Of My Machine**_ That Is Accessible To Me Only From The Web Browser In My Machine But As **_**Ubuntu Server Is All CLI Based And Has No Browser In It**_** I Can't Use It Is There Any Way So That **_I Can Use My Home Server Ip Address To Host The GUI_** In Whenever I Would Need To Use It ??

Thanks

**Comment by epsylon** [comment]
Hi @SmokinSpectre, you can try to use the GUI by using different solutions; First one, can be to attach to your SSH connection a X lib (x-server/X-Fordwarding) using a tunnel and manage that machine (an run the GUI) remotely. As for example, Putty.
Another solution is to make the GUI listen, not at localhost (127.0.0.1) but at the LAN IP of the machine, and if you are in the local network, run it from another ip to the ip of the machine (ex: 192.168.1.56:9999). For that you need to edit the code (located at: webgui.py) and change it. Or even NAT and after access it, from a external network.

**Comment by SmokinSpectre** [comment]
Hey thanks for your quick reply i read the code and found a lot of mentions for the localhost address( 127.0.0.1 ) also i found this particular line **host = "0.0.0.0"
                     port = 9999**
so am i supposed to change only this line or change all the lines where 127.0.0.1 is mentioned to my own internal ip address ??

**Comment by epsylon** [comment]
```
./core/main.py -> host = '0.0.0.0' -> line: 3086
./core/webgui.py -> host = "0.0.0.0" -> line: 50
```
