### ISSUE TITLE
GUI ERROR 

### ISSUE THREAD

**Issue by ov1faruk** [epsylon/ufonet#279]
I am running on kali linux and whenever I try "python3 ufonet --gui" it shows the following errors : 

Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/home/ov1faruk/ufonet/core/main.py", line 346, in run
    self.start_ship_engine()
  File "/home/ov1faruk/ufonet/core/main.py", line 330, in start_ship_engine
    self.update_flying_stats() # update flying time stats
  File "/home/ov1faruk/ufonet/core/main.py", line 1515, in update_flying_stats
    stats_json_file = open(self.mothership_stats_file, "w+")
PermissionError: [Errno 13] Permission denied: 'core/json/stats.json'

( I tried to type http://127.0.0.1:9999/ manually on the browser , it doesn't work either , any solution ? )

**Comment by epsylon** [comment]
@ov1faruk there is something wrong on your folder permissions:

`PermissionError: [Errno 13] Permission denied: 'core/json/stats.json'`

Try to change them, for example, using this way:

**1) cd /home/ov1faruk
2) sudo chmod -R 775 ufonet/**

**Comment by ov1faruk** [comment]
So what I did , 
"opened my terminal and did
cd /home/ov1faruk 
then 
sudo chmod -R 775 ufonet/" 

but the same issue exists. :( 

***Thanks for the fast reply***

**Comment by epsylon** [comment]
@ov1faruk ok, try to understand the issue, firstly. You need to change the permissions of the folder, to execute it (but also to save some files). 

This can be done using different ways; right click on your dekstop, via terminal, etc...

ex:

sudo chown -R ov1faruk:ov1faruk path.to.ufonet -> _sudo chown -R ov1faruk:ov1faruk /home/ov1faruk/ufonet_
sudo chmod -R 775 path.to.ufonet -> _sudo chmod -R 775 /home/ov1faruk/ufonet_

another solution, is just removing 'stats' folder (don't worry, it will be auto-regenerate when you execute UFONet again) but also remember that this will delete permanetly your stats:

**rm -r core/json/**

**Comment by ov1faruk** [comment]
Man! Thanks a lot! this helped and you also made me understood the issue. 
gui working smooth.
***(respect)***
