### ISSUE TITLE
Nothing Happening To My Test Site

### ISSUE THREAD

**Issue by expiredcat** [epsylon/ufonet#280]
Hi there, I tried ufonet on my webserver(which I test these stuff) to test ufonet if it was working well, but it seems not. My webserver is totally unprotected, and it is accessible from the web. My stats are like this
![Stats](https://user-images.githubusercontent.com/57807810/97591450-8b52ad80-19f7-11eb-94e5-c44ca904501b.png)
but nothing happens to my webserver, it doesn't even slow down! Any Solutions?

**Comment by dontbanmeplz** [comment]
Get more bots
It’s the only way

**Comment by nekologist** [comment]
How? I downloaded all the bots I can with auto search and --zombie-download or something like that

**Comment by deeshirazi** [comment]
> How? I downloaded all the bots I can with auto search and --zombie-download or something like that

1) python3 ufonet
2) python3 ufonet --help
3) check your options you will see download bots from t.ex community or github etc
4) chose which one you want download from( i would choose the community)
5) python3 ufonet --download-(from whereever you want to dolwnload) 
6) pyrhon3 ufonet --gui (you will see bots there too and just run the program from there!
I guess! I hope it helps

**Comment by pcouy** [comment]
I actually think this "tool" is a trap. It makes you believe that it can automatically enroll hundreds of bots for you from a simple Google search. I won't go into the details of why it is unrealistic, but it is.

Then it mixes up "Open redirect" (which it actually uses but is of no use when trying to perform a DDoS) and "SSRF" (which could actually be used for a DDoS).

I suspect that the users of this software (who think they are enrolling bots in their own attacks) are actually being enrolled as the bots of @epsylon 's own botnet.

**Comment by epsylon** [comment]
@pcouy If your idea of evaluating a free software tool, in which you can check the code yourself, or whose network traffic you can check with other tools such as Ettercap or Wireshark, to really see how it works is to say that "you think that" and accusing its creator of using it to manipulate people, what you really show is that you are quite a loser ... Or that you speak without having a clue. Even how complex it is to do a DDoS and how much the tool makes it easier to launch it efficiently. 

Without a doubt, you are a troll, but don't worry, the Community behind UFONet knows perfectly what the tool is like or even that its creator has been involved in certain developments for more than 15 years, all of them, by the way, free, gratis and with the idea of empowering the people
..

Stop fooling around and learn to read code ... Or create your own UFONet botnet and check how network packets are sent, or how the whole toolkit is working. 

But above all, don't waste my time responding to stupid things.

**Comment by pcouy** [comment]
Any remotely technical question asked here gets answered with the same condescending tone and no real answer. How do you expect to be taken seriously ?

Even if your tool actually performed the function you pretend it does, you would be enabling any script kiddie to launch DDoS attacks with absolutely no skill required. This would make this software a huge topic in the infosec community, which is not. Nobody remotely serious about infosec ever mentionned UFONet anywhere. Why is that so ?

As for your comment about learning to read code, I did actually read some part of it and it really seems like when you provide your _users_ with a list of _zombies_ through your _mothership_, you are in fact delivering a list of _targets_ to your _victims_ who unknowingly take part in your own botnet thourgh a _command and control server_. Anyway, I have better things to do than spend a whole day trying to read your spaghetti code.

You mention the Community (with a capital C) but the only content I'm able to find online about this software is directly published by yourself, or copy pasted from your website.

**Comment by epsylon** [comment]
@pcouy It is not within my time options to respond to little vermin like you. In fact, don't feed the troll is definitely good advice. But it makes me laugh how good a vigilante you are, that you come here with various nonsense typical of someone who has no idea of computer security, it seems, that to save the rest of the user from my evil. Dont have other thing that does?. You can open your own project and leave the rest to remain alone. Or is it that you are an attention-seeking hater, because among other things, you have nothing interesting to show to the rest? I give condescending answers, but you ask idiotic questions. ;-)

If you want to play trolls, I warn you, things can go quite bad for you, my ass is already bare...

Anyway, I'm not going to give you a chance to get some fame. Go back to your code repository, to keep making a fool of yourself, I have other things to do. And if you don't, you will be blocked. 

Capicci? ;-)

**Comment by pcouy** [comment]
> If you want to play trolls, I warn you, things can go quite bad for you, my ass is already bare...

Is this a threat ?

**Comment by dontbanmeplz** [comment]
Yes it is me has banned me before and he will ban you
