### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by Kid-Joe** [epsylon/ufonet#282]
1.issue -when i doing attack all of url become FIALED cannot connect 
2 issue-nuke is not working

**Comment by Kid-Joe** [comment]
and can you include new zombies please

**Comment by epsylon** [comment]
@Kid-Joe you have the tools to include new zombies (but also to exclude broken zombies), just need to play a bit with it... this is a user TO-DO task.

**Comment by epsylon** [comment]
_2 issue-nuke is not working_ -> I have seen "nuke" working at TCP layer (analyzing traffic). Do you have any clues to confirm that affirmation or is just your impression?
