### ISSUE TITLE
Newbie Here!

### ISSUE THREAD

**Issue by deeshirazi** [epsylon/ufonet#285]
Hello friends!

Can someone PLEASE just write down what i should write inside the CMD (Windows) to get Ufonet started? I am stack at cd ./ufonet and after that nada... in 2 days i have tried ./ufonet.py, ./ufonet.python, .python ./ufonet.py etc and nothing happens! Just write down those lines that i have to write inside the command prompt please! I have to learn this, it´s very important! I am not trying to boot someone to have fun no, i am trying to do something positive for my people who are suffering in my country back home!

**Comment by dontbanmeplz** [comment]
Tbh this isn't meant for windows. If you want to do something positive for family at home, learn python or write a website to share with them. A booting website is not something i would see as positive.

**Comment by deeshirazi** [comment]
> 
> 
> Tbh this isn't meant for windows. If you want to do something positive for family at home, learn python or write a website to share with them. A booting website is not something i would see as positive.

you didn´t get my point, but never mind, i am not trying to learn the whole programing in python, and Ufonet is working on windows too! I just don´t know how to start it and i need help!

**Comment by dontbanmeplz** [comment]
python3 unfonet

**Comment by deeshirazi** [comment]
> 
> 
> python3 unfonet
Tried but it does not work my friend! 
Python3 is not a recognized as an internal or external command!
I have python, pip and all of that installed but does not work!

**Comment by epsylon** [comment]
@deeshirazi this is happening because the windows shell isn't a *UNIX shell. You can use a PoweShell to simulate that, or other methods. Also, if you have Python3 installed at you Win32, you can try to run it like this:

**Python3.exe ufonet**

**Comment by deeshirazi** [comment]
> @deeshirazi this is happening because the windows shell isn't a *UNIX shell. You can use a PoweShell to simulate that, or other methods. Also, if you have Python3 installed at you Win32, you can try to run it like this:
> 
> **Python3.exe ufonet**

thanks bro, you were right, i just created a Ubuntu VM and everything worked just well! :) But the Tor browser does not work!

**Comment by epsylon** [comment]
@deeshirazi Tor Browser is working... Maybe you should allow it to visit local networks (such as: 127.0.0.1). You can verify that is working on different videos from Media section at UFONet website: https://ufonet.03c8.net/#media
