### ISSUE TITLE
MacOs Pycurl Not Working

### ISSUE THREAD

**Issue by RocketNinja15** [epsylon/ufonet#289]
Hello!

On macOS, I have installed pycurl multiple times, but every time I run ufonet, It says

Error importing: pycurl lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-pycurl'

it says I have pycurl, when I try to reinstall it, but It isn't finding it.

**Comment by epsylon** [comment]
@RocketNinja15 try to use pip3... 

ex: **pip3 search pycurl**
pycurl (7.43.0.6)           - PycURL -- A Python Interface To The cURL library
  INSTALLED: 7.43.0.5
  LATEST:    7.43.0.6
