### ISSUE TITLE
Geoip.h 

### ISSUE THREAD

**Issue by RocketNinja15** [epsylon/ufonet#290]
py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found
#include "GeoIP.h"

This happens when I run the setup as a root user.

**Comment by epsylon** [comment]
@RocketNinja15 you need to install **python-geoip** and **pygeoip**. I recommend you to use pip3

ex: pip3 search geoip

python-geoip (1.2)    - Provides GeoIP functionality for  Python.
  INSTALLED: 1.2 (latest)
pygeoip (0.3.2)          - Pure Python GeoIP API
  INSTALLED: 0.3.2 (latest)

**Comment by epsylon** [comment]
To fix this error:

sudo apt-get install python3-geoip libgeoip-dev libgeoip1
