### ISSUE TITLE
Error when attacking..

### ISSUE THREAD

**Issue by wooilok123** [epsylon/ufonet#293]
![botner](https://user-images.githubusercontent.com/68337442/102119964-dd06a880-3e7c-11eb-8ac2-402cc8806ecd.JPG)
Hi , Im having this error while attacking, also I tried sending 100 attacks to the website it still not going down. Is it possible that firewall has filtered these attacks ?

**Comment by epsylon** [comment]
@wooilok123 this is because you are opening so many threads. Sometimes OS cannot manage them propertly. Try to clean your botnet from failing zombies and to control the number of threads using: **--threads**

**Comment by wooilok123** [comment]
Helo, may i know how to find out and remove failed bots?
Also really love this tool , easy  to use and effective ! well done
[image: image.png]

**Comment by epsylon** [comment]
@wooilok123 for zombies related to HTTP/Layer7 you can try: **ufonet --test botnet/zombies.txt**
