### ISSUE TITLE
Tor!

### ISSUE THREAD

**Issue by deeshirazi** [epsylon/ufonet#296]
Hello!
This command starts the Gui but am i starting the Gui via Tor?

python3 ufonet --proxy http://127.0.0.1:9050 --gui

And everything is working perfect but i am not sure if i am on the web gui via Tor gateways or not! And before i start the Gui i check for Tor python3 ufonet --check-tor and it says the Tor is not ser correctly or something like that!

Could someone please help?

**Comment by epsylon** [comment]
@deeshirazi [Guide] Installing Tor With Privoxy: https://darkweblinks.org/2018/08/10/guide-installing-tor-with-privoxy/
