### ISSUE TITLE
Syntax warning and Crypto

### ISSUE THREAD

**Issue by uyeet** [epsylon/ufonet#298]
/home/portalnugget/ufonet/core/main.py:3325: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if url_link not in zombies and url_link+os.linesep not in zombies_found and url_link is not "": # AI mode (parsing search engines mixed pool and stored army)

          ||          /\        ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||      *~~~~~~~~*    ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-          (0)  XX  (0)           -(00)-  ||                                             ||
   ||             \| (00) |/              ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||     |-> DROIDS     #     |-> LORIS          ||
            |  |.''.( xx ).''.|  |              ||     |-> ALIENS     #     |-> UFOSYN         ||
            .'.'   X|'..'|X   '.'.              ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
    | '###  |  =| | ###### | |=  |' ###  |      ||     |-> FRAGGLE    #     |-> UFOUDP         ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||     |-> SNIPER     #                        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||                                             ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       #|=============================================|#
    .'_.-|            YY            |-._'.      ||                                             ||
                                                ||  -> [ UFONet: https://ufonet.03c8.net ] <-  ||
    + Class: PSYoPs / ViPR404+ (model I^) +     ||                                             ||
                                                #|=============================================|#

/home/portalnugget/ufonet/core/webgui.py:2229: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_target_dec is not "":
/home/portalnugget/ufonet/core/webgui.py:2378: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 0: # not any data (or decryption allowed) on grid so discard
/home/portalnugget/ufonet/core/webgui.py:2380: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 1: # add this player as a rookie
/home/portalnugget/ufonet/core/webgui.py:2383: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 2: # add this player as a mercenary
/home/portalnugget/ufonet/core/webgui.py:2386: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 3: # add this player as a bandit
/home/portalnugget/ufonet/core/webgui.py:2389: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 4: # add this player as a ufommander
/home/portalnugget/ufonet/core/webgui.py:2392: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 5: # add this player as a ufoleet
/home/portalnugget/ufonet/core/webgui.py:4229: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/portalnugget/ufonet/core/webgui.py:4256: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not "":
/home/portalnugget/ufonet/core/webgui.py:4335: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/portalnugget/ufonet/core/webgui.py:4397: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/home/portalnugget/ufonet/core/webgui.py:5508: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # stream creation + encryption + package send
/home/portalnugget/ufonet/core/webgui.py:5719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_enckey is not "": # stream creation + encryption + package send
/home/portalnugget/ufonet/core/webgui.py:5785: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_enckey is not "": # stream creation + encryption + package send
/home/portalnugget/ufonet/core/webgui.py:5849: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_enckey is not "": # stream creation + encryption + package send
/home/portalnugget/ufonet/core/webgui.py:5920: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_enckey is not "": # stream creation + encryption + package send
/home/portalnugget/ufonet/core/webgui.py:6010: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/portalnugget/ufonet/core/webgui.py:6010: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/portalnugget/ufonet/core/webgui.py:6010: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/home/portalnugget/ufonet/core/webgui.py:6080: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if news_key is not "": # news decryption
/home/portalnugget/ufonet/core/webgui.py:6102: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if missions_key is not "": # missions decryption
/home/portalnugget/ufonet/core/webgui.py:6209: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "": # board decryption
/home/portalnugget/ufonet/core/webgui.py:6288: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # grid decryption
/home/portalnugget/ufonet/core/webgui.py:7040: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_deckey is not "": # wargames decryption
/home/portalnugget/ufonet/core/webgui.py:7184: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_deckey is not "": # links decryption
/home/portalnugget/ufonet/core/webgui.py:7234: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_deckey is not "": # streams decryption
/home/portalnugget/ufonet/core/webgui.py:7288: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_deckey is not "": # globalnet decryption
Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/home/portalnugget/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/home/portalnugget/ufonet/core/main.py", line 3084, in create_web_interface
    from .webgui import ClientThread
  File "/home/portalnugget/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/home/portalnugget/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by uyeet** [comment]
I also have installed the "crypto" Module

**Comment by epsylon** [comment]
@uyeet -> **sudo apt-get install python3-crypto**

If doesn't work, try also to install it using pip -> **pip3 install pycrypto**
