### ISSUE TITLE
./ufonet --gui Throws connection reset on bash on windows

### ISSUE THREAD

**Issue by Thecakeisgit** [epsylon/ufonet#30]
When i <code>./ufonet --gui</code> and i go to Firefox and enter http://127.0.0.1:9999, i get a connection reset !
The program just say this:
```
root@(none):~/ufonet# ./ufonet --gui
w3m: Can't load http://127.0.0.1:9999.
w3m: Can't load http://127.0.0.1:9999.
```

**Comment by epsylon** [comment]
Strange...You shouldn't need to enter url: http://127.0.0.1:9999 by manually. 
Did you wait for UFONet to open GUI automatically?. 
It takes just a couple of seconds at some configuration machines. Is you are using a VM, probably it takes a bit more of time or can be more slow.

**Comment by Thecakeisgit** [comment]
I'm on windows, so there is a new bash emulator, fruit of Microsoft + Canonical union, and the shell is not really good implemented, and you can't run gui app ^^ So i just tried to lauch ufonet from bash and to access it from windows.
I got a Lunix partition and it works correctly ^^ so idk what it is..
@epsylon

**Comment by epsylon** [comment]
Perfect. Thanks for your report.
