### ISSUE TITLE
Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe'

### ISSUE THREAD

**Issue by root-debug-hub** [epsylon/ufonet#302]
I've been trying to fix it for two days.
All forums 
looked
`Installed c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\ufonet-1.6-py3.8.egg
Processing dependencies for ufonet==1.6
Searching for pycrypto>=2.6.1
Reading https://pypi.org/simple/pycrypto/
Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#sha256=f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1.tar.gz
Writing C:\Users\admin\AppData\Local\Temp\easy_install-upk1u6x7\pycrypto-2.6.1\setup.cfg
Running pycrypto-2.6.1\setup.py -q bdist_egg --dist-dir C:\Users\admin\AppData\Local\Temp\easy_install-upk1u6x7\pycrypto-2.6.1\egg-dist-tmp-_cmb0ryo
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
winrand.c
c:\users\admin\appdata\local\programs\python\python38\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

C:\Users\admin\Desktop\ufonet-master>c:\users\admin\appdata\local\programs\python\python38\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

**Comment by epsylon** [comment]
@root-debug-hub -> https://stackoverflow.com/questions/17319033/fixing-warning-gmp-or-mpir-library-not-found-not-building-crypto-publickkey
