### ISSUE TITLE
Ufonet 

### ISSUE THREAD

**Issue by luis19924** [epsylon/ufonet#305]
Trato de abrir ufonet en kali pero me sale este error, ya no se que hacer. Me podrían ayudar
Traceback (most recent call last):
  File "/root/ufonet/ufonet", line 16, in <module>
    app.run()
  File "/root/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/root/ufonet/core/main.py", line 3084, in create_web_interface
    from .webgui import ClientThread
  File "/root/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/root/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by epsylon** [comment]
You can automatically get all required libraries using (**as root**):

     **python3 setup.py install**

For manual installation on Debian-based systems (ex: Ubuntu), run: 

     **sudo apt-get install** python3-pycurl python3-geoip python3-whois **python3-crypto** python3-requests python3-scapy libgeoip1 libgeoip-dev

On other systems such as: Kali, Ubuntu, ArchLinux, ParrotSec, Fedora, etc... also run:
 
     pip3 install GeoIP
     pip3 install python-geoip
     pip3 install pygeoip
     pip3 install requests
     **pip3 install pycrypto**
     pip3 install pycurl
     pip3 install whois
     pip3 install scapy-python3
