### ISSUE TITLE
Got an error because GeoIP

### ISSUE THREAD

**Issue by mrchoppa030** [epsylon/ufonet#307]
Cant install Ufonet bc: 
`Warning: 'classifiers' should be a list, got type 'tuple'
warning: no files found matching 'ChangeLog'
py_GeoIP.c:23:10: fatal error: GeoIP.h: File or directory not found
   23 | #include "GeoIP.h"`
I tried to install it manually but didnt worked:
`$ python3 geoip
python3: can't open file '/root/ufonet/geoip': [Errno 2] No such file or directory
`
after that, i tried this:
`$ pip install GeoIP`
`Collecting GeoIP
  Using cached GeoIP-1.3.2.tar.gz (20 kB)
Building wheels for collected packages: GeoIP
  Building wheel for GeoIP (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3v1q4bmx                                                                                                                  
       cwd: /tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/                                      
  Complete output (15 lines):                                                                                      
  /usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'               
    warnings.warn(msg)                                                                                             
  Warning: 'classifiers' should be a list, got type 'tuple'                                                        
  running bdist_wheel                                                                                              
  running build                                                                                                    
  running build_ext                                                                                                
  building 'GeoIP' extension                                                                                       
  creating build                                                                                                   
  creating build/temp.linux-x86_64-3.9                                                                             
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c py_GeoIP.c -o build/temp.linux-x86_64-3.9/py_GeoIP.o                                                                                                        
  py_GeoIP.c:23:10: fatal error: GeoIP.h: Datei oder Verzeichnis nicht gefunden                                    
     23 | #include "GeoIP.h"                                                                                       
        |          ^~~~~~~~~                                                                                       
  compilation terminated.                                                                                          
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1                                           
  ----------------------------------------                                                                         
  ERROR: Failed building wheel for GeoIP
  Running setup.py clean for GeoIP
Failed to build GeoIP
Installing collected packages: GeoIP
    Running setup.py install for GeoIP ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9euagf6d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/GeoIP                                                                                                          
         cwd: /tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/                                    
    Complete output (15 lines):                                                                                    
    /usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'             
      warnings.warn(msg)                                                                                           
    Warning: 'classifiers' should be a list, got type 'tuple'                                                      
    running install                                                                                                
    running build                                                                                                  
    running build_ext                                                                                              
    building 'GeoIP' extension                                                                                     
    creating build                                                                                                 
    creating build/temp.linux-x86_64-3.9                                                                           
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c py_GeoIP.c -o build/temp.linux-x86_64-3.9/py_GeoIP.o                                                                                                      
    py_GeoIP.c:23:10: fatal error: GeoIP.h: Datei oder Verzeichnis nicht gefunden                                  
       23 | #include "GeoIP.h"                                                                                     
          |          ^~~~~~~~~                                                                                     
    compilation terminated.                                                                                        
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1                                         
    ----------------------------------------                                                                       
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ywtk43o3/geoip_0fe617f7266b417382b1506a9ab28760/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9euagf6d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/GeoIP Check the logs for full command output. `

pls help (oh and btw, i dont know the rules of github. if this is the wrong place to ask questions than sorry)

**Comment by epsylon** [comment]
@mrchoppa030 -> https://ufonet.03c8.net/#installation

```
I tried to install it manually but didnt worked:
$ python3 geoip python3: can't open file '/root/ufonet/geoip': [Errno 2] No such file or directory 
```

You have syntax errors. This command should be:

**sudo pip3 install GeoIP**

```
py_GeoIP.c:23:10: fatal error: GeoIP.h: Datei oder Verzeichnis nicht gefunden
23 | #include "GeoIP.h"
```

FIX:
1) **sudo apt-get install libgeoip1 libgeoip-dev**
2) **sudo python3 setup.py install**

**Comment by Bhayou** [comment]
Thanks bro
