### ISSUE TITLE
Improvement: Config file for gui.

### ISSUE THREAD

**Issue by Thecakeisgit** [epsylon/ufonet#31]
You could also make a json config file to configure port, host, etc... It can be useful :D 
```
{
  host: '0.0.0.0',
  port: '9999',
  foo: 'bar'
}
```

**Comment by epsylon** [comment]
I will... now is just using variables on code because not so many people try to changes it. But you have reason, if you want to do it, is more easy from a file so, is a detail than can be easly added to next release.
Thanks for you suggestion ;-)
