### ISSUE TITLE
gui mode wont run

### ISSUE THREAD

**Issue by Gnomex007** [epsylon/ufonet#314]
after few day im use Ufonet for my assignment.. im cant run in guii mode.. thanks...

**Comment by Gnomex007** [comment]
sudo python3 ufonet --gui                                                                                                                      130 ⨯

          ||          /\        ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||      *~~~~~~~~*    ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-          (0)  XX  (0)           -(00)-  ||                                             ||
   ||             \| (00) |/              ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||     |-> DROIDS     #     |-> LORIS          ||
            |  |.''.( xx ).''.|  |              ||     |-> ALIENS     #     |-> UFOSYN         ||
            .'.'   X|'..'|X   '.'.              ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
    | '###  |  =| | ###### | |=  |' ###  |      ||     |-> FRAGGLE    #     |-> UFOUDP         ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||     |-> SNIPER     #                        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||                                             ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       #|=============================================|#
    .'_.-|            YY            |-._'.      ||                                             ||
                                                ||  -> [ UFONet: https://ufonet.03c8.net ] <-  ||
    + Class: PSYoPs / ViPR404+ (model I^) +     ||                                             ||
                                                #|=============================================|#


just stuck like that. browser wont run.. dunno why

**Comment by epsylon** [comment]
@Gnomex007 **you don't need to run it as root**... probably because of that your browser is not working. Try without it:

**python3 ufonet --gui** 

Also, after run it, try to open a browser manually and visit this url: **http://127.0.0.1:9999**
