### ISSUE TITLE
help pless

### ISSUE THREAD

**Issue by Up7951** [epsylon/ufonet#315]
||          /\        ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||      *~~~~~~~~*    ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-          (0)  XX  (0)           -(00)-  ||                                             ||
   ||             \| (00) |/              ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||     |-> DROIDS     #     |-> LORIS          ||
            |  |.''.( xx ).''.|  |              ||     |-> ALIENS     #     |-> UFOSYN         ||
            .'.'   X|'..'|X   '.'.              ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
    | '###  |  =| | ###### | |=  |' ###  |      ||     |-> FRAGGLE    #     |-> UFOUDP         ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||     |-> SNIPER     #                        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||                                             ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       #|=============================================|#
    .'_.-|            YY            |-._'.      ||                                             ||
                                                ||  -> [ UFONet: https://ufonet.03c8.net ] <-  ||
    + Class: PSYoPs / ViPR404+ (model I^) +     ||                                             ||
                                                #|=============================================|#

=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OFF)ensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

[AI] Initiating void generation sequence...

======================

[Error] [AI] Not 'abductions.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'troops.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'robots.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'drones.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'reflectors.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'warps.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'crystals.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'bosons.txt.gz' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'abductions' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'troops' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'robots' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'drones' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'reflectors' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'warps' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'crystals' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'bosons' file in /var/www/ufonet/

[Error] [AI] Cannot found any container... -> [Aborting!]

[Info] [AI] Suspend [Blackhole] with: Ctrl+z

**Comment by epsylon** [comment]
@Up7951 To run a grider at your machine to work as a server, is a bit complex task, so first read this: https://github.com/epsylon/ufonet/blob/master/docs/README_grider.txt

You are having a **permission problem** -> _[Error] [AI] Write access denied for..._

Try to solve that
