### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sjonks** [epsylon/ufonet#317]
I am on MacOS and when I do ./ufonet it says:
zsh: permission denied: ./ufonet

**Comment by sjonks** [comment]
Also, I have having trouble installing GeoIP

#include <GeoIP.h>
         ^~~~~~~~~
         "GeoIP.h"
/Users/[REDACTED]/ufonet/geoip-api-python/py_GeoIP.c:24:10: fatal error: 
      'GeoIPCity.h' file not found
#include <GeoIPCity.h>

**Comment by epsylon** [comment]
@sjonks -> https://github.com/epsylon/ufonet/issues/307#issuecomment-806486727
