### ISSUE TITLE
Can't download zombies.

### ISSUE THREAD

**Issue by InsaneGal** [epsylon/ufonet#318]
Every time I try to download zombies I just get this:

`[AI] Trying [Blackhole] [Server]: 176.28.23.46

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Info] [AI] You can try to download [Zombies] from a different [Blackhole] [Server] (provided by someone!) with:

 ex: ufonet --down-from '<IP>'

Or/And from a [Blackhole] [GitHub] with:

 ex: ufonet --download-github
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

`

Is my IP blocked or something?

**Comment by epsylon** [comment]
@InsaneGal yep, probably your IP has been firewalled... Some others have report to me that they can connect... Remember that this server is not replying to ICMP pings. Btw, If you haven't done any suspicious activity, it will be unbanned soon. 

Try it again after some hours..

Many thanks!
