### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [epsylon/ufonet#320]
Hello,

When I execute this script I have this error

```
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25bc' in position 3: ordinal not in range(256)

```

I have seen inside the script that the option " # -*- coding: utf-8 -*- " is but I don't know what is the problem.

A greeting and thanks

**Comment by epsylon** [comment]
@tXambe your environment isn't supporting UTF-8... try to fix that!
