### ISSUE TITLE
installation issues, ive installed everything requested and stll getting error/ directory issues 

### ISSUE THREAD

**Issue by NotAnAlienz** [epsylon/ufonet#321]
python3 setup.py install

/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't open file '/Users/epalpa/setup.py': [Errno 2] No such file or directory
epalpa@Brons-MacBook-Pro ~ %

**Comment by Aholicknight** [comment]
did you run the setup.py as sudo?

**Comment by NotAnAlienz** [comment]
> did you run the setup.py as sudo?

ive tried sudo and brew and still get directory issues. Does it work on mac?

**Comment by NotAnAlienz** [comment]
epalpa@Brons-MacBook-Pro ~ %        pip3 install GeoIP

Collecting GeoIP
  Using cached GeoIP-1.3.2.tar.gz (20 kB)
Using legacy 'setup.py install' for GeoIP, since package 'wheel' is not installed.
Installing collected packages: GeoIP
    Running setup.py install for GeoIP ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-install-7vb9alzy/geoip_08e3838452bd434483112299cb1d0333/setup.py'"'"'; __file__='"'"'/private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-install-7vb9alzy/geoip_08e3838452bd434483112299cb1d0333/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-record-h2il_2fd/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/GeoIP
         cwd: /private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-install-7vb9alzy/geoip_08e3838452bd434483112299cb1d0333/
    Complete output (15 lines):
    /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.9
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c py_GeoIP.c -o build/temp.macosx-10.9-x86_64-3.9/py_GeoIP.o
    py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found
    #include "GeoIP.h"
             ^~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-install-7vb9alzy/geoip_08e3838452bd434483112299cb1d0333/setup.py'"'"'; __file__='"'"'/private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-install-7vb9alzy/geoip_08e3838452bd434483112299cb1d0333/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d4/yl5hmx7j4z35b9z976vd3pf40000gn/T/pip-record-h2il_2fd/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/GeoIP Check the logs for full command output.

Maybe the issue stems from my troubles installing GeoIP? its the only package i cant get atm

**Comment by epsylon** [comment]
@NotAnAlienz this GeoIP error can be fixed, if you also install this libraries: 

 **libgeoip-dev** - Development files for the GeoIP library
 **libgeoip1** - non-DNS IP-to-country resolver library

**Comment by NotAnAlienz** [comment]
brew install libgeoip-dev
Updating Homebrew...
Warning: No available formula or cask with the name "libgeoip-dev". Did you mean libgtop?
==> Searching for similarly named formulae...
This similarly named formula was found:
libgtop ✔
To install it, run:
  brew install libgtop ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
epalpa@Brons-MacBook-Pro ~ %

**Comment by epsylon** [comment]
@NotAnAlienz brew install geoip ?

**Comment by NotAnAlienz** [comment]
GeoIp installed with brew, but running "python3 setup.py install" i still get

 epalpa@Brons-MacBook-Pro ~ % python3 setup.py install

/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't open file '/Users/epalpa/setup.py': [Errno 2] No such file or directory
epalpa@Brons-MacBook-Pro ~ % 

is there a specific install i should use for mac?

**Comment by Aholicknight** [comment]
I don't think I ever saw UFONet run on a mac before, so your best bet is probably installing a kali vm and installing UFONet on that

**Comment by NotAnAlienz** [comment]
> I don't think I ever saw UFONet run on a mac before, so your best bet is probably installing a kali vm and installing UFONet on that

hm, do you know any good kits like ufonet for mac?

**Comment by Aholicknight** [comment]
not my problem

**Comment by NotAnAlienz** [comment]
lol ok, ill make my own then

**Comment by epsylon** [comment]
@NotAnAlienz sorry but we haven't any guide related to macosx... try to researh (and maybe write one) it by yourself.
