### ISSUE TITLE
Targets are always offline

### ISSUE THREAD

**Issue by Chris-ml17** [epsylon/ufonet#323]
every target i try attacking is always offline, the abduction function works normally and is able to assess the target but when i attack it's always offline. I am running it through the web gui

**Comment by Marios1231** [comment]
me too its reall annoying

**Comment by epsylon** [comment]
@Chris-ml17 @Marios1231 Can some of you guys write this template with a more detailed explanation of the issue?

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Marios1231** [comment]
> @Chris-ml17 @Marios1231 Can some of you guys write this template with a more detailed explanation of the issue?
> 
> https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

okay I ran the GUI i went to the website I went to attack and then set my target I didn't set a place to attack number of rounds was 1 and maps and extras are not selected, when I run it I get this 

https://pastebin.com/iEQ02GzY 
thank you

**Comment by epsylon** [comment]
hey @Marios1231, take a look to your target (provided with the url to pastebin). This url is malformed: **https://%20%20**

**Comment by Marios1231** [comment]
> hey @Marios1231, take a look to your target (provided with the url to pastebin). This url is malformed: **https://%20%20**

My target is normal but it becomes like %20%20** by itself I don't know how I put normal https://example.com and it switches by it self to https://%20%20

**Comment by epsylon** [comment]
@Marios1231 Sorry, but your bug cannot be reproduced. The ticket will be closed.

**Comment by hjawadwala** [comment]
> > hey @Marios1231, take a look to your target (provided with the url to pastebin). This url is malformed: **https://%20%20**
> 
> My target is normal but it becomes like %20%20** by itself I don't know how I put normal https://example.com and it switches by it self to https://%20%20

same here. the target gets %20%20 added after http://

**Comment by hjawadwala** [comment]
> > hey @Marios1231, take a look to your target (provided with the url to pastebin). This url is malformed: **https://%20%20**
> 
> My target is normal but it becomes like %20%20** by itself I don't know how I put normal https://example.com and it switches by it self to https://%20%20

try 
http:[IP] don't put // . it worked for me :)

**Comment by epsylon** [comment]
OK!. You are right. I have seen the bug...let me patch it

**Comment by epsylon** [comment]
should be fixed -> https://github.com/epsylon/ufonet/commit/985701eb7d0c0f66c39a9f5667ca1c4167308db8

**Comment by Marios1231** [comment]
> > > hey @Marios1231, take a look to your target (provided with the url to pastebin). This url is malformed: **https://%20%20**
> > 
> > My target is normal but it becomes like %20%20** by itself I don't know how I put normal https://example.com and it switches by it self to https://%20%20
> 
> same here. the target gets %20%20 added after http://

Thank you just saw it, it works
