### ISSUE TITLE
just a few questions 

### ISSUE THREAD

**Issue by undertaker8801** [epsylon/ufonet#324]
ok i see im getting the same issue as what some one else is getting when trying to do a attack through the gui i get this error it puts %20% twice before any ip i put in. then one other question when you click on show bnet on a map it shows like 1 every 4 secounds so for it to show a 1000 will take like a hour is it always that slow or is there away i can speed stuff up i have it on a good dedicated server. also its a grate programe just still trying to work things out

**Comment by undertaker8801** [comment]
ok so the way to fix if any one else asks it to remove the //  and it will not add the %20%

**Comment by undertaker8801** [comment]
is there anyway to make it attack harder it does like 1 server a secound insteading of lots at once

**Comment by epsylon** [comment]
@undertaker8801 real attack goes more faster/harder than map... it takes sometimes to resolve each IP for geolocation...

To make your attack more stronger, try to use "Extra Attacks"
