### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by jazxminemasters** [epsylon/ufonet#325]
im new and after installing  pip3 install GeoIP
   pip3 install python-geoip
   pip3 install pygeoip
   pip3 install requests
   pip3 install pycrypto
   pip3 install pycurl
   pip3 install whois
   pip3 install scapy-python3

what do i do next to open the ufonet (im on macos)

**Comment by epsylon** [comment]
@jazxminemasters -> _what do i do next to open the ufonet (im on macos)_ <- Sorry!. You should try it yourself and if you succeed, you can create a guide, because we do not have any related to macosx
