### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by AVEBOOM** [epsylon/ufonet#326]
when i run sudo apt-get install python3-crypto command i get 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-crypto' has no installation candidate

**Comment by AVEBOOM** [comment]
ive git cloned from the exact source and im always missing crypto

**Comment by epsylon** [comment]
@AVEBOOM -> https://ufonet.03c8.net/#installation -> **pip3 install pygeoip**
