### ISSUE TITLE
ufonet download-zombies error 

### ISSUE THREAD

**Issue by AVEBOOM** [epsylon/ufonet#327]
ive used the python3 ./ufonet --download-github and i get an error in the output still
![ufonet error](https://user-images.githubusercontent.com/87085807/127770430-c254af9b-f69f-46a9-8255-51d759142eed.PNG)

**Comment by epsylon** [comment]
@AVEBOOM this is related with the grider device... maybe your IP has been blocked or even the grider is temporaly unaccesible... just try it again and it should works!

**Comment by AVEBOOM** [comment]
ty

**Comment by Thewxtcher** [comment]
i aslo still have this error i have everything update and even debigged some code to include the latest python3 update also cgi is discontinued in a lib package thats 3.11 the latest is 3.13 thats why the cgi module does load but what i do nothing i do lets me use or download the zombies or anything else i bassically got its for looks right now untill it works properly

**Comment by Thewxtcher** [comment]
===========================================================================

888     888 8888888888 .d88888b.  888b    888          888
888     888 888        d88P Y888b 8888b   888          888
888     888 888       888     888 88888b  888          888
888     888 8888888   888     888 888Y88b 888  .d88b.  888888
888     888 888       888     888 888 Y88b888 d8P  Y8b 888
888     888 888       888     888 888  Y88888 88888888 888
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OFF)ensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)}

===========================================================================

[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

**Comment by Thewxtcher** [comment]
[AI] Downloading list of [Zombies] from [GitHub] server ...

======================

[AI] Trying [Blackhole] [GitHub]: https://raw.githubusercontent.com/epsylon/ufonet/master/botnet/

[AI] [Control] [Blackhole] [GitHub] Reply: [VORTEX READY!] ;-)
------------

[Info] Zombies: 1
[Info] Aliens : 1
[Info] Droids : 1
[Info] UCAVs  : 1
[Info] X-RPCs : 1
[Info] DNSs   : 1
[Info] NTPs   : 1
[Info] SNMPs  : 1

[Info] [AI] Congratulations!. Total downloaded: 8
------------

[AI] Do you want to merge ONLY the new 'troops' into your army? (Y/n)y
-------------------------

[Info] [AI] Botnet updated! -> ;-)
-------------------------

[AI] You would also like to update other content: [News] [Missions] [Grid] [Board]... (Y/n)y
-------------------------

[Error] [AI] Something wrong downloading GUI content! -> [Aborting!]
-------------------------

[AI] Generating random exit...

 -> Chao ab ordo!
