### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by dosekali** [epsylon/ufonet#332]
____                                                                        
          ||        / /\ \      ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||   O ==*~~~~~~*== 0 ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-          (0)  XX  (0)           -(00)-  ||                                             ||
   ||             \| (00) |/              ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||     |-> DROIDS     #     |-> LORIS          ||
            |  |.''.( xx ).''.|  |              ||     |-> ALIENS     #     |-> UFOSYN         ||
            .'.'   X|'..'|X   '.'.              ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
    | '###  |  =| | ###### | |=  |' ###  |      ||     |-> FRAGGLE    #     |-> UFOUDP         ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||     |-> SNIPER     #                        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||                                             ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       #|=============================================|#
    .'_.-|            YY            |-._'.      ||                                             ||
                                                ||  -> [ UFONet: https://ufonet.03c8.net ] <-  ||
   + Class: PSYoPs / ViPR404+/(model:I^3) +     ||                                             ||
                                                #|=============================================|#

Traceback (most recent call last):

        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

  File "/home/dose/ufonet/core/tools/ufoscan.py", line 15, in <module>
    from scapy.all import *
  File "/home/dose/.local/lib/python3.9/site-packages/scapy/all.py", line 5, in <module>
    raise Exception(msg)
Exception: 
        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dose/ufonet/ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/dose/ufonet/core/main.py", line 32, in <module>
    from core.tools.ufoscan import UFOSCAN
  File "/home/dose/ufonet/core/tools/ufoscan.py", line 18, in <module>
    sys.exit(2)
SystemExit: 2
>>> 
^C                                                                                                               
_____________________________________________________________________________________________________
I have done all installation without error but i get the above error once i run the Gui and click on UPDATE etc...CAN SOMEONE HELP ME OUT, maybe something is missing during my installation...
Thanks in advance..

**Comment by dosekali** [comment]
┌──(dose㉿Dose)-[~/ufonet]
└─$ sudo python3 setup.py install                                                                                                                                                           1 ⨯
[sudo] password for dose: 
running install
running bdist_egg
running egg_info
writing ufonet.egg-info/PKG-INFO
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
writing requirements to ufonet.egg-info/requires.txt
writing top-level names to ufonet.egg-info/top_level.txt
reading manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/crypter.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/grider.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/blackhole.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/zombie.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/update.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/webgui.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/commander.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien9.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien7.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien4.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien8.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien10.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien11.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien2.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien1.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien5.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien6.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien13.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien3.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien12.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/mothership.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link9.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link6.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link10.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link8.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link5.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link3.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link12.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link11.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link7.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link2.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link1.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link4.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/favicon.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/board.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/ufonet-logo.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/aliens.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/spaceinvaders.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jit.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/main.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/options.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/monlist.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/fraggle.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/uforst.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/droper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoack.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/pinger.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoudp.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/sniper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/overlap.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/__init__.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/herd.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/model.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/shipname.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/crypter.py to crypter.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/grider.py to grider.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/blackhole.py to blackhole.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/monlist.py to monlist.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/fraggle.py to fraggle.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/uforst.py to uforst.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/droper.py to droper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoack.py to ufoack.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/pinger.py to pinger.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoudp.py to ufoudp.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/sniper.py to sniper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/overlap.py to overlap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ufonet-1.7-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.7-py3.9.egg
removing '/usr/local/lib/python3.9/site-packages/ufonet-1.7-py3.9.egg' (and everything under it)
creating /usr/local/lib/python3.9/site-packages/ufonet-1.7-py3.9.egg
Extracting ufonet-1.7-py3.9.egg to /usr/local/lib/python3.9/site-packages
ufonet 1.7 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python3.9/site-packages/ufonet-1.7-py3.9.egg
Processing dependencies for ufonet==1.7
Searching for scapy-python3==0.26
Best match: scapy-python3 0.26
Processing scapy_python3-0.26-py3.9.egg
scapy-python3 0.26 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/scapy_python3-0.26-py3.9.egg
Searching for whois==0.9.13
Best match: whois 0.9.13
Processing whois-0.9.13-py3.9.egg
whois 0.9.13 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/whois-0.9.13-py3.9.egg
Searching for pycurl==7.43.0.6
Best match: pycurl 7.43.0.6
Processing pycurl-7.43.0.6-py3.9-linux-x86_64.egg
pycurl 7.43.0.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/pycurl-7.43.0.6-py3.9-linux-x86_64.egg
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1-py3.9-linux-x86_64.egg
pycrypto 2.6.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/pycrypto-2.6.1-py3.9-linux-x86_64.egg
Searching for requests==2.26.0
Best match: requests 2.26.0
Processing requests-2.26.0-py3.9.egg
requests 2.26.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/requests-2.26.0-py3.9.egg
Searching for pygeoip==0.3.2
Best match: pygeoip 0.3.2
Processing pygeoip-0.3.2-py3.9.egg
pygeoip 0.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/pygeoip-0.3.2-py3.9.egg
Searching for python-geoip==1.2
Best match: python-geoip 1.2
Processing python_geoip-1.2-py3.9.egg
python-geoip 1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/python_geoip-1.2-py3.9.egg
Searching for GeoIP==1.3.2
Best match: GeoIP 1.3.2
Processing GeoIP-1.3.2-py3.9-linux-x86_64.egg
GeoIP 1.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/GeoIP-1.3.2-py3.9-linux-x86_64.egg
Searching for urllib3==1.26.6
Best match: urllib3 1.26.6
Processing urllib3-1.26.6-py3.9.egg
urllib3 1.26.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/urllib3-1.26.6-py3.9.egg
Searching for idna==3.2
Best match: idna 3.2
Processing idna-3.2-py3.9.egg
idna 3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/idna-3.2-py3.9.egg
Searching for charset-normalizer==2.0.4
Best match: charset-normalizer 2.0.4
Processing charset_normalizer-2.0.4-py3.9.egg
charset-normalizer 2.0.4 is already the active version in easy-install.pth
Installing normalizer script to /usr/local/bin

Using /usr/local/lib/python3.9/site-packages/charset_normalizer-2.0.4-py3.9.egg
Searching for certifi==2021.5.30
Best match: certifi 2021.5.30
Processing certifi-2021.5.30-py3.9.egg
certifi 2021.5.30 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/site-packages/certifi-2021.5.30-py3.9.egg
Finished processing dependencies for ufonet==1.7
                                                                                                                                                                                                
┌──(dose㉿Dose)-[~/ufonet]
└─$ 

AS YOU CAN SEE THE setup.py looks successfully installed.
Can somegive me more info on how to do this,,please I will appreciate your help..

**Comment by epsylon** [comment]
@dosekali try to follow this thread: https://github.com/epsylon/ufonet/issues/301#issuecomment-790032789
