### ISSUE TITLE
[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [server]

### ISSUE THREAD

**Issue by samsep1oI** [epsylon/ufonet#336]
[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [server]
-------------------------------------------------------------------------------------------------
Hello! Help please :)
I tried with vpn, without vpn, with using tor, without using tor, all times I got this error, can you help me? Or just tell is the ufonet still working today? I use kali linux, mb you can recommend a linux distribution which I should use?

**Comment by epsylon** [comment]
@samsep1oI -> https://github.com/epsylon/ufonet/issues/333#issuecomment-904537970
