### ISSUE TITLE
[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!] ------------  [Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

### ISSUE THREAD

**Issue by Anonymous2212K** [epsylon/ufonet#337]
Hello friends, why do I get this error when I want to download the zombies in ufonet? I use kali linux in a virtual box, I thought it could be that, although I don't think so.

I already removed and installed 3 times kali linux in the virtual box and nothing works.

I hope they answer me, thank you.

**Comment by epsylon** [comment]
@Anonymous2212K -> Please, before opening a new ticket, check that the same question has not been answered before ->  https://github.com/epsylon/ufonet/issues/333#issuecomment-904537970

This is how we make our time more efficient... ;-)

Thanks!
