### ISSUE TITLE
print invalid syntax

### ISSUE THREAD

**Issue by Scrymmery** [epsylon/ufonet#338]
$ ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "D:\UfoNet-master\core\main.py", line 142
    print "                                             0===============================================0"
                                                                                                         ^
SyntaxError: invalid syntax
 
so, when i try to launch ufonet this error appears, looks like there is used python2 syntax, and readme tells it's requires python3+  am i missing something?

**Comment by epsylon** [comment]
@Scrymmery your version looks pretty old... (try: ./ufonet --version)

https://github.com/epsylon/ufonet/blob/master/core/main.py#L142
