### ISSUE TITLE
autosearch error

### ISSUE THREAD

**Issue by beZic** [epsylon/ufonet#344]
hi i keep getting this error when using zombie auto search, what should i do 

[Error] [AI] Unable to connect to: duck

**Comment by sinaj2889** [comment]
I have the same problem but only sometimes, I think its when you search to much duckduckgo gets suspicious.

**Comment by beZic** [comment]
> I have the same problem but only sometimes, I think its when you search to much duckduckgo gets suspicious.

how do i stop it from happening? i currently have found 1.3million possible zombies and i can't find out if they're active until i get around this problem

**Comment by sinaj2889** [comment]
> > I have the same problem but only sometimes, I think its when you search to much duckduckgo gets suspicious.
> 
> how do i stop it from happening? i currently have found 1.3million possible zombies and i can't find out if they're active until i get around this problem

Try using: ./ufonet -s 'proxy.php?url=' --se 'bing' 
And then let it search an then it should check all humans/possible zombies
But may you can help me at my problem I always only can attack one round and then I get Error something wrong attacking.

**Comment by epsylon** [comment]
@beZic related -> https://github.com/epsylon/ufonet/issues/178#issuecomment-550150466
