### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ozymumbles1** [epsylon/ufonet#35]
Can I DDoS ipv4 addresses?

**Comment by Pr0xy671** [comment]
This is not an issue.
Try and find out

**Comment by epsylon** [comment]
I recommend you to try the things before to ask for some attention...
Yes, you can DDoS to IPv4 addresses. But remember that this is a WebAbuse/Layer7 attack.
If you are planning to test it on a Home LAN, this should has a webserver listening (ex: router conf)
To make it, just add HTTP protocol prefix to target's IP:
./ufonet -a **http(s)**://IP

Thanks @Pr0xy671 ! :8ball:
