### ISSUE TITLE
Please add this function PULL REQUEST

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#350]
Hi epsylon thanks for this but would be nice you could add a toll that removes failed zombies out of zombies.txt automatically

Regards Sinaj

**Comment by epsylon** [comment]
@sinaj2889 this function exists (in fact it runs **automatically by default**) since version 1.2 "Armaggedon"...

So has been **implemented ~3 years ago**:

```
    --no-purge          Disable 'Zombies purge' round check
    --expire=EXPIRE     Set expire time for 'Zombies purge' (default: 30)
```
