### ISSUE TITLE
Боты не атакуют 

### ISSUE THREAD

**Issue by leo562** [epsylon/ufonet#352]
Здравствуйте, всем.

У меня проблема почему боты не атакуют, заражено 134 бота но они не атакуют цель

Ее нету если я указал

**Comment by epsylon** [comment]
Привет @leo562,

Попробуйте выполнить шаги, предложенные в следующем шаблоне, созданном для облегчения отчетов:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

Ваша цель поднята ?. Как вы думаете, может быть, используется брандмауэр?

Вы можете проверить своих «зомби», используя:

`python3 ufonet -t 'botnet/zombies.txt'`

Или создайте и атакуйте вас, чтобы убедиться, что они действительно работают с:

`python3 ufonet --attack-me  `
