### ISSUE TITLE
?

### ISSUE THREAD

**Issue by kingstar788** [epsylon/ufonet#354]
[Info] [Zombies] Attacking from: www.reddit.com
[Info] [Zombies] Attacking from: uy.radiocut.fm
[Info] [Zombies] Attacking from: www.jianyouxuetang.com
[Info] [Zombies] Attacking from: mantis.innovaphone.com
[Info] [Zombies] Attacking from: validator.w3.org
[Info] [Zombies] Attacking from: icda.lacba.org
[Info] [Zombies] Attacking from: www.sirus.fr
[Info] [Zombies] Attacking from: zonaprivada.recuerdo.net
[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

**Comment by epsylon** [comment]
@kingstar788 the solution to your problem is in the provided output:

`sudo apt-get install python3-geoip libgeoip-dev libgeoip1`

You need to install those libraries.
