### ISSUE TITLE
Can't access any pages in the GUI.

### ISSUE THREAD

**Issue by JayKash357** [epsylon/ufonet#355]
I don't know if they're fake, and intended to be troll pages, but when I click the ship.games, etc., pages it won't load with 404 not found.

**Comment by epsylon** [comment]
It is not possible to reproduce your error with that description. Try to use a template for bug reporting:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
