### ISSUE TITLE
Is server still down?

### ISSUE THREAD

**Issue by v-e-n-u-s-o-s** [epsylon/ufonet#357]
[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 176.28.23.46

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

**Comment by epsylon** [comment]
@v-e-n-u-s-o-s Your IP has been blocked by the firewall... 


```
[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX READY!] ;-)

```
