### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Warhammar** [epsylon/ufonet#358]
Im getting.

File <stdin> line1
seafile.rlp.net   FALSE - False 1666793855 sfcsrftoken

**Comment by epsylon** [comment]
really strage stuff @Warhammar o_0

try to fill in this template to know your environment: 

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
