### ISSUE TITLE
i've installed this version of ufonet and this is what i get straight out the box when i try any command

### ISSUE THREAD

**Issue by xXSVDBOIXx** [epsylon/ufonet#359]
this is just an example:
┌──(root💀my user)-[~/ufonet]
└─# ./ufonet -h
/usr/bin/env: ‘python’: No such file or directory
──(root💀my user)-[~/ufonet]
└─# ./ufonet --examples
/usr/bin/env: ‘python’: No such file or directory

**Comment by Ovanim** [comment]
Typ in first: cd ufonet
Maybe you can solve the problem...

**Comment by xXSVDBOIXx** [comment]
did cd then typed it i went into cd udfonet tyoed it and gave me the same
thing

**Comment by Ovanim** [comment]
Download ufonet again, maybe you didnt download it...

**Comment by xXSVDBOIXx** [comment]
i've tried redownloading and it gave the same error idk what else to trg
again

**Comment by Ovanim** [comment]
Comes exactly the same when you have enter cd ufonet?

**Comment by Ovanim** [comment]
And which version did you download?

**Comment by Ovanim** [comment]
git clone http://code.03c8.net:3000/epsylon/ufonet typ this in your terminal

**Comment by xXSVDBOIXx** [comment]
that constantly times out

**Comment by Ovanim** [comment]
Did you typed it in your terminal??

**Comment by xXSVDBOIXx** [comment]
yeah i did

**Comment by Ovanim** [comment]
And what was there after that?

**Comment by Ovanim** [comment]
Did it worked?

**Comment by xXSVDBOIXx** [comment]
no i got the same error

**Comment by Ovanim** [comment]
I don't think that's because of ufonet..Can you go in kali linux with a normal account? *so not root

**Comment by Ovanim** [comment]
I mean the basic one

**Comment by Ovanim** [comment]
kali@kali

**Comment by Ovanim** [comment]
And then download it again

**Comment by Ovanim** [comment]
With the basic account

**Comment by xXSVDBOIXx** [comment]
still saying the same thing

**Comment by epsylon** [comment]
@xXSVDBOIXx something wrong with your python environment:

` /usr/bin/env: ‘python’: No such file or directory`

Try: **python3** ufonet --examples

If you have the same error, you should try to re-install python3 (for example: python3.7):

`ex: sudo apt-get install python3.7`
