### ISSUE TITLE
UFONet stops...

### ISSUE THREAD

**Issue by lbdBG** [epsylon/ufonet#36]
Here is what i get in the terminal: (process:4210): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
If you need anything, just pm me
Running on a Kali Linux VM

**Comment by epsylon** [comment]
This is not an "error" from UFONet... 
It is a "warning" related with Firefox/browser (ex: http://askubuntu.com/questions/815424/ubuntu-16-wont-play-youtube-videos-sometimes) and shouldn't be a problem for the normal behavior of the tool.
Thanks by the way, for your suggestion.
