### ISSUE TITLE
Cant connect to any Engine in Ufonet

### ISSUE THREAD

**Issue by Ovanim** [epsylon/ufonet#362]
Hi guys,
I've got a problem, everytime there are these errors, for example: cant connect to:yahoo 
the same goes for the other search engines(bing and DuckDuckGo)
Does anyone know how to fix that?
Thanks

**Comment by epsylon** [comment]
@Ovanim It is easier to know what happens and see how you have configured your environment, fill in the following template:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

Btw, are you using any proxy (ex: Tor)?

**Comment by Ovanim** [comment]
No i don't
