### ISSUE TITLE
AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!] why ?

### ISSUE THREAD

**Issue by Gara123dfs** [epsylon/ufonet#363]
Every time i want to download Zombies It show this 

[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 176.28.23.46

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

I tried with VPN and without VPN and still...

**Comment by epsylon** [comment]
@Gara123dfs this IP (176.28.23.46) is not longer providing "Community Zombies"...

You should **--update** the tool to have the new one: https://github.com/epsylon/ufonet/commit/d9191b1a381a6ea70f8e5d41d072dee98ff3c5be

Or try to use another source taking from: **Global.Radar**
