### ISSUE TITLE
Unable to download a list of zombies [exiting]

### ISSUE THREAD

**Issue by InsaneGal** [epsylon/ufonet#364]
3 different IPs, this server is either down or I'm being banned from using it on sight through different IPs. I'd like an explanation.

**Comment by epsylon** [comment]
@InsaneGal this IP (176.28.23.46) is not longer providing "Community Zombies"...

You should **--update** the tool to have the new one: https://github.com/epsylon/ufonet/commit/d9191b1a381a6ea70f8e5d41d072dee98ff3c5be

Or try to use another source taking from: **Global.Radar**
