### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#368]
I get this error when using: 
python3 ufonet -s 'proxy.php?url=' --se 'bing'

Please help me thanks so much for this XD!

**Comment by epsylon** [comment]
@sinaj2889 it is more easy to research your issue if you try to fill this template: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

Thanks!
