### ISSUE TITLE
[Error] [AI] Unable to connect to: duck                                           
[AI] Do you want to try a different search engine? (Y/n)

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#369]
This one is not accepting "n" answer pls improve thanks very much

**Comment by epsylon** [comment]
@sinaj2889 it is accepting it, but "code flow" is not really advanced, for example, having in mind when more than one search engine is used. The code is just passing to next engine, so yeah, you are semi-right... I will have it in mind for future updates. Thanks!
