### ISSUE TITLE
Who can help me? :(

### ISSUE THREAD

**Issue by xkktm** [epsylon/ufonet#371]
[Info] [AI] You have [1970286 possible zombies] stored from a previous search...

[AI] Do you want to resume it? (NOTE: If not, this DATA will be REMOVED) (Y/n)

How could i save all the possible zombies that i have?

**Comment by epsylon** [comment]
@xkktm if you enter: "Y", your "zombies" will be saved. Also you have a file: _botnet/humans.txt_ with that zombies stored on it.
You can manually add these to: _botnet/zombies.txt_
