### ISSUE TITLE
ufonet --auto-search in an infinite loop

### ISSUE THREAD

**Issue by mixeddreams** [epsylon/ufonet#373]
--auto-search function never stops searching for zombies.

**Comment by epsylon** [comment]
@mixeddreams if the function keep going it is because it has results... btw, you can stop/break it using: **Ctrl+Z**

After that, you will have a new file at your **/data/** folder called: **humans.txt**

These are the zombies that you have found until you stopped the process.

**Comment by MiChaelinzo** [comment]
> @mixeddreams if the function keep going it is because it has results... btw, you can stop/break it using: **Ctrl+Z**
> 
> After that, you will have a new file at your **/data/** folder called: **humans.txt**
> 
> These are the zombies that you have found until you stopped the process.

They are automatically added in your list?

**Comment by MiChaelinzo** [comment]
> @mixeddreams if the function keep going it is because it has results... btw, you can stop/break it using: **Ctrl+Z**
> 
> After that, you will have a new file at your **/data/** folder called: **humans.txt**
> 
> These are the zombies that you have found until you stopped the process.

I got 5 mil in auto-search, what's the command `` to add them?

**Comment by MiChaelinzo** [comment]
https://i.vgy.me/5uovWd.png 

that's my cat neko-neko_chan

**Comment by epsylon** [comment]
@MiChaelinzo If you let the process end (even if it takes a lot of time), the zombies will be automatically added and avoiding repetitions. However, if you stop the process, you will have to copy them on your list manually.
