### ISSUE TITLE
GeoIP.h Error

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#374]
Hi buddy so I did some research after setup.py failed and I found out GeoIP uses something that doesn't support python3 but ufonet only works with python3 so I think you should update it to GeoIP2 that's available would love this bc them it would work again XD. Love this project so much but everytime there is trouble somewhere I hope you will fix it thank you soo much.

Regards Sinaj

**Comment by epsylon** [comment]
@sinaj2889 your suggestions are ridiculous from a dev perspective xD

about your GEoIP, try this: https://ufonet.03c8.net/#installation

probably installing this libs your issue will be fixed:

- python3-geoip - Python3 bindings for the GeoIP IP-to-country resolver library
- libgeoip-dev - Development files for the GeoIP library
- libgeoip1 - non-DNS IP-to-country resolver library

**Comment by sinaj2889** [comment]
Ok Lol now it's working but after some time at autosearch I get cant connect to duck but this is not a problem Lul
