### ISSUE TITLE
Zombies Inquiry

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#376]
Why the zombies list in GitHub is only 8? and blackhole I cannot download and connect, server error! btw amazing work you done here! Keep up the good work!

**Comment by epsylon** [comment]
@MiChaelinzo This feature is interesting in case the tool is attempted or by the Global.NET nodes can not share their zombies using "blackholes". In that case you can overturn and share all zombie lists quickly. 

It is something we can activate in case of emergency.

Do not share the zombies with the main tool also ensures complying with certain Github use policies.
