### ISSUE TITLE
Freezing after 5mil zombies

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#377]
https://i.vgy.me/9ewvPZ.png

I use the botnets in auto-search, converted humans into zombies, took 30 mins. freezing the Kali Linux while copy-pasting it.
I'm also using VMware Workstation Pro I got 8GB RAM and 2 processors and 4 cores per processors total of 8 processors. 
Even --test-all is freezing, I got 6.5k before works fine for me but 5mil in auto search would probably won't hurt. 
I'm planning cutting it into 100k, I'll be back.

**Comment by MiChaelinzo** [comment]
220k working fine for me, I'm planning 500k to 1m next just attacking regular website with Cloudflare etc.
I got nothing to do and using this Github issue as a diary.

**Comment by epsylon** [comment]
@MiChaelinzo Maybe we can check exactly at what point the tool is freezing to try to fix it...

**Comment by MiChaelinzo** [comment]
Before cli attack and auto-search and test-all. It's alright it's just freezing due to loads amount of botnets, my Kali Linux is the fault I think also I messed it up running depricated and legacy softwares, it's currently running LXDE only, MATE and GNOME etc. other versions won't work.
