### ISSUE TITLE
[Community] Server is receiving huge amounts of traffic...

### ISSUE THREAD

**Issue by epsylon** [epsylon/ufonet#380]
Hi,

The community server, which also serves the project website is receiving huge amounts of traffic.

At the moment, it is not possible to know if it is an attack or is due to the high demand of the UFONET tool, due to the events of the current world geopolitics.

It is a good time for you to use the nodes you can find by searching through Dork (and other methods). 

Do not forget to share the zombies that you have checked that work with the rest of the community:

https://raw.githubusercontent.com/epsylon/ufonet/master/docs/README_blackhole.txt

The central/community server is not necessary, if those who use Ufonet know how to organize.

----

If you have many targets, remember that you can put them in a list, in a text file (ex: targets.txt), as follows:

https://url1.net
https://url2.net
[...]

And launch from the shell, for example:

python3 ufonet -f "targets.txt" -R 100 ....

----

Remember that you can see many examples of how to combine different attack techniques to make your operations more efficient / powerful, with the command:

**python3 ufonet --examples**

----

Keep calm, the UFonet tool is P2P (peer to peer), so it should not affect you, beyond being able to download the zombies of the community (which is outdated).

Best regards!

**Comment by MiChaelinzo** [comment]
Thank you @epsylon for the update!

Amazing work your doing! Many people probably are using this tool. 
I wish I could help I'm still figuring out what happened with my KL VM can only run LXDE.

**Comment by epsylon** [comment]
[UFONet v1.8 - "DarK-PhAnT0m!"](https://github.com/epsylon/ufonet/releases/tag/v1.8) has been released...
