### ISSUE TITLE
Zombies

### ISSUE THREAD

**Issue by Frido-Cpp** [epsylon/ufonet#381]
Is it possible to use zombies for crypto mining?

**Comment by MiChaelinzo** [comment]
Yeah and that is illegal by law.

**Comment by Frido-Cpp** [comment]
Yeah Was asking for educational reasons. Talking about law. using the framework for attacks still uses zombies cpu, So I just thought of like using them for crypto stuffs :} just to learn how open redirect crypto jacking works
