### ISSUE TITLE
I have tried various installation methods, but it still has an error, how can I solve it?

### ISSUE THREAD

**Issue by kitcoun** [epsylon/ufonet#384]
[root ufonet]# ./ufonet -h
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/opt/script/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

centos7 python3.7.1

**Comment by MiChaelinzo** [comment]
Are you running the latest Python? or 3.8?
You need to download the module 
Example: pip3 install <package>==<version>
                                    numpy==1.16

**Comment by kitcoun** [comment]
python3.7.1

**Comment by kitcoun** [comment]
pip3 install pycrypto  
pip3 install pycrytodome

invalid

**Comment by epsylon** [comment]
@kitcoun try this:

- **sudo apt-get install python3-crypto
- pip3.7 install pycrypto**

**Comment by epsylon** [comment]
@kitcoun also:

**python3.7 -m pip install pycrypto**

**Comment by kitcoun** [comment]
> @kitcoun 还：
> 
> **python3.7 -m pip install pycrypto **
invalid, including replacing the system centos8

**Comment by epsylon** [comment]
@kitcoun to have more info about your issue, please, try to fill this template: 

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

Have you tried with other python versions (ex: 3.8) ?

**Comment by kitcoun** [comment]
Tried python 3.8.10

**Comment by epsylon** [comment]
@kitcoun this kind of issues in which I haven't any "real" data (environment, runtime, etc..) are just wasting time... 

Try to use this template: https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by kitcoun** [comment]
![20220317232000 1](https://user-images.githubusercontent.com/38834202/158834742-104c6e5c-3456-43a6-b7b0-f486a1f3eb06.png)
![20220317232000 2](https://user-images.githubusercontent.com/38834202/158834789-502ffaef-46a1-420e-9ffa-a80669b00b88.png)
![20220317232755](https://user-images.githubusercontent.com/38834202/158834804-37f3af6a-2f0e-479e-bfdd-21e307d976eb.png)

I reset the system

**Comment by epsylon** [comment]
@kitcoun This last comment makes it easier to understand what really happens, thanks!

Look at your first image:

`python3 setup.py install -> -bash: python3: command not found`

Try this:

**python3.8 setup.py install** 

Due to the configuration of your environment, you must run Python3 with the exact version (python3.8, python3.7, etc.)

**Comment by kitcoun** [comment]
I tried many times, including different systems, different Python versions, PIP3 installation and so on, but all ended in failure
