### ISSUE TITLE
fix: 'SyntaxWarning: "is not" with a literal. Did you mean "!="?'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [epsylon/ufonet#386]
See https://github.com/epsylon/ufonet/blob/master/core/main.py#L3171

Change from 
```python
                if abductions_reply is not "":
```
to
```python
                if abductions_reply != "":
```
or just
```python
                if abductions_reply:
```

**Comment by epsylon** [comment]
@AIGeneratedUsername you are right. It works but there is a warning when building the toolhttps://github.com/epsylon/ufonet/commit/62d1a70001ae1f944556a3ac2fa8785b8d5178cd

Fixed: https://github.com/epsylon/ufonet/commit/62d1a70001ae1f944556a3ac2fa8785b8d5178cd

Thanks!
