### ISSUE TITLE
ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by MiddleMan12** [epsylon/ufonet#387]
I have all requested packages installed and when i try to use ./ufonet im getting this error 

Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/alex/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

**Comment by MiddleMan12** [comment]
The problem was i wasn't using python3 (ex. python3 ufonet )

**Comment by KentoBento123** [comment]
> The problem was i wasn't using python3 (ex. python3 ufonet )

I dont think that was the problem as I am currently using sudo python3 unfonet but its still not workin
