### ISSUE TITLE
How does this command work?

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#391]
--expire 5 what would that do I don't understand for what the number stands like rounds or what bc it should purge but doesn't really how it should so I guess I'm using it wrong

**Comment by epsylon** [comment]
The command is used to mark the time in seconds to make a purge of the "zombies" that do not work, for each round. This is used, above all, when you have a large list of "zombies", to make the rounds become more and more effective. The default value (30 seconds) should be correct.
