### ISSUE TITLE
Could you help me with this?

### ISSUE THREAD

**Issue by KentoBento123** [epsylon/ufonet#393]
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I have python 3.10
and had pasted python3 setup.py install

also the Makefile says Cannot run program "\usr\bin\make" (in directory "C:\Users\Name\OneDrive\Desktop\ufonet-v1.8\ufonet"): CreateProcess error=2, The system cannot find the file specified

**Comment by dontbanmeplz** [comment]
Windows is not supported with ufonet, make is not something that can exist on windows use wsl or windows subsystem for linux. This will allow you to run the program @KentoBento123

**Comment by KentoBento123** [comment]
When I tried it says "The requested operation requires elevation" @dontbanmeplz

**Comment by KentoBento123** [comment]
sorry i its a dumb question but i got ubuntu going but it couldn't find the files crypto, ex @dontbanmeplz

**Comment by dontbanmeplz** [comment]
Did you run git clone again and redo the install process? Also it's good to run `apt update`

**Comment by KentoBento123** [comment]
git clone https://github/epsylon/ufonet
Cloning into 'ufonet'...
fatal: unable to access 'https://github/epsylon/ufonet/': Could not resolve host: github 

@dontbanmeplz

**Comment by KentoBento123** [comment]
apt update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
@dontbanmeplz  (my brain is not functioning)

**Comment by dontbanmeplz** [comment]
>  git clone https://github/epsylon/ufonet
> 
> Cloning into 'ufonet'...
> 
> fatal: unable to access 'https://github/epsylon/ufonet/': Could not resolve host: github 
> 
> 
> 
> @dontbanmeplz 

This I have no idea but you have to run `sudo apt update`

**Comment by KentoBento123** [comment]
but I can't cause permissions it shows but I ran as administer do you know whats goin on with this @dontbanmeplz

**Comment by dontbanmeplz** [comment]
Do you know how to use Linux

**Comment by KentoBento123** [comment]
nvm Im dumb as hell I forgot to run as root @dontbanmeplz

**Comment by KentoBento123** [comment]
nvm said it too early @dontbanmeplz 

setuptools.sandbox.UnpickleableException: ConfigurationError("Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'")

**Comment by epsylon** [comment]
@KentoBento123 
1) _git clone https://github/epsylon/ufonet_ -> **git clone https://github.com/epsylon/ufonet**
2) [Errno 2] No such file or directory: 'curl-config'") -> **sudo apt-get install python3-pycurl**
