### ISSUE TITLE
Cannot connect to Tor

### ISSUE THREAD

**Issue by GWMNGSG** [epsylon/ufonet#396]
Hello,

I apologise in advance because I am pretty aware of being a total noob.
I would like to learn how to use this tool safely, so I installed a Ubuntu VM on VirtualBox on my laptop.

I did some researches and I acknowledged the existence of  the ```proxychains4```  for connecting to the Internet through a chain of proxies. 

In the ```/etc/proxychains4.conf``` file  I specified ```random_chain``` as a method with maximum length of 3. 
I added some proxies at the bottom of the file (I'm also proxying the DNS reequest with ```proxy_dns```).

I activated the tor server with ``` sudo systemctl start tor.service``` , with a socket listening on ```127.0.0.1:9050``` (I found out that this is the default Tor port). 

When i run ```proxychains4 ./ufonet --check-tor```, the proxychains starts, with three random proxies amongst the ones in the config file.

Everything is okay, it can connect up until ```check.tor.project.org:443 ... OK```, 
Then it shows ```It seems that tor is not properly set```, but as my IP address actually gives me the one of the last proxy in the chain and not mine.

I guess that this has to do with some misconfiguration of tor, but I checked its status and it seems to be actually active, maybe I should more deeply check the log files of tor but I actually dont know

I was wondering how I could fix this problem, 

Thank you

**Comment by MiChaelinzo** [comment]
Are you trying to attack yourself and it won't work? Or you trying to shutdown a huge website?. Which won't really work without many participants and rounds. Also being it run like blockchain which is p2p and requires users original IP. Also zombies here are persistent and would keep attacking even after use, if you don't block it's IP etc. It will test your website javascript or bot test repeatedly. This DDOS/DOS open software is both awesome and scary... also be careful of the daemons when you share your IP. For me I'm planning to use Ufonet for blue team/defensive.

**Comment by epsylon** [comment]
@GWMNGSG Check first for some other threads related with proxies, here:

https://github.com/epsylon/ufonet/issues?q=is%3Aissue+is%3Aclosed+proxychains

A good example about proxychains:

https://github.com/epsylon/ufonet/issues/151
