### ISSUE TITLE
Please add a crypto mining function and use better site up checkers bc it says offline even when online tyy.

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#397]
Suggestion in title.

**Comment by epsylon** [comment]
Thanks for your suggestion

**Comment by sinaj2889** [comment]
I hope to see some goof enhancements soon xd

**Comment by epsylon** [comment]
This tool is not for mining, and haven't nothing related with it. I can do whatever with code, sure, but no every happy idea that pass for the mind of a troll as you are. I hope that you understand my position :-)

**Comment by sinaj2889** [comment]
Not yet

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/406#issuecomment-1185403021
