### ISSUE TITLE
UFOnet - FileNotFoundError: No Such file or directory: 'docs/FAQ.html'

### ISSUE THREAD

**Issue by vlibNull** [epsylon/ufonet#398]
So, 
This is just ONE issue I had with this package on an Arch install. 
Update: Did a full rollback on my system and fetched it again, still having this particular issue.

Traceback (most recent call last):
File "/usr/share/ufonet/ufonet", line 16, in <module>
app.run()
File "/usr/share/ufonet/core/main.py", line 1378, in run
self.create_web_interface()
File "/usr/share/ufonet/core/main.py", line 3778, in create_web_interface
newthread = ClientThread(ip, port, clientsock)
File "/usr/share/ufonet/core/webgui.py", line 62, in __init__
self.pages = Pages()
File "/usr/share/ufonet/core/webgui.py", line 2560, in __init__
f = open(self.faq_file) # extract FAQ text
FileNotFoundError: [Errno 2] No such file or directory: 'docs/FAQ.html'

**Comment by vlibNull** [comment]
Update: OLD. I tried to install a prebuilt package from blackarch repo, turns out it's outdated. However, my most recent issue request is still happening with a rollback of my entire system and a fresh reinstall of ufonet from this repo directly.

**Comment by epsylon** [comment]
@vlibNull it looks that there is something wrong with your OS environment. 

` FileNotFoundError: [Errno 2] No such file or directory: 'docs/FAQ.html'`

Try to:

1) Clone UFONet repository: _git clone https://github.com/epsylon/ufonet_
2) Install it using provided auto-setup script: **python3 setup.py install**
3) Check that file "FAQ.html" exists at "docs" folder
