### ISSUE TITLE
Downloading nodes & github zombies/BOTNET Error!

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#404]
```
[AI] Downloading list of [Zombies] from [Radar] [Blackhole] [Nodes] ...

======================

[Error] [AI] Something wrong downloading! -> [Exiting!]

michael@cocaine:~/ㄒㄖㄖㄥ丂/BOTNET/ufonet$ sudo python3 ufonet --download-nodes



```
**I have not this error in my ParrotOS only in Kali Linux** 

_also ParrotOS ufonet can't attack or start GUI!_

**Comment by epsylon** [comment]
This is not an error. . 

Probably your IP has been firewalled by "l4m3r1ng attempts!" :)

Stop [boring/trolling this forum](https://github.com/MiChaelinzo?tab=overview&from=2022-01-01&to=2022-01-31).

**Comment by sinaj2889** [comment]
I get the same I didn't do it before

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/406#issuecomment-1185403021
