### ISSUE TITLE
Is there are way this could be stronger because if you use this it doesn't even affect the website a bit.

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#406]

**Comment by epsylon** [comment]
@sinaj2889 RTFM! ;-)

**Comment by sinaj2889** [comment]
I have but it's not strong you can't even annoy  a server with it

**Comment by sinaj2889** [comment]
I swear I studied the documentation 7 times when I was bored I read everything and it didn't affect it or tell me what to do I have 5000 zombies I used all methods

**Comment by sinaj2889** [comment]
@josyaaa what what?

**Comment by sinaj2889** [comment]
@epsylon what am I doing wrong huh?
And why are all your answers here so cheeky like as if I first would read the docs before I ask?!

**Comment by epsylon** [comment]
@sinaj2889 your time trolling this place with multiple accounts and silly questions is over. 

Good luck! :)
