### ISSUE TITLE
Please check the zombies and other types on the community server from time to time

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#407]

**Comment by epsylon** [comment]
Of course. Do you want something more?. I am here, exclusively, for you and your needs. Even, you can call me as "Mr Little Slave"... ;-)

**Comment by sinaj2889** [comment]
No no I just wanted to say more than 50% of the zombies on the server are trash = not working

**Comment by epsylon** [comment]
So, create your own zombies list... easy!

**Comment by sinaj2889** [comment]
Yeah I understand but for new people to test it it's annoying
