### ISSUE TITLE
ModuleNotFoundError: Not module named 'UFONet'

### ISSUE THREAD

**Issue by BoomSharing** [epsylon/ufonet#410]
I try to run it in the folder I installed it to as per suggestion in [https://github.com/epsylon/ufonet/issues/59](Issue 59) and i still get this error

I am running on Arch Linux

[boom@Toaster-003 ufonet]$ python ufonet.py
python: can't open file '/home/boom/Downloads/ufonet-v1.8/ufonet/ufonet.py': [Errno 2] No such file or directory
[boom@Toaster-003 ufonet]$ ufonet
Traceback (most recent call last):
  File "/usr/bin/ufonet", line 33, in <module>
    sys.exit(load_entry_point('ufonet==1.8', 'gui_scripts', 'ufonet')())
  File "/usr/bin/ufonet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet'

Any suggestions?

**Comment by epsylon** [comment]
Hi @BoomSharing 

```
[boom@Toaster-003 ufonet]$ python ufonet.py
python: can't open file '/home/boom/Downloads/ufonet-v1.8/ufonet/ufonet.py': [Errno 2] No such file or directory
```

Let's check what files you have at app root folder. Try this: 

[boom@Toaster-003 ufonet]$ ls

**Comment by BoomSec** [comment]
So I haven't been able to recreate the problem unfortunately and fortunately I guess. However I have tried to install it onto another operating system and encountered a similar problem I had encountered with my original Arch Linux system which is included below. I feel that it may be contributing to the problem;

  × Running setup.py install for geoip did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      /usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'bugtrack_url'
        warnings.warn(msg)
      Warning: 'classifiers' should be a list, got type 'tuple'
      running install
      /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'GeoIP' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC -I/usr/include/python3.10 -c py_GeoIP.c -o build/temp.linux-x86_64-3.10/py_GeoIP.o
      py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory
         23 | #include "GeoIP.h"
            |          ^~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> geoip

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by epsylon** [comment]
@BoomSec <-> @BoomSharing 

FIX:

    **sudo apt-get install libgeoip1 libgeoip-dev**
    **sudo python3 setup.py install**
