### ISSUE TITLE
Lol Looks offline

### ISSUE THREAD

**Issue by ajunkdha** [epsylon/ufonet#411]
I've been using it for almost 1 week.. but strangely the botnet considers the target offline..

**Comment by epsylon** [comment]
@ajunkdha did you try to run the tool after this commit? https://github.com/epsylon/ufonet/commit/753904e3923c9d972997ff7b060acce38c3801f9

Anyway, remember that it can also be something related to the checkpoint. Some what they do is launch a head, others make a ping at the network level and your target may have disabled respond to such requests. I don't have enough data to help you.

**Comment by ajunkdha** [comment]
> 

Yes working, target nice be clam 
Thanks eps <3
