### ISSUE TITLE
./ufonet --auto-search not ending

### ISSUE THREAD

**Issue by YusaGozlukAdam** [epsylon/ufonet#412]
Hi! When I run ./ufonet --auto-search this code keeps looping, how long will this take?

sorry for asking a dumb question

**Comment by TITAN-ComProject** [comment]
Endlessly, but you can stop it with control + z

**Comment by YusaGozlukAdam** [comment]
okay thanks

**Comment by YusaGozlukAdam** [comment]
@TITAN-ComProject  so, i download humans but, i cant add to my army, how i can add?

**Comment by epsylon** [comment]
@YusaGozlukAdam The process will end when there are no possible results. The tool warns you that it could last a long time.

The transfer of humans to zombies should be automatic. But you can do it manually. Open with a text editor the file (btonet/humans.txt) and copy/paste the list on the file (botnet/zombies.txt).

**Comment by AnonymousModz420** [comment]
untill it dont find anything if u want to stop the search urself hit CONTROL Z

Sent from Proton Mail mobile

-------- Original Message --------
