### ISSUE TITLE
Error importing: requests lib. 

### ISSUE THREAD

**Issue by gelan77** [epsylon/ufonet#416]
Hi i have a problem when i try to run this i get the error "Error importing: requests lib" i have upgraded the whole system and updated requests but alas the error remains please help

**Comment by gelan77** [comment]
![Screenshot_2022-08-29_06_54_08](https://user-images.githubusercontent.com/83081203/187186587-47b1ae17-ba9b-4729-965d-c9ee06986da4.png)

**Comment by epsylon** [comment]
@gelan77 plz, review -> https://ufonet.03c8.net/#installation

try:

**sudo apt-get install python3-requests**

or

**pip3 install requests**

**Comment by gelan77** [comment]
I tried both of them but it hasn't worked yet

**Comment by dontbanmeplz** [comment]
what error are you getting when you try these commands?

**Comment by joshuyaaa** [comment]
...

**Comment by epsylon** [comment]
@joshuyaaa @gelan77 maybe is related with the specific version of Python3 (Python3.5, Python3.8, etc...). Do you have more than one version installed? (python3 --version)

Try with more specific pip3, such as: **pip3.8 install request**

**Comment by joshuyaaa** [comment]
@epsylon  I think @gelan77  Q,I don't understand what you will have such Q ? python ok

**Comment by gelan77** [comment]
My version is 3.10.5 I think the problem is not in this, yet request has versions 2.28.1 but apparently it is not visible
