### ISSUE TITLE
Crypto.Cipher error module.

### ISSUE THREAD

**Issue by Vikingo-07** [epsylon/ufonet#417]
└─$ ./ufonet -h                                                                                               100 ⨯
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kali/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

i cant fix that..

**Comment by Godtier37** [comment]
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/root/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

**Comment by epsylon** [comment]
https://stackoverflow.com/a/39048720

**Comment by Vikingo-07** [comment]
> https://stackoverflow.com/a/39048720

┌──(kali㉿kali)-[~/ddos/ufonet]
└─$ sudo pip uninstall crypto                                                                                                                                                                                                            1 ⨯
[sudo] password for kali: 
Found existing installation: crypto 1.4.1
Uninstalling crypto-1.4.1:
  Would remove:
    /usr/local/bin/crypto
    /usr/local/bin/decrypto
    /usr/local/lib/python3.10/dist-packages/crypto-1.4.1.dist-info/*
    /usr/local/lib/python3.10/dist-packages/crypto/*
Proceed (Y/n)? 
  Successfully uninstalled crypto-1.4.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
                                                                                                                                                                                                                                             
┌──(kali㉿kali)-[~/ddos/ufonet]
└─$ sudo pip uninstall pycrypto
Found existing installation: pycrypto 2.6.1
Uninstalling pycrypto-2.6.1:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/pycrypto-2.6.1-py3.10-linux-x86_64.egg
Proceed (Y/n)? 
  Successfully uninstalled pycrypto-2.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
                                                                                                                                                                                                                                             
┌──(kali㉿kali)-[~/ddos/ufonet]
└─$ sudo pip install pycrypto  
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.2/446.2 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycrypto
  Building wheel for pycrypto (setup.py) ... done
  Created wheel for pycrypto: filename=pycrypto-2.6.1-cp310-cp310-linux_x86_64.whl size=524480 sha256=14f515fff89c64f8eeed2aa70676142d1b3fa589edaf17939ae6dde7c3a697bb
  Stored in directory: /root/.cache/pip/wheels/e8/4b/5b/b10a6fc885057b6ff9fbd5691d7e700d0a9408f80b7e6f12e0
Successfully built pycrypto
Installing collected packages: pycrypto
Successfully installed pycrypto-2.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
                                                                                                                                                                                                                                             
┌──(kali㉿kali)-[~/ddos/ufonet]
└─$ ./ufonet -h                
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kali/ddos/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

**Comment by Vikingo-07** [comment]
┌──(kali㉿kali)-[~/ddos/ufonet]
└─$ python                   
Python 2.7.18 (default, Aug  1 2022, 06:23:55) 
[GCC 12.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.Cipher import AES
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Crypto.Cipher
>>>
