### ISSUE TITLE
It seems that Tor is not properly set.

### ISSUE THREAD

**Issue by net-vader12968** [epsylon/ufonet#42]
## ufonet-v0.8# ./ufonet --check-tor
```
=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

UFONet - DDoS Botnet via Web Abuse - by psy 

===========================================================================**

Sending request to: https://check.torproject.org
It seems that Tor is not properly set.

Your IP address appears to be: xxx.xxx.xxx.117

```
I sure TOR browser is working properly........

thnx in adv. 

> 
*************************NOOB Alert!!!*************************
 @epsylon

**Comment by epsylon** [comment]
This should works if you have TOR configurated as a terminal environment... If you haven't you should try it like this: 
**./ufonet --check-tor --proxy "http://127.0.0.1:8118"**
(you need to invoke --proxy on your check)

**Comment by Tosible** [comment]
Lol @net-vader12968 I think you just gave everyone your IP?
If you're on Windows, make sure you have Tor Browser up. Then set the proxy flag to something like:
`./ufonet --check-tor --proxy "http://127.0.0.1:9150`
Tor Browser runs on port 9150

**Comment by epsylon** [comment]
I have edited @net-vader12968 comment to snip IP..
@Tosible thanks! :8ball:
