### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KirbyHacks** [epsylon/ufonet#421]
I am new to using UFOnet so what seems more comfortable to me is the gui. At the time of the attacks, this same one hangs on me and does not receive any response, in addition to the fact that the zombies stop working, I tried to test them but they are all online, the site is also online. Can someone help me?
![proof](https://user-images.githubusercontent.com/99104490/203425438-1a88ae2c-1335-4b61-b981-c6f4c262d414.png)

**Comment by epsylon** [comment]
hey @KirbyHacks, it seems that t**he list of zombies you have does not work correctly**. 

You can **look at the final statistics** to see how many work properly. 

You can also do tests (**--test-all** / **-t "botnet/zombies.txt"** ) to see if they respond. 

You can even do a somewhat more complex test to measure its efficiency (**--attack-me**).

Another option may be or **someone passes you a zombies list**. 

Also, take a **look at the Globalnet**.

**Comment by KirbyHacks** [comment]
thanks dude
