### ISSUE TITLE
web gui not opening in fire fox

### ISSUE THREAD

**Issue by arad-top-g** [epsylon/ufonet#423]
when i use the command (sudo ./ufonet --gui)it opens the web interface in another browser called GNOME what should i do

**Comment by epsylon** [comment]
Hi @arad-top-g 

This is related with your OS environment. You have GNOME browser set as default browser. Try to change it on your settings for other that you want.

Btw, you can open another browser after launch UFONet and enter this url manually on it: http://127.0.0.1:9999
