### ISSUE TITLE
I just installed ufonet and downloaded everything including zombies. However, when I run the "./ufonet - - gui" code and attack a url from the "attack" part of the web page, I get the following error "Error importing: pygeoip lib. On Debian based systems: $ sudo apt-get install python-geoip' or 'pip install geoip')" also shows zombies 0 on the map. I waited about 10 minutes and nothing changed. Nothing changes when I write the above code. Please help as soon as possible! :) @epsylon

### ISSUE THREAD

**Issue by Angalut** [epsylon/ufonet#424]
![27485233-efa18450-57f9-11e7-8650-88b65c6ef947(1).png](https://user-images.githubusercontent.com/121760276/210256546-73926dc3-e8fe-4e3e-a96c-e0d1218c0437.png)

![27485234-f2007652-57f9-11e7-909d-3488000c6373(1).png](https://user-images.githubusercontent.com/121760276/210256570-56434f35-53c9-41f2-9f21-441bed303671.png)

![27485226-e893f120-57f9-11e7-8f51-6e19a928023e(1).png](https://user-images.githubusercontent.com/121760276/210256590-b1a29e22-1121-4ce7-9cc8-9a7c8173b23c.png)

**Comment by dontbanmeplz** [comment]
What is the software on your server?

**Comment by epsylon** [comment]
@Angalut lol, your madness is like a trip ;)

related: https://github.com/epsylon/ufonet/issues/18

**Comment by Angalut** [comment]
Thanks i will try this as soon as possible 😙🙌

**Comment by Angalut** [comment]
> What is the software on your server?
> 

I could not understand what you mean. If you are talking about the operating system, the operating system is Kali Linux (Virtual Machine) @dontbanmeplz

**Comment by tsimon05** [comment]
@Angalut does ufonet work for you?

**Comment by Angalut** [comment]
> @Angalut does ufonet work for you?

Yes, but i not using ufonet now.
