### ISSUE TITLE
python3 scapy error

### ISSUE THREAD

**Issue by b33fsup3m3** [epsylon/ufonet#425]
┌──(root㉿d3m0n)-[/home/d3m0n/ufonet]
└─# python3 ufonet --gui

        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene.
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).

Error importing: scapy lib.

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

┌──(root㉿d3m0n)-[/home/d3m0n/ufonet]
└─# sudo apt-get install python3-scapy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-scapy is already the newest version (2.4.5+g9420c22-2).
The following packages were automatically installed and are no longer required:
  distro-info-data ettercap-common ettercap-graphical gir1.2-nautilus-3.0 golang-1.18 golang-1.18-doc golang-1.18-go
  golang-1.18-src libatk1.0-data libavcodec58 libavutil56 libduktape207 libev4 libfaudio0 libflac8 libflac8:i386
  libfmt8 libilmbase25 libjs-psl libjs-terser liblerc3 liblerc3:i386 libllvm13 libluajit-5.1-2 libluajit-5.1-common
  libnautilus-extension1a libnode93 libnsl2:i386 libopenexr25 libpcre3:i386 libperl5.34 libpolkit-agent-1-0
  libpolkit-gobject-1-0 libpoppler118 libstb0 libsvtav1enc0 libsvtav1enc0:i386 libswresample3 libtirpc3:i386 libucl1
  libwebsockets16 libwireshark15 libwiretap12 libwrap0:i386 libwsutil13 libx264-163 node-abab node-asynckit
  node-combined-stream node-cssom node-cssstyle node-delayed-stream node-domelementtype node-domhandler node-entities
  node-exit-hook node-form-data node-jsdom node-mime node-mime-types node-parse5 node-psl node-terser
  node-tough-cookie node-universalify node-webidl-conversions openjdk-11-jre perl-modules-5.34 pkexec polkitd
  python3-future python3-impacket python3-invoke python3-ldap3 python3-ldapdomaindump python3-nacl python3-paramiko
  python3-pefile python3-qrcode ruby2.7 ruby2.7-dev ruby2.7-doc upx-ucl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 499 not upgraded.

**Comment by Kris-Lcq** [comment]
Unable to locate package python3-scapy.
How to fix it?

**Comment by epsylon** [comment]
try this: **python3 -m pip install scapy**

https://stackoverflow.com/questions/54576932/so-since-scapy-has-been-renamed-to-kamene-how-would-i-import-and-use-base64-byt
