### ISSUE TITLE
[Error] [AI] you haven't [Zombies] to be extracted from: 'botnet/zombies.txt'

### ISSUE THREAD

**Issue by h54t45tv45** [epsylon/ufonet#426]
plz help

**Comment by epsylon** [comment]
@h54t45tv45 the [Error] message is really clear... try to re-clone this repo, or just "touch" /botnet/zombies.txt file and run --download-zombies command to restablish your db

**Comment by hamid0901** [comment]
how to do? go directory ufonet/botnet/ and ./ufonet ----download-zombies or ufonet/ --download-zombies?

**Comment by epsylon** [comment]
you should search for zombies (dorking, other motherships, etc...)
