### ISSUE TITLE
i cant install scapy 

### ISSUE THREAD

**Issue by FRRIES** [epsylon/ufonet#429]
when i use the command ./ufonet says:
Bad key text.parse_math in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 303 ('text.parse_math: True  # Use mathtext if there is an even number of unescaped')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.2/matplotlibrc.template
or from the matplotlib source distribution

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

and when i copy and paste sudo apt-get install python3-scapy says Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
python3-scapy ya está en su versión más reciente (2.4.5+g9420c22-2).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 14 no actualizados.
ad says again this:
Bad key text.parse_math in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 303 ('text.parse_math: True  # Use mathtext if there is an even number of unescaped')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.2/matplotlibrc.template
or from the matplotlib source distribution

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

**Comment by dontbanmeplz** [comment]
What system type are you on

**Comment by FRRIES** [comment]
Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/425#issuecomment-1406130798
