### ISSUE TITLE
try decryption

### ISSUE THREAD

**Issue by ehhtehh** [epsylon/ufonet#430]
how to you decrypt the news etc.. on the gui?

**Comment by epsylon** [comment]
@ehhtehh You need to introduce the secret key in the input box. UFONet uses symmetrical encryption (AES256+HMAC-SHA1). In some sections it will be enough for you to click on a link in which he says: "**Try Decryption**".

From the terminal, you can launch the command: **python3 ufonet --crypter** and follow the steps to encrypt/decipher.

**Comment by ehhtehh** [comment]
Zombies are saying failed (cannot connect) is that normal or happens on a
target. Or is it because my tor or privacy is not configured correctly?

**Comment by ehhtehh** [comment]
Oops I meant privoxy

**Comment by epsylon** [comment]
@ehhtehh some of the main possible answers to your question:

1 - Your zombies list is not correctly updated (for example, only with working zombies) so it is not a valid list
2 - Your networking is not working
3 - Your target is offline!

**Comment by ehhtehh** [comment]
If the host I am testing with has most protocols blocked such as icmp ping
request etc... how would you be able to further stress test it.. it seems
invincible. But I feel that can't be possible
