### ISSUE TITLE
installing error and can't run 

### ISSUE THREAD

**Issue by arnabmaity777** [epsylon/ufonet#433]
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing ufonet.egg-info/PKG-INFO
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
writing requirements to ufonet.egg-info/requires.txt
writing top-level names to ufonet.egg-info/top_level.txt
reading manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images.aliens' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images.aliens' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images.aliens' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images.aliens' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images.crew' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images.crew' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images.crew' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images.crew' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js.cluster' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js.cluster' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js.cluster' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js.cluster' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js.leaflet' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js.leaflet' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js.leaflet' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js.leaflet' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.txt' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.txt' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.txt' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.txt' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/model.txt -> build/bdist.linux-x86_64/egg/core/txt
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jit.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/spaceinvaders.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/webgui.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/board.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/commander.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/favicon.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien10.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien1.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien9.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien3.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien8.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien6.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien2.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien7.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien13.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien4.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien5.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien12.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien11.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/ufonet-logo.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link8.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link12.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link11.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link9.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link6.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link2.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link1.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link4.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link7.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link5.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link10.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link3.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/aliens.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/mothership.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/__init__.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/update.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/crypter.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/grider.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/blackhole.py -> build/bdist.linux-x86_64/egg/core/tools
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/sniper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/pinger.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoudp.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/fraggle.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/droper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoack.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/uforst.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/monlist.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/overlap.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/main.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/herd.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/options.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/zombie.py -> build/bdist.linux-x86_64/egg/core
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/crypter.py to crypter.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/grider.py to grider.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/blackhole.py to blackhole.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/sniper.py to sniper.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/pinger.py to pinger.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoudp.py to ufoudp.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/fraggle.py to fraggle.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/droper.py to droper.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoack.py to ufoack.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/uforst.py to uforst.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/monlist.py to monlist.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/overlap.py to overlap.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ufonet-1.8-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.8-py3.11.egg
removing '/usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg' (and everything under it)
creating /usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg
Extracting ufonet-1.8-py3.11.egg to /usr/local/lib/python3.11/dist-packages
ufonet 1.8 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg
Processing dependencies for ufonet==1.8
Searching for scapy-python3>=0.20
Reading https://pypi.org/simple/scapy-python3/
Downloading https://files.pythonhosted.org/packages/4f/f3/e33d21e25b0dda2ffeebcc3ad06d26eff7f913c9b8b397c30f443b68b8e4/scapy-python3-0.26.tar.gz#sha256=81e4f5522d38c136fd3f1be4e35ffe4fd1f4c2091db3c021d95f8b9d5978b9eb
Best match: scapy-python3 0.26
Processing scapy-python3-0.26.tar.gz
Writing /tmp/easy_install-g606m4ka/scapy-python3-0.26/setup.cfg
Running scapy-python3-0.26/setup.py -q bdist_egg --dist-dir /tmp/easy_install-g606m4ka/scapy-python3-0.26/egg-dist-tmp-mpj78qgz
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-g606m4ka/scapy-python3-0.26/setup.py", line 11, in <module>
    """
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout. Did you mean: 'install_platlib'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/darkstar/Desktop/ufonet/setup.py", line 19, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 444, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 733, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 778, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 705, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 731, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 924, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1198, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1182, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-g606m4ka/scapy-python3-0.26/setup.py", line 11, in <module>
    """
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

after that when i'm trying to run it shows 

Traceback (most recent call last):
  File "/home/user/Desktop/ufonet/ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/user/Desktop/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by epsylon** [comment]
@arnabmaity777 try:

    sudo apt-get install python3-crypto
    pip3 install pycrypto

And/or search here: https://github.com/epsylon/ufonet/issues?q=is%3Aissue+is%3Aclose+No+module+named+%27Crypto%27+
