### ISSUE TITLE
longintrepr.h not found

### ISSUE THREAD

**Issue by Dyjana7** [epsylon/ufonet#437]
sudo python3 setup.py install
running install
/usr/local/lib/python3.11/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing ufonet.egg-info/PKG-INFO
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
writing requirements to ufonet.egg-info/requires.txt
writing top-level names to ufonet.egg-info/top_level.txt
reading manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images.aliens' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images.aliens' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images.aliens' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images.aliens' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.images.crew' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.images.crew' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.images.crew' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.images.crew' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js.cluster' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js.cluster' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js.cluster' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js.cluster' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.js.leaflet' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.js.leaflet' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.js.leaflet' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.js.leaflet' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/usr/local/lib/python3.11/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'core.txt' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'core.txt' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'core.txt' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'core.txt' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
copying build/lib/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/shipname.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/model.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/options.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/board.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien10.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien7.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien1.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien2.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien5.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien13.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien9.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien6.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien4.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien3.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien12.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien11.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien8.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/mothership.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/ufonet-logo.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/favicon.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link3.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link2.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link6.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link4.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link12.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link5.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link7.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link11.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link10.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link8.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link1.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link9.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/commander.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/blackhole.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/crypter.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/grider.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/main.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/update.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/spaceinvaders.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/treemap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jit.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/sniper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/overlap.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/droper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoudp.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/pinger.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/monlist.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/uforst.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoack.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/fraggle.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/herd.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/webgui.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/zombie.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/__init__.py -> build/bdist.linux-x86_64/egg/core
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/blackhole.py to blackhole.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/crypter.py to crypter.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/grider.py to grider.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/sniper.py to sniper.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/overlap.py to overlap.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/droper.py to droper.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoudp.py to ufoudp.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/pinger.py to pinger.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/monlist.py to monlist.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/uforst.py to uforst.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoack.py to ufoack.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/fraggle.py to fraggle.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ufonet-1.8-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.8-py3.11.egg
removing '/usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg' (and everything under it)
creating /usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg
Extracting ufonet-1.8-py3.11.egg to /usr/local/lib/python3.11/dist-packages
ufonet 1.8 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python3.11/dist-packages/ufonet-1.8-py3.11.egg
Processing dependencies for ufonet==1.8
Searching for pycrypto>=2.6.1
Reading https://pypi.org/simple/pycrypto/
Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#sha256=f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1.tar.gz
Writing /tmp/easy_install-mxcyaaf5/pycrypto-2.6.1/setup.cfg
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mxcyaaf5/pycrypto-2.6.1/egg-dist-tmp-vv4yjzga
/usr/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py:661: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
In file included from /usr/include/python3.11/Python.h:86,
                 from src/_fastmath.c:31:
/usr/include/python3.11/cpython/pytime.h:208:60: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  208 | PyAPI_FUNC(int) _PyTime_FromTimespec(_PyTime_t *tp, struct timespec *ts);
      |                                                            ^~~~~~~~
/usr/include/python3.11/cpython/pytime.h:213:56: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  213 | PyAPI_FUNC(int) _PyTime_AsTimespec(_PyTime_t t, struct timespec *ts);
      |                                                        ^~~~~~~~
/usr/include/python3.11/cpython/pytime.h:217:63: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
  217 | PyAPI_FUNC(void) _PyTime_AsTimespec_clamp(_PyTime_t t, struct timespec *ts);
      |                                                               ^~~~~~~~
src/_fastmath.c:33:10: fatal error: longintrepr.h: No such file or directory
   33 | #include <longintrepr.h>                                /* for conversions */
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

**Comment by epsylon** [comment]
related: https://github.com/aio-libs/aiohttp/issues/6600
