### ISSUE TITLE
Unable to download zombies

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#439]
[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

**Comment by epsylon** [comment]
===========================================================================

[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX READY!] ;-)
------------

[Info] Zombies: 1074
[Info] Droids : 13
[Info] Aliens : 10
[Info] UCAVs  : 10
[Info] X-RPCs : 64
[Info] DNSs   : 11562
[Info] NTPs   : 29
[Info] SNMPs  : 10

[Info] [AI] Congratulations!. Total downloaded: 12772
------------

[AI] Do you want to merge ONLY the new 'troops' into your army? (Y/n)

**Comment by epsylon** [comment]
@MiChaelinzo maybe your IP was temporarily banned... or server was unable to complete your request. 

Try again later!

**Comment by MiChaelinzo** [comment]
I think the IP: 46.163.118.220 is down because I tried using it again and using a VPN/TOR

```
[AI] Downloading list of [Zombies] from [Private] server: 46.163.118.220 ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]


```

**Comment by MiChaelinzo** [comment]
Alright I fixed it I tried using anonsurf TOR: 
```

[AI] Downloading list of [Zombies] from [Community] server ...

======================

[AI] Trying [Blackhole] [Server]: 46.163.118.220

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX READY!] ;-)
------------

[Info] Zombies: 1074
[Info] Droids : 13
[Info] Aliens : 10
[Info] UCAVs  : 10
[Info] X-RPCs : 64
[Info] DNSs   : 11562
[Info] NTPs   : 29
[Info] SNMPs  : 10

[Info] [AI] Congratulations!. Total downloaded: 12772
------------

[AI] Do you want to merge ONLY the new 'troops' into your army? (Y/n)Y
-------------------------

[Info] [AI] Botnet updated! -> ;-)

```
