### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by DannyBrock123** [epsylon/ufonet#440]
I installed everything but idk what to do now

**Comment by epsylon** [comment]
@DannyBrock123 you can start by reading the documentation (it has examples of everything):

https://github.com/epsylon/ufonet/blob/master/docs/README.txt

Or reviewing the examples provided on help:

**python ufonet --examples**

**Comment by greenfelin** [comment]
> I installed everything but idk what to do now

Bro, help me out if ur OS is Linux. I'm new and need help with UFONET asap with Linux kernel

**Comment by epsylon** [comment]
RTFM, bro.

**Comment by greenfelin** [comment]
> RTFM, bro.

Lol, noted man. But imma still contact you if i ran into any major bumps aight
