### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Heyo7726** [epsylon/ufonet#441]
Is there any discord server of ufonet? just for support.
Also can i install it on windows 10?

**Comment by dontbanmeplz** [comment]
no and there will never be a discord server

and yes you can use on windows with wsl or windows subsystem for linux, look it up

**Comment by Heyo7726** [comment]
> no and there will never be a discord server
> 
> and yes you can use on windows with wsl or windows subsystem for linux, look it up

Oh really cool
