### ISSUE TITLE
loic attack doesn't work

### ISSUE THREAD

**Issue by mananex** [epsylon/ufonet#444]
**L7 attacks just don't go**. I tried this command (the number of incoming requests for this site can be seen on dstat.cc):
`./ufonet -a "https://zetvideo.net" --loic 10000 --threads 500 -r 20`

 And I don't see any increase in requests during my attack. At the same time, attacking, for example, using mhddos, then all requests go and are shown on dstat.cc 

**What am I doing wrong? (translated using google translate)**

**Comment by epsylon** [comment]
@mananex Why don't you try to check the behavior of network packages on your local machine, for example, using Wireshark?
