### ISSUE TITLE
~/Desktop/ufonet$ ./ufonet  /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by SecretOsse** [epsylon/ufonet#446]
I get this error weird cuz I have installed everything
virtual-machine:~/Desktop/ufonet$ pip3 install requests
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)
virtual-machine:~/Desktop/ufonet$ pip3 install python-geoip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-geoip in /home/-/.local/lib/python3.10/site-packages (1.2)
virtual-machine:~/Desktop/ufonet$ pip3 install pygeoip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pygeoip in /home/-/.local/lib/python3.10/site-packages (0.3.2)
virtual-machine:~/Desktop/ufonet$ pip3 install pycrypto
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycrypto in /usr/local/lib/python3.10/dist-packages (2.6.1)
virtual-machine:~/Desktop/ufonet$ pip3 install pycurl
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycurl in /home/-/.local/lib/python3.10/site-packages (7.45.2)
virtual-machine:~/Desktop/ufonet$ pip3 install whois
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: whois in /home/-/.local/lib/python3.10/site-packages (0.9.27)
virtual-machine:~/Desktop/ufonet$ pip3 install scapy-python3
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scapy-python3 in /home/-/.local/lib/python3.10/site-packages (0.26)

**Comment by epsylon** [comment]
@SecretOsse this issue is related with config of your OS envirnoment, not with UFONet code.

Btw, where is the error?

Fill out the following template to make the task-fixing easier:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
