### ISSUE TITLE
مشكله 

### ISSUE THREAD

**Issue by zxcvbnm7832** [epsylon/ufonet#452]
Hello, if I came to make an attack, he says put a password, what is a password? 
![Screenshot_20230924_224944_com google android googlequicksearchbox](https://github.com/epsylon/ufonet/assets/145098489/29e49c70-9f43-4690-8c91-d553b4ab80ee)

**Comment by epsylon** [comment]
@zxcvbnm7832 Modifying traffic packets, required to carry out certain types of attacks with UFONet, requires "root" privileges. 

If you have permissions, enter **your root password**. 

If you don't have them, you can perform other types of attacks. 

For example: **python3 ufonet --examples**

```
----------------------------------------------
+_PALANTIR-3.14 (non-root): 
----------------------------------------------

 ufonet -a "http://target.com" -r "100" --threads "100" --loic "1000" --loris "1000"

```

**Comment by zxcvbnm7832** [comment]
Hello how to increase the number of zombies

في الأربعاء، ٤ أكتوبر، ٢٠٢٣ ٢:٤٩ ص psy ***@***.***> كتب:
