### ISSUE TITLE
fatal error: longintrepr.h: No such file or directory

### ISSUE THREAD

**Issue by trntyy** [epsylon/ufonet#454]
python3 setup.py install 

After a amount of text this appears:

fatal error: longintrepr.h: No such file or directory

Or the problem is because I need to download pycrypto and I get another error

pip3 install pycrypto 

After a amount of text this appears:

ERROR: Could not build wheels for pycrypto, which is required to install pyproject.toml-based projects

The problem is not my operating system. I tried from several PCs with kali linux and the exact same thing appears.

I searched several forums for the solution but it didn't help me.

I need you to tell me how I can fix it.

**Comment by epsylon** [comment]
@trntyy @JesusPanda related -> https://github.com/aio-libs/aiohttp/issues/6600

fix (not tested): https://github.com/aio-libs/aiohttp/issues/6600#issuecomment-1685286620
