### ISSUE TITLE
Some libraries are out of date breaking install

### ISSUE THREAD

**Issue by hwac121** [epsylon/ufonet#459]
Please excuse, posted to wrong repository

**Comment by hwac121** [comment]
I absolutely LOVE this application and I really hope these issues can be resolved in some way. Thanks in advance.

**Comment by AnonymousModz420** [comment]
yea this tool is straight 🔥🔥🔥🔥🔥 packing ⛽⛽⛽⛽⛽⛽ definitely keep this tool up an running thanks..🥴☑️✊🎭

-------- Original Message --------
