### ISSUE TITLE
No map

### ISSUE THREAD

**Issue by Parasimpaticki** [epsylon/ufonet#46]
When I open up the map there is no background picture of the map.
https://i.imgur.com/92LtXJj.png

**Comment by epsylon** [comment]
This is because token used for mapbox API has expired and we need a new one to correctly show map tiles. I am on it...

**Comment by epsylon** [comment]
fixed here: https://github.com/epsylon/ufonet/commit/a4531d6dfbe12f1bf1ebe57903a20d6223cfd8c0
