### ISSUE TITLE
/root/ufonet/core/ajaxmap.py

### ISSUE THREAD

**Issue by IRedScarface** [epsylon/ufonet#460]
### Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 66, in run
    res = self.pages.get(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/root/ufonet/core/webgui.py", line 4080, in get
    self.pages[page] = AjaxMap().ajax(pGet)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
        ^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-995:

I added this to fix this bug : `self.zombies = []`

```
def __init__(self):
    self.geo_db_mirror1 = 'https://turina.space/bordercheck/maps.tar.gz'  # Turina Server
    self._geoip = None
    self._geoasn = None
    self._geoipstatus = 'nomap'
    self._err = ''
    ufonet = UFONet()
    ufonet.create_options()
    try:
        self.zombies = ufonet.extract_zombies()
        aliens_army = ufonet.extract_aliens()
        droids_army = ufonet.extract_droids()
        ucavs_army = ufonet.extract_ucavs()
        rpcs_army = ufonet.extract_rpcs()
        self.zombies.extend(aliens_army)
        self.zombies.extend(droids_army)
        self.zombies.extend(ucavs_army)
        self.zombies.extend(rpcs_army)
    except:
        self.zombies = []  # I added this
        return
```
        
    **Then it gave an error like this and I couldn't do it**
  
```
  def get_next_zombie(self, name):
    if name in self.zombies:
        for z in self.zombies:
            if name == None:
                return z
            if z == name:
                name = None
        return None
    else:
        return self.zombies[0]
```
    
### Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 66, in run
    res = self.pages.get(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/root/ufonet/core/webgui.py", line 4079, in get
    from .ajaxmap import AjaxMap
  File "/root/ufonet/core/ajaxmap.py", line 201
    def get_next_zombie(self, name):
                                    ^
IndentationError: unindent does not match any outer indentation level
Exception in thread Thread-44:

**Comment by epsylon** [comment]
@IRedScarface this is beacuse **your list of zombies (zombies.txt) is empty!**

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

Try to rebuild it
