### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by masterhol** [epsylon/ufonet#461]
~/ufonet$ pip install Crypto
Requirement already satisfied: Crypto in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (1.4.1)
Requirement already satisfied: Naked in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from Crypto) (0.1.32)
Requirement already satisfied: shellescape in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from Crypto) (3.8.1)
Requirement already satisfied: requests in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from Naked->Crypto) (2.27.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/dist-packages (from Naked->Crypto) (6.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from requests->Naked->Crypto) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from requests->Naked->Crypto) (1.26.18)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/kirillstrelaev4/.local/lib/python3.9/site-packages (from requests->Naked->Crypto) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->Naked->Crypto) (3.4)
kirillstrelaev4@cloudshell:~/ufonet$ python ufonet 
Traceback (most recent call last):
  File "/home/kirillstrelaev4/ufonet/ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kirillstrelaev4/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by epsylon** [comment]
@masterhol -> https://ufonet.03c8.net/#installation

       **pip3 install pycrypto
       sudo apt-get install python3-crypto**
