### ISSUE TITLE
scapy version fuked

### ISSUE THREAD

**Issue by VastMast** [epsylon/ufonet#462]
sudo python3 ./ufonet --gui

        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

I have installed the latest version of scapy (kamene) and im getting this error help

**Comment by G3K45** [comment]
I Have the same issue with you and i remove the scapy from pip and install by pressing sudo apt-get install python3-scapy in Kali Linux 
and now works perfectly.If this dont work sorry

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/425
