### ISSUE TITLE
--auto-search Issue and questions regarding firewall and radar usage

### ISSUE THREAD

**Issue by Tig3rone** [epsylon/ufonet#469]
I've been using the tool for about a week now, and I've run the --auto-search command multiple times. However, every time I use this command, even after deleting the humans.txt and zombies.txt files in hopes of finding the same number of targets, the result always show a lower number. From what I understand, during each search, the humans.txt file is updated with potential targets that will then be tested and added to the zombies.txt file; but by removing these files, the --auto-search command should yield the same results.

Then, I wanted to ask for help regarding the radar to find nodes from which to download zombies because when using this command, the radar doesn't detect nodes.

So, I'm having quite a bit of difficulty obtaining zombies, droids, aliens, etc...

Finally, I would like to know how long it takes for a user to be removed from the firewall (since, reading some issues, a specific time is not specified, but it's only mentioned to wait for a little while / a few hours / a few days) and when a user is firewall'd until an unban request is made.

I've tested it quite awhile and probably got myself fw'd while trying to learn it.

DISCLAIMER: I'm currently learning the tool and I'm not an expert, given that, I just would like further help to understand this beautiful masterpiece of software that epsylon created. Thank you in advance to anyone who can help.

**Comment by epsylon** [comment]
should be fixed at this release: https://github.com/epsylon/ufonet/commit/aea21b3c4a8fd2f5aa8c924afa4e96eb455a4e43

try this steps:

1. git clone https://github.com/epsylon/ufonet (or python3 **ufonet --update**)
2. cd ufonet
3. sudo python3 setup.py
4. python3 ufonet
