### ISSUE TITLE
[Error] - Something wrong testing!

### ISSUE THREAD

**Issue by NickVendetta** [epsylon/ufonet#47]
This is the session:
root@kali:~/Downloads/ufonet# ./ufonet -t botnet/zombies.txt
=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

UFONet - DDoS Botnet via Web Abuse - by psy 

===========================================================================
Are 'they' alive? :-) (HEAD Check):
===================================
Trying: 1232
---------------------

[Error] - Something wrong testing!

Traceback (most recent call last):
  File "/root/Downloads/ufonet/core/main.py", line 362, in run
    test = self.testing(zombies)
  File "/root/Downloads/ufonet/core/main.py", line 1898, in testing
    reply = self.connect_zombies(zombie)
  File "/root/Downloads/ufonet/core/main.py", line 523, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
*** Error in `python': double free or corruption (out): 0xbffdf100 ***
Aborted

**Comment by epsylon** [comment]
"Community" zombies list has been updated reciently to those than only works. 
Can you try to update your list again: --download-zombies ?
Btw... "memory corruption because of excesive threads" error is detailed here:
FAQ: http://ufonet.03c8.net/FAQ.html

**Comment by NickVendetta** [comment]
after i update the zombies list the result is still same..:(

**Comment by epsylon** [comment]
Did you check the link provided to try to understand the problem?

```
This "bug" is related with how your OS is managing python threads.
 
UFONet tries to reduce as max as possible this issue by establishing a 'reaction timeout' 
for each thread created (to try to close it correctly if fails). 
```

You need to reduce your list of zombies (25-50) because your OS/Python configuration cannot manages it correctly...

Remember that by increasing number of rounds on attack you will have same impact:

./ufonet -a "http(s)://target.com/"            = 250 zombies * 1 round = 250 requests
./ufonet -a "http(s)://target.com/" -r "10" = 25 zombies * 10 rounds = 250 requests

**Comment by NickVendetta** [comment]
yes..the result is still the same after i reduce list of zombies..

**Comment by epsylon** [comment]
You reduced your list of zombies to... how many?
Are you using a computer with not so much memory? 
What OS are you running?What version of glibc? And python? And gcc?
http://stackoverflow.com/questions/24519612/error-in-usr-bin-python-double-free-or-corruption-out-0x00007f7c3c017
