### ISSUE TITLE
Can I attack another virtual machine using Ufonet?

### ISSUE THREAD

**Issue by UsernameMartinIsNotAvailable** [epsylon/ufonet#474]
How can I attack another virtual machine using Ufonet?

I've finally finish installing ufonet on my host virtual machine (i use Ubuntu 22.04 on Vmware). And now I want to attack another virtual machine (windows 10) on the same Vmware. How can I do it?

**Comment by epsylon** [comment]
If the machine is inside your LAN, you will only be able to use some Layer 7 and Layer 3 attacks, those that do not rely on NAT.
