### ISSUE TITLE
The attack is not causing any affect on the Ip address

### ISSUE THREAD

**Issue by Freer10otp** [epsylon/ufonet#475]
I am not getting any errors. The attack is running smoothly, and I have a good number of zombies. It might be the way I configured the requests, but I am not sure. I ping the ip address from before I start the attack to after and nothing changes. The ip command I use is http://1.1.1.1 for an example. Any reasons this is happening?

**Comment by epsylon** [comment]
Many factors depend on whether or not an attack is effective. From how you issue the commands to carry out the attack, to how the target machine defends itself. You should investigate much more about what may be going wrong.
