### ISSUE TITLE
hello sir i cant install infonet what i do now  plese help me 

### ISSUE THREAD

**Issue by dineepakarunarathna** [epsylon/ufonet#478]
python3 setup.py install
Traceback (most recent call last):
  File "/home/kg/ufonet/setup.py", line 17, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

after i runed this commend sudo apt-get install python3-setuptools
but displaed this error    

./ufonet
Traceback (most recent call last):
  File "/home/kg/ufonet/./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kg/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by hwac121** [comment]
Try python3 ufonet

**Comment by epsylon** [comment]
should be fixed at this release: https://github.com/epsylon/ufonet/commit/aea21b3c4a8fd2f5aa8c924afa4e96eb455a4e43

try this steps:

1. git clone https://github.com/epsylon/ufonet (or python3 **ufonet --update**)
2. cd ufonet
3. sudo python3 setup.py
4. python3 ufonet
