### ISSUE TITLE
ufonet not installing correctly

### ISSUE THREAD

**Issue by hwac121** [epsylon/ufonet#479]
I just downloaded and installed Kali to my new laptop. In my old system with an older version of Kali ufonet worked awesome. Now I cannot even get it to install. Several of the required items such as GeoIP will not install, ufonet will not run. Getting many depricated and basic error messages.

Please tell me a fix is in the works, I really hate to lose this application. I have used it for a long time now and absolutely love it!

I have followed all the directions inside the README.md file, if I need to do something additional please let me know. Thank you in advance for your time and effort.
### MY SYSTEM

- OS: Kali GNU/Linux Rolling x86_64
- Host: Inspiron 5559
- Kernel: 6.8.11-amd64
- CPU: Intel i5-6200U (4) @ 2.800GHz
- GPU: Intel Skylake GT2 [HD Graphics 520]
- Memory: 1915MiB / 7650MiB

**Comment by epsylon** [comment]
should be fixed at this release: https://github.com/epsylon/ufonet/commit/aea21b3c4a8fd2f5aa8c924afa4e96eb455a4e43

try this steps:

1. git clone https://github.com/epsylon/ufonet (or python3 **ufonet --update**)
2. cd ufonet
3. sudo python3 setup.py
4. python3 ufonet
