### ISSUE TITLE
UFOnet do not start

### ISSUE THREAD

**Issue by yario-o** [epsylon/ufonet#48]
The error : 

> Traceback (most recent call last):
>   File "./ufonet", line 10, in <module>
>     from core.main import UFONet
>   File "/home/yario/ufonet/core/main.py", line 16, in <module>
>     from herd import Herd
>   File "/home/yario/ufonet/core/herd.py", line 11, in <module>
>     import zombie
>   File "/home/yario/ufonet/core/zombie.py", line 10, in <module>
>     import pycurl, StringIO, md5, re
> ImportError: No module named pycurl

**Comment by epsylon** [comment]
`ImportError: No module named pycurl`

How to install: http://ufonet.03c8.net/#installation
