### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by hamid0901** [epsylon/ufonet#481]
==========================================
Starting round: 11 of  111
==========================================

[Info] [Droids] Attacking from: mxtoolbox.com
[Info] [Zombies] Attacking from: validator.w3.org
[Info] [Zombies] Attacking from: translate.google.com
[Info] [Aliens] Attacking from: www.checkifdown.com
[Info] [Aliens] Attacking from: www.isitwp.com
[Info] [Aliens] www.isitwp.com -> FAILED (cannot connect!)
[Info] [Aliens] Attacking from: nibbler.silktide.com
[Info] [Droids] Attacking from: www.sslshopper.com
[Info] [Droids] Attacking from: mxtoolbox.com
[Info] [X-RPCs] Attacking from: www.sbc4d.com
[Info] [UCAVs] onlineornot.com -> Target is ONLINE! -> [Keep shooting!]
Exception in thread Thread-53 (send_aliens):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/root/tools/ufonet/core/main.py", line 4446, in send_aliens
    name_alien = t.netloc
                 ^
UnboundLocalError: cannot access local variable 't' where it is not associated with a value

**Comment by epsylon** [comment]
your army is empty... try to search for some working zombies.

**Comment by hamid0901** [comment]
how to search and download? 
" ./ufonet --download-zombies " I've already tried it, but it's the same result

**Comment by epsylon** [comment]
@hamid0901 because this is a static botnet provided for testing purposes and to show how it can works. 

check in the "radar" for other working zombies provided by third-party. 

try to "federate" your mothership with other groups/individuals, etc.

these are tasks for the masters, not for coders.

**Comment by epsylon** [comment]
**UFONet was a "big button" botnet, some years ago.** 

Nowadays, fundamentally becasue InfoSec community has made a lot of advances into protect systems, for example, from Open Redirect vulnerabilities, it needs much more operation of master to conf/deploy it correctly. And some of them doesn't depends of me, as the main coder.

**Comment by hamid0901** [comment]
> 이것은 테스트 목적으로 제공되고 작동 방식을 보여주기 위해 제공되는 정적 봇넷이기 때문입니다.
> 
> "레이더"에서 타사에서 제공하는 다른 작업 좀비를 확인하십시오.
> 
> 당신의 모선을 다른 그룹/개인 등과 "연합"시키려고 노력하십시오.
> 
> 이것은 코더가 아닌 마스터를 위한 작업입니다.



> @hamid0901 because this is a static botnet provided for testing purposes and to show how it can works.
> 
> check in the "radar" for other working zombies provided by third-party.
> 
> try to "federate" your mothership with other groups/individuals, etc.
> 
> these are tasks for the masters, not for coders.

ok,what is radar? and how to federate my mothership with other groups/individuals, etc?

**Comment by epsylon** [comment]
RTFM -> https://ufonet.03c8.net/FAQ.html
