### ISSUE TITLE
I tried to increase the number of zombies through the black hole but . . . 

### ISSUE THREAD

**Issue by hamid0901** [epsylon/ufonet#485]
this is i use command (ufonet --blackhole)

┌──(root㉿kali)-[~/tools/ufonet]
└─# ./ufonet --blackhole  
                     ____                                                                        
          ||        / /\ \      ||              #===============================================#
        -(00)-     + (XX) +   -(00)-            ||                                             ||
   ||     ||   O ==*~~~~~~*== 0 ||        ||    ||  > Botnet [DDoS]   #  > Close Combat [DoS]  ||
 -(00)-     O|O  (0)  XX  (0)           -(00)-  ||                                             ||
   ||  _____ |____\| (00) |/______|D___   ||    ||     |-> ZOMBIES    #     |-> LOIC           ||
     O+!$(O)! (O)  0'----'0  (O) !(O)$!+O       ||     |-> DROIDS     #     |-> LORIS          ||
       |OO OO|  .''.( xx ).''.  |OO OO|         ||     |-> ALIENS     #     |-> UFOSYN         ||
      **+***.'.'  +X|'..'|X+  '.'***+**.        ||     |-> UCAVs      #     |-> XMAS           ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||     |-> X-RPCs     #     |-> NUKE           ||
   +(O).)-|0|  \   x| ## |x   /  |0|-(.(O)+     ||     |-> DBSTRESS   #     |-> UFOACK         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||     |-> SPRAY      #     |-> UFORST         ||
        _ | ||  '-.___||___.-'  || | _          ||     |-> SMURF      #     |-> DROPER         ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||     |-> TACHYON    #     |-> OVERLAP        ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||     |-> MONLIST    #     |-> PINGER         ||
 _  | '###  |  =| | ###### | |=  |' ###  |  _   ||     |-> FRAGGLE    #     |-> UFOUDP         ||
(0)-| |(0)| '.  0\||__**_ ||/0  .' |(0)| |-(0)  ||     |-> SNIPER     #                        ||
 *  \ '._.'   '.  | \_##_/ |  .'   '._.' /  *   ||                                             ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       #|=============================================|#
    .'_.-|            YY            |-._'.      ||                                             ||
                                                ||  -> [ UFONet: https://ufonet.03c8.net ] <-  ||
   + Class: PSYoPs / ViPR404+/(model:I^4*2) +   ||                                             ||
                                                #|=============================================|#

=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OFF)ensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

[AI] Initiating void generation sequence...

======================

[Error] [AI] Not 'abductions.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'troops.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'robots.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'drones.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'reflectors.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'warps.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'crystals.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'bosons.txt.gz' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'abductions' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'troops' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'robots' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'drones' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'reflectors' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'warps' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'crystals' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'bosons' file in /var/www/ufonet/

[Error] [AI] Cannot found any container... -> [Aborting!]

[Info] [AI] Suspend [Blackhole] with: Ctrl+z
^C
[AI] Terminating void generation sequence...

Traceback (most recent call last):
  File "/root/tools/ufonet/core/main.py", line 1527, in run
    while True: time.sleep(1)
                ^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tools/ufonet/./ufonet", line 16, in <module>
    app.run()
  File "/root/tools/ufonet/core/main.py", line 1530, in run
    app.collapse()
  File "/root/tools/ufonet/core/tools/blackhole.py", line 614, in collapse
    self.blackray.shining = False
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shining'
                                                                                  
┌──(root㉿kali)-[~/tools/ufonet]
└─# ls /var/www/ufonet/

ls: cannot access '/var/www/ufonet/': No such file or directory

what should i do?

**Comment by epsylon** [comment]
Hi @hamid0901 

To DOWNLOAD zombies from COMMUNITY server:

./ufonet --download-zombies

To DOWNLOAD zombies from ANOTHER MOTHERSHIP server:

./ufonet --donwload-from=IP

To CREATE your OWN BLACKHOLE (and share your zombies:

./ufonet --blackhole

----

CHECK THIS:
```

  *Community*:
    --deploy            Deploy data to share in '/var/www/ufonet/'
    --grider            Create a 'grider' to share 'stats/wargames/messages'
    --blackhole         Generate a 'blackhole' to share 'zombies'
    --download-nodes    Download 'zombies' from Radar
    --up-to=UPIP        Upload 'zombies' to IP (ex: --up-to '<IP>')
    --down-from=DIP     Download 'zombies' from IP (ex: --down-from '<IP>')
    --upload-zombies    Upload 'zombies' to Community
    --download-zombies  Download 'zombies' from Community
    --upload-github     Upload 'zombies' to GitHub
    --download-github   Download 'zombies' from GitHub
```
and for generate your own blackhole, this:

https://github.com/epsylon/ufonet/blob/master/docs/README_blackhole.txt
