### ISSUE TITLE
zombies are not saved

### ISSUE THREAD

**Issue by grachove** [epsylon/ufonet#488]
hello, I use "termux" and "Kali Linux" and I ran into a problem - when I save zombies, they disappear somewhere when testing and attacking them from 0 to 2, please help 🙏
![Screenshot_20241125-215653](https://github.com/user-attachments/assets/2d22bf8a-9b87-4873-8529-5ea0d92148f0)
![Screenshot_20241125-215708](https://github.com/user-attachments/assets/470324f5-ccd8-44ef-b71b-fa52978ff782)

**Comment by grachove** [comment]
sorry my question may seem silly, I'm just new to this topic.

**Comment by epsylon** [comment]
you haven't any zombies at your army -> botnet/zombies.txt
