### ISSUE TITLE
UFOnet don't start

### ISSUE THREAD

**Issue by yario-o** [epsylon/ufonet#49]
The error:

> 
> Traceback (most recent call last):
>   File "./ufonet", line 13, in <module>
>     app = UFONet()
>   File "/home/yario/ufonet/core/main.py", line 139, in __init__
>     self.ctx = ssl.create_default_context() # creating context to bypass SSL cert validation (black magic)
> AttributeError: 'module' object has no attribute 'create_default_context'

**Comment by epsylon** [comment]
That "issue" (which is a problem from your OS conf, not a UFONet code) was reported more than one time... Please, try to review previous ones so we don't repeat again and again same things:

https://github.com/epsylon/ufonet/issues/20
https://github.com/epsylon/ufonet/issues/13
[...]

'ssl.create_default_context' was added to Python > 2.7.9 -> https://docs.python.org/2/library/ssl.html

Solution: **Try to upgrade your python env..** (you need python > 2.7.9)

**Comment by peterpt** [comment]
Sorry for the massive delay on this one , i had multiple stuff to do and i never remember more to deal with this issue . Right now i am configuring a machine with all the tools i think are important to have and i went again to install ufonet , i have Python 3.2.3 and i still get the same issue ?!!

https://s23.postimg.org/qpt4u02cr/ufonet_001.png

sorry for the delay

**Comment by peterpt** [comment]
Just installed right now latest Python 3.5.2 from source code and tried ufonet , got the same situation  
https://s30.postimg.org/hrqq6kg2p/ufonet_p35.png

**Comment by epsylon** [comment]
`python > 2.7.9` 
Python 3.x is not supported.
http://stackoverflow.com/questions/3253430/python-2-x-or-3-x

**Comment by peterpt** [comment]
well , i figured that out by myself , but i had some issues .
However , i was able to fix the missed packages from python needed to run the script .
after installing the version 2.7.9 i was unable to run also the script , however the setup script in your repository was warning me of multiple missing packages .
I was able to install them and now the script is working 
https://s27.postimg.org/m40qk95g3/ufonet_004.png

**Comment by epsylon** [comment]
Very nice @peterpt !
Yep, that setup.py script was added reciently and probably needs to be more advanced. Btw, these are just "warnings" that doesn't interrupt correct functionality.
Thanks for your time to report!

**Comment by kaungmyat12345** [comment]
root@kali:~/Desktop/ufonet-master# ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/root/Desktop/ufonet-master/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
  File "/usr/local/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
root@kali:~/Desktop/ufonet-master#

**Comment by kaungmyat12345** [comment]
how solve this problem.
to open ufonet.

**Comment by kaungmyat12345** [comment]
it my error
how to solve it??????

root@kali:~/Desktop/ufonet-master# ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in  ### <module>
    from core.main import UFONet
  File "/root/Desktop/ufonet-master/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
  File "/usr/local/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
root@kali:~/Desktop/ufonet-master#

**Comment by peterpt** [comment]
https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl

&
apt-get install openssl
