### ISSUE TITLE
GeoIP problems in install

### ISSUE THREAD

**Issue by AngelShark7** [epsylon/ufonet#51]
Again i'm sorry for bother you , but i can't seem to fix the problem here : 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Lucas PC>cd/python27/scripts

C:\Python27\Scripts>pip install geoip
Collecting geoip
  Using cached GeoIP-1.3.2.tar.gz
Building wheels for collected packages: geoip
  Running setup.py bdist_wheel for geoip ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\users\\lucasp~1\\appdata\\local\\temp\\pip-build-oqmpal\\
geoip\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repla
ce('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
 c:\users\lucasp~1\appdata\local\temp\tmp_zdwefpip-wheel- --python-tag cp27:
  c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution optio
n: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'GeoIP' extension
  creating build
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  C:\Users\Lucas PC\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pytho
n\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -
Ic:\python27\PC /Tcpy_GeoIP.c /Fobuild\temp.win32-2.7\Release\py_GeoIP.obj -fno-
strict-aliasing
  cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasin
g'
  py_GeoIP.c
  py_GeoIP.c(23) : fatal error C1083: Cannot open include file: 'GeoIP.h': No su
ch file or directory
  error: command 'C:\\Users\\Lucas PC\\AppData\\Local\\Programs\\Common\\Microso
ft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for geoip
  Running setup.py clean for geoip
Failed to build geoip
Installing collected packages: geoip
  Running setup.py install for geoip ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\lucasp~1\\appdata\\local\\temp\\pip-build-oqmpal
\\geoip\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --re
cord c:\users\lucasp~1\appdata\local\temp\pip-vksqf9-record\install-record.txt -
-single-version-externally-managed --compile:
    c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    C:\Users\Lucas PC\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyt
hon\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include
 -Ic:\python27\PC /Tcpy_GeoIP.c /Fobuild\temp.win32-2.7\Release\py_GeoIP.obj -fn
o-strict-aliasing
    cl : Command line warning D9002 : ignoring unknown option '-fno-strict-alias
ing'
    py_GeoIP.c
    py_GeoIP.c(23) : fatal error C1083: Cannot open include file: 'GeoIP.h': No
such file or directory
    error: command 'C:\\Users\\Lucas PC\\AppData\\Local\\Programs\\Common\\Micro
soft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\lucasp~1\\appdata\\local\\temp\\pip-build-oqmpal\\geoip\\setup.py';f=get
attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" install --record c:\users\lucasp~1\a
ppdata\local\temp\pip-vksqf9-record\install-record.txt --single-version-external
ly-managed --compile" failed with error code 1 in c:\users\lucasp~1\appdata\loca
l\temp\pip-build-oqmpal\geoip\

C:\Python27\Scripts>

**Comment by epsylon** [comment]
stackoverflow.com/questions/22315846/install-geoip-on-windows

**Comment by AngelShark7** [comment]
Thank you , it worked perfectly

**Comment by AngelShark7** [comment]
Once i open ufonet file , it just opens and closes immediatly , im running with python

**Comment by Tosible** [comment]
Are you just double clicking the script itself or running from terminal?

**Comment by AngelShark7** [comment]
What's the code to open from terminal , just to make sure im running the correct one

**Comment by Tosible** [comment]
```python ufonet.py``` if I'm not mistaken. Or sometimes just ```ufonet.py``` by itself

**Comment by epsylon** [comment]
https://docs.python.org/2/using/windows.html
**try: python ufonet or ./ufonet**
