### ISSUE TITLE
 [Error] - Something wrong searching using: bing 

### ISSUE THREAD

**Issue by BorjanEch0** [epsylon/ufonet#52]
I get and error when i search from bing or yahoo.
i tried on multiple os and pcs it just halts with the error after a while
i would be glad if you can help.

**Comment by epsylon** [comment]
Can you share more info about your error?

**Comment by borjanj** [comment]
from the start of ufonet, ./ufonet --gui there are no error messages i go to botnet i check both check boxes for all search engines and all dorks and in the middle of search at a random time it just stops and says the error: [Error] - Something wrong searching using: bing

**Comment by epsylon** [comment]
Please, try to paste here a copy of your (verbose) output for this command:
./ufonet --sd "botnet/dorks.txt" --sa -v
Are you using a proxy?
Did you tried to receive less num results? (ex: --sn "5")?

**Comment by borjanj** [comment]
I ran the command and it succeeded with occasional error failed to connect to yahoo but when ran from gui i got this:

======================
Dork: proxy.php?url=
======================

+Victim found: http://www.kaixin001.com/login/seclogin.php?url=/interface/domain_proxy.php?type=4proxy.php?url=
------------
+Victim found: http://coolespiele.com/proxy.php?url=
------------
+Victim found: http://www.coolespiele.com/proxy.php?url=
------------
+Victim found: https://www.keihanhotels-resorts.co.jp/biwakohotel/wedding/plan/2014/proxy.php?url=
------------

======================
+Possible Zombies: 4
======================

--------------------------------------------

======================
Dork: check.cgi?url=
======================

+Victim found: http://validator.w3.org/feed/check.cgi?url=
------------
+Victim found: http://www.feedvalidator.org/check.cgi?url=
------------
+Victim found: http://www.accuride.co.jp/cgi/check.cgi?URL=C2421_20.igscheck.cgi?url=
------------
+Victim found: http://www.budogu.jp/cart/syscheck.cgi?url=
------------
+Victim found: http://www.accuride.co.jp/cgi/check.cgi?url=
------------

======================
+Possible Zombies: 5
======================

--------------------------------------------

======================
Dork: checklink?uri=
======================

[Info] - Not any possible victim(s) found for this query!

======================
+Possible Zombies: 0
======================

--------------------------------------------

======================
Dork: validator?uri=
======================

[Info] - Not any possible victim(s) found for this query!

======================
+Possible Zombies: 0
======================

--------------------------------------------

======================
Dork: redirect_uri=
======================

+Victim found: http://journals.sagepub.com/action/requestResetPassword?redirectUriredirect_uri=
------------
+Victim found: https://facebook.com/v1.0/dialog/oauth?redirect_uri=
------------
+Victim found: https://login.quicken.com/?response_type=code&amp;client_id=quicken_estore&amp;redirect_uri=
------------
+Victim found: http://www.movescount.com/?signin&amp;redirect_uri=
------------
+Victim found: https://now.bt.co/login?redirect_uri=
------------
+Victim found: https://sso.cpm.org/logout?redirect_uri=
------------
+Victim found: https://oauth.vk.com/authorize?client_id=2981351&amp;scope=friends,wall,offline&amp;redirect_uri=
------------
+Victim found: https://account.arena.net/login?redirect_uri=
------------

======================
+Possible Zombies: 8
======================

--------------------------------------------

======================
Dork: redirect=
======================

+Victim found: http://mmcredirect.millenniumsi.com/redirect=
------------
+Victim found: http://www.ski-doo.com/?redirect=
------------
+Victim found: http://store.hp.com/?jumpid=re_r11662_redirect_ETRredirect=
------------

======================
+Possible Zombies: 3
======================

--------------------------------------------

======================
Dork: referer=
======================

[Info] - Not any possible victim(s) found for this query!

======================
+Possible Zombies: 0
======================

--------------------------------------------

======================
Dork: pageurl=
======================

+Victim found: https://chp.optumrx.com/RxSolWeb/mvc/cmsContent.do?pageUrl=/CHP/OrderMedicalSupplies/DiabetesTestingSuppliespageurl=
------------
+Victim found: http://www.farmsco.com/index.html?pageURL=logout&amp;cmdpageurl=
------------
+Victim found: http://www.emirates.com/SessionHandler.aspx?pub=/english&amp;pageurl=
------------
+Victim found: https://www.pbig.ml.com/advisor/erdmanngroup.html?pageurl=
------------
+Victim found: http://ctilc.iec.cat/cis/servlet/StartCISPage?PAGEURL=/CORPUS/CorpusIndex.htmlpageurl=
------------
+Victim found: https://cms.rhides.com/servlet/StartCISPage?PAGEURL=/icms_casabac/icms_start.htmlpageurl=
------------
+Victim found: https://www.optumrx.com/RxSolWeb/mvc/cmsContent.do?pageUrl=/CHP/CustomerService/HelpTopics/AccountAccesspageurl=
------------
+Victim found: https://www.ml.com/advisor/BROUGHTON_GROUP.html?pageurl=
------------
+Victim found: https://www.pbig.ml.com/advisor/RutledgeCustodio.html?pageurl=
------------

======================
+Possible Zombies: 9
======================

--------------------------------------------

======================
Dork: returnUrl=
======================

[Info] - Not any possible victim(s) found for this query!

======================
+Possible Zombies: 0
======================

--------------------------------------------

======================
Dork: goto=
======================

+Victim found: https://goto.my.salesforce.com/goto=
------------
+Victim found: https://goto.sutterhealth.org/goto=
------------
+Victim found: https://goto.arinc.com/goto=
------------
+Victim found: https://lms.learning.hhs.gov/Saba/Web/Main/goto/RegisterLaunchCatalog?offeringId=dowbt000000000030100&amp;launchRegisteredOffering=truegoto=
------------
+Victim found: http://cheshireherald.ct.newsmemory.com/?date=20161117&amp;goTo=A1goto=
------------
+Victim found: https://goto.neopost.com/goto=
------------

======================
+Possible Zombies: 6
======================

--------------------------------------------

======================
Dork: redir=
======================

+Victim found: http://www.audible.com/redir?productid=MB_LIST_001200EG1mftredir=
------------
+Victim found: https://transurban.webex.com/media/redir/index.htmlredir=
------------
+Victim found: https://qbo.intuit.com/redir/testdriveredir=
------------
+Victim found: https://onedrive.live.com/redir?resid=A63F46BE44FF8EFB!106&amp;authkey=!AJNAEVcyCVfy4cwredir=
------------
+Victim found: https://minesider.stofa.dk/?redir=
------------
+Victim found: https://www.bestsoundtechnology.com/?redir=
------------
+Victim found: http://www.koreaschool.org/?act=member.login&amp;redir=
------------
+Victim found: http://www.telekom.de/is-bin/INTERSHOP.static/WFS/EKI-TELEKOM-Site/EKI-TELEKOM/-/special/kundencenter-app/kundencenter-app.html?wt_mc=dt_cp_toi_kundencenter_app_redir_tupredir=
------------
+Victim found: http://songlimhs.net/?act=member.login&amp;redir=
------------
+Victim found: http://www.microsoft.com/en-us/evalcenter/redir/redir=
------------

======================
+Possible Zombies: 10
======================

--------------------------------------------

======================
Dork: openfile=
======================

+Victim found: https://kynect.ky.gov/Anonymous/OpenFile?option=Dopenfile=
------------
[Error] - Something wrong searching using: bing

**Comment by epsylon** [comment]
I think it is related with how those search engines are managing multiple requests. Is not a problem of UFONet code. You can know it because you are receiving that error on different places every time that you executing tool.

I recommend you to limit max number of results. Also, you can edit botnet/dorks.txt file to have those that really are giving you results.

PD: I edited your comment to remove urls.

**Comment by borjanj** [comment]
Ok thank you for your time! you can close the issue.
