### ISSUE TITLE
Map generator error trying to place https zombies

### ISSUE THREAD

**Issue by peterpt** [epsylon/ufonet#54]
Ufonet gets an error when tries to place an https zombie , the console mode gets : 
1484540937163	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]

**Comment by epsylon** [comment]
This is a warning (not an error) and it is related with the addons of your browser (probably Firefox). This is not related with UFONet code.
