### ISSUE TITLE
[Error] - Something wrong searching using: bing

### ISSUE THREAD

**Issue by Occupy4Elephants** [epsylon/ufonet#55]
[Error] - Something wrong searching using: bing

I'm getting their error when trying to find zombies.  I selected the option to just use yahoo and received the same error [Error]- Something wrong searching using: yahoo.

The OS I am running Ufonet on is the latest edition of Kali  (not on a VM)

Thank you

**Comment by epsylon** [comment]
Which search query (dork) are you using?
Not any error here trying:  ./ufonet -s 'proxy.php?url=' --sa

Total zombies found: 10

**Comment by Occupy4Elephants** [comment]
I am using the dork list that's included.  It gives the same error when I enter an individual query though too.  Hmmm I wonder wth

**Comment by epsylon** [comment]
Are you using any proxy?

**Comment by antonixus** [comment]
Same error [Error] - Something wrong searching using: bing
No proxy.
If i choose another se i had error too
[Error] - Something wrong searching using: yahoo

**Comment by epsylon** [comment]
Can you provide us an output results (with hidden IPs please) of your results. 

Please try it by using -v option on your command. 

Also to have more detailed exit, you can edit **main.py** on **line 29**, changing:
DEBUG = 0
to 
DEBUG = 1
