### ISSUE TITLE
Cant connect to tor

### ISSUE THREAD

**Issue by grundyr** [epsylon/ufonet#56]
no matter what i try i keep getting the same problem.
i hope someone could help me out, i have tried allot of tutorials as well.

the error: http://prntscr.com/e4yae6

**Comment by Tosible** [comment]
The most common OS in the world is Windows (so I'll assume you're using Windows), if so, all you need is Tor browser up and set to 127.0.0.1:9150

Also, this might help you #42

**Comment by anonymousmask** [comment]
@epsylon 

how to fix this 

Sending request to: https://check.torproject.org

It seems that Tor is not properly set.

Your IP address appears to be: 112.198.69.98

root@localhost:~/ufonet#



im using gnu root debian on android




thanks
