### ISSUE TITLE
When i test UFOnet on my site, traffics are not reflected on my site.

### ISSUE THREAD

**Issue by takethepiracydown** [epsylon/ufonet#57]
I've set everything right. I've got 2000 plus bots. But, when I test on my site, traffics are not reflected on my site.

**Comment by epsylon** [comment]
Are you searching on proper logs?
Which webserver are you using (apache, nginx,...)?

**Comment by takethepiracydown** [comment]
I'm using apache server. I've set everything done. When  I execute ./ufonet -a example.com, all the bots get connected and then it shows 
[ Info] Firing from: http://45.55.201.25/xmlrpc.php
[Error] X-RPC: http://45.55.201.25/xmlrpc.php -> FAILED (cannot connect!)]

What was my mistake? sorry, I'm newbie

**Comment by epsylon** [comment]
I see, you are mixing a lot of stuff.
Firstly, if you have apache server (for example over a *unix system) you should take a look to the correct logs of your website. For example, it can found at some systems on: /var/logs/apache2/access.logs
Review where is your project on server and where are correct paths to logs.

 [Error] X-RPC: http://45.55.201.25/xmlrpc.php -> FAILED (cannot connect!)]
This is related with that this concrete bot is not working correctly. Maybe this IP hasn't more xmlrpc, it is using a patched wordpress and so on. You can remove it from: botnet/rpcs.txt file.
