### ISSUE TITLE
cant run it - Import Error

### ISSUE THREAD

**Issue by xltitanlee** [epsylon/ufonet#59]
Hi Guys,

Please excuse my very noobness on this
When I type ufonet it came:

Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 9, in <module>
    load_entry_point('ufonet==0.8', 'gui_scripts', 'ufonet')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 357, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2394, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2108, in load
ImportError: No module named UFONet

here is my info 
OS : Centos6 x64
Selinux : on
CPU : intel haswell  x64
RAM:8gb
Python : 2.7.13

what could I be doing wrong?

**Comment by xltitanlee** [comment]
BTW here is my PiP have : 
pip install lxml 
pip install geoip 
pip install requests
pip install pycrypto
pip install pycurl

here is my RPM pack : 
upstart-0.6.5-12.el6_4.1.x86_64
setup-2.8.14-20.el6.noarch
nss-softokn-freebl-3.14.3-3.el6_4.x86_64
basesystem-10.0-4.el6.noarch
bash-4.1.2-15.el6_4.x86_64
ncurses-base-5.7-3.20090208.el6.x86_64
nspr-4.9.5-2.el6_4.x86_64
nss-softokn-3.14.3-3.el6_4.x86_64
nss-3.14.3-4.el6_4.x86_64
libcap-2.16-5.5.el6.x86_64
selinux-policy-3.7.19-195.el6_4.12.noarch
info-4.13a-8.el6.x86_64
kernel-2.6.32-358.14.1.el6.x86_64
popt-1.13-7.el6.x86_64
nss-tools-3.14.3-4.el6_4.x86_64
libacl-2.2.49-6.el6.x86_64
make-3.81-23.el6.x86_64
db4-4.7.25-17.el6.x86_64
wget-1.12-8.el6.x86_64
libGeoIP1-1.5.1-4.1.x86_64
libgcc-4.4.7-17.el6.x86_64
gamin-0.1.10-9.el6.x86_64
texlive-texmf-2007-39.el6_7.noarch
shadow-utils-4.1.4.2-13.el6.x86_64
tzdata-2016j-1.el6.noarch
readline-6.0-4.el6.x86_64
glibc-2.12-1.192.el6.x86_64
sqlite-3.6.20-1.el6.x86_64
python-2.6.6-66.el6_8.x86_64
file-libs-5.04-15.el6.x86_64
perl-libs-5.10.1-141.el6_7.1.x86_64
dbus-libs-1.2.24-7.el6_3.x86_64
perl-Module-Pluggable-3.90-141.el6_7.1.x86_64
grep-2.6.3-3.el6.x86_64
perl-5.10.1-141.el6_7.1.x86_64
cyrus-sasl-lib-2.1.23-13.el6_3.1.x86_64
libjpeg-turbo-1.2.1-3.el6_5.x86_64
libpng-1.2.49-2.el6_7.x86_64
xz-libs-4.999.9-0.3.beta.20091007git.el6.x86_64
libselinux-2.0.94-7.el6.x86_64
expat-2.0.1-11.el6_2.x86_64
krb5-libs-1.10.3-57.el6.x86_64
bzip2-1.0.5-7.el6_0.x86_64
libICE-1.0.6-1.el6.x86_64
libtiff-3.9.4-21.el6_8.x86_64
cpio-2.10-11.el6_3.x86_64
libfontenc-1.1.2-3.el6.x86_64
sysvinit-tools-2.87-4.dsf.el6.x86_64
xorg-x11-font-utils-7.2-11.el6.x86_64
urw-fonts-2.4-11.el6.noarch
python-imaging-1.1.6-19.el6.x86_64
libnih-1.0.1-7.el6.x86_64
libss-1.41.12-22.el6.x86_64
file-5.04-15.el6.x86_64
libcom_err-devel-1.41.12-22.el6.x86_64
gmp-4.3.1-7.el6_2.2.x86_64
python-pygments-1.1.1-1.el6.noarch
libutempter-1.1.5-4.1.el6.x86_64
python-jinja2-2.2.1-2.el6_5.x86_64
vim-minimal-7.2.411-1.8.el6.x86_64
gnutls-2.8.5-19.el6_7.x86_64
net-tools-1.60-110.el6_2.x86_64
netpbm-10.47.05-11.el6.x86_64
tar-1.23-11.el6.x86_64
pixman-0.32.8-1.el6.x86_64
cpp-4.4.7-17.el6.x86_64
pinentry-0.7.6-6.el6.x86_64
libXau-1.0.6-4.el6.x86_64
binutils-2.20.51.0.2-5.36.el6.x86_64
avahi-libs-0.6.25-15.el6_8.1.x86_64
which-2.19-6.el6.x86_64
ppl-0.10.2-11.el6.x86_64
dash-0.5.5.1-4.el6.x86_64
libgomp-4.4.7-17.el6.x86_64
groff-1.18.1.4-21.el6.x86_64
poppler-data-0.4.0-1.el6.noarch
libX11-common-1.6.3-2.el6.noarch
cracklib-2.8.16-4.el6.x86_64
libXt-1.1.4-6.1.el6.x86_64
cairo-1.8.8-6.el6_6.x86_64
ghostscript-8.70-21.el6_8.1.x86_64
redhat-logos-60.0.14-12.el6.centos.noarch
texlive-texmf-errata-fonts-2007-7.1.el6.noarch
libpciaccess-0.13.1-2.el6.x86_64
libselinux-devel-2.0.94-7.el6.x86_64
texlive-texmf-errata-dvips-2007-7.1.el6.noarch
texlive-texmf-fonts-2007-39.el6_7.noarch
libuser-0.56.13-5.el6.x86_64
texlive-dvips-2007-60.el6_7.x86_64
pciutils-libs-3.1.10-2.el6.x86_64
texlive-texmf-latex-2007-39.el6_7.noarch
mingetty-1.08-5.el6.x86_64
tex-preview-11.85-10.el6.noarch
kernel-headers-2.6.32-642.15.1.el6.x86_64
libssh2-1.4.2-1.el6.x86_64
glibc-devel-2.12-1.192.el6.x86_64
openssl-devel-1.0.1e-48.el6_8.4.x86_64
rpm-4.8.0-32.el6.x86_64
python-sphinx-0.6.6-2.el6.noarch
gpgme-1.1.8-3.el6.x86_64
libselinux-utils-2.0.94-7.el6.x86_64
fipscheck-lib-1.2.0-7.el6.x86_64
pyOpenSSL-0.13.1-2.el6.x86_64
ustr-1.0.4-9.1.el6.x86_64
unzip-6.0-4.el6.x86_64
gdbm-1.8.0-36.el6.x86_64
libxml2-2.7.6-21.el6_8.1.x86_64
libgcrypt-1.4.5-12.el6_8.x86_64
yum-metadata-parser-1.1.2-16.el6.x86_64
libxml2-devel-2.7.6-21.el6_8.1.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
automake-1.11.1-4.el6.noarch
python-pycurl-7.19.0-8.el6.x86_64
libgpg-error-devel-1.7-4.el6.x86_64
yum-plugin-fastestmirror-1.1.30-14.el6.noarch
libxslt-devel-1.1.26-2.el6_3.1.x86_64
slang-2.2.1-1.el6.x86_64
curl-7.19.7-52.el6.x86_64
newt-python-0.52.11-3.el6.x86_64
kbd-misc-1.15-11.el6.noarch
policycoreutils-2.0.83-19.30.el6.x86_64
iproute-2.6.32-23.el6.x86_64
udev-147-2.46.el6.x86_64
device-mapper-1.02.77-9.el6.x86_64
device-mapper-event-1.02.77-9.el6.x86_64
libdrm-2.4.39-1.el6.x86_64
kbd-1.15-11.el6.x86_64
dracut-kernel-004-303.el6.noarch
openssh-5.3p1-84.1.el6.x86_64
postfix-2.6.6-2.2.el6_1.x86_64
cronie-1.4.4-7.el6.x86_64
iptables-ipv6-1.4.7-9.el6.x86_64
dhcp-common-4.1.1-34.P1.el6.centos.x86_64
kernel-2.6.32-358.el6.x86_64
openssh-server-5.3p1-84.1.el6.x86_64
bfa-firmware-3.0.3.1-1.el6.noarch
iwl100-firmware-39.31.5.1-1.el6.noarch
b43-openfwwf-5.2-4.el6.noarch
aic94xx-firmware-30-2.el6.noarch
iwl1000-firmware-39.31.5.1-1.el6.noarch
grub-0.97-81.el6.x86_64
passwd-0.77-4.el6_2.2.x86_64
audit-2.2-2.el6.x86_64
acl-2.2.49-6.el6.x86_64
ql2400-firmware-5.08.00-1.el6.noarch
ql2100-firmware-1.19.38-3.1.el6.noarch
libertas-usb8388-firmware-5.110.22.p23-3.1.el6.noarch
ql2500-firmware-5.08.00-1.el6.noarch
zd1211-firmware-1.4-4.el6.noarch
rt61pci-firmware-1.2-7.el6.noarch
ql2200-firmware-2.02.08-3.1.el6.noarch
ipw2100-firmware-1.3-11.el6.noarch
ipw2200-firmware-3.1-4.el6.noarch
gpg-pubkey-c105b9de-4e0fd3a3
coreutils-libs-8.4-19.el6_4.2.x86_64
openldap-2.4.23-32.el6_4.1.x86_64
libblkid-2.17.2-12.9.el6_4.3.x86_64
iputils-20071127-17.el6_4.x86_64
dbus-glib-0.86-6.el6.x86_64
vim-common-7.2.411-1.8.el6.x86_64
vim-enhanced-7.2.411-1.8.el6.x86_64
kernel-2.6.32-358.11.1.el6.x86_64
filesystem-2.4.30-3.el6.x86_64
ca-certificates-2010.63-3.el6_1.5.noarch
nss-util-3.14.3-3.el6_4.x86_64
nss-sysinit-3.14.3-4.el6_4.x86_64
ncurses-libs-5.7-3.20090208.el6.x86_64
libattr-2.4.44-7.el6.x86_64
initscripts-9.03.38-1.el6.centos.2.x86_64
zlib-1.2.3-29.el6.x86_64
kernel-firmware-2.6.32-358.14.1.el6.noarch
audit-libs-2.2-2.el6.x86_64
selinux-policy-targeted-3.7.19-195.el6_4.12.noarch
chkconfig-1.3.49.3-2.el6.x86_64
openssl-1.0.1e-48.el6_8.4.x86_64
pkgconfig-0.23-9.1.el6.x86_64
libsepol-2.0.41-4.el6.x86_64
libGeoIP-devel-1.5.1-54.1.x86_64
glib2-2.22.5-7.el6.x86_64
texlive-texmf-errata-2007-7.1.el6.noarch
sed-4.2.1-10.el6.x86_64
texlive-texmf-errata-latex-2007-7.1.el6.noarch
bzip2-libs-1.0.5-7.el6_0.x86_64
glibc-common-2.12-1.192.el6.x86_64
libstdc++-4.4.7-3.el6.x86_64
python-libs-2.6.6-66.el6_8.x86_64
gawk-3.1.7-10.el6.x86_64
perl-Pod-Escapes-1.04-141.el6_7.1.x86_64
libudev-147-2.46.el6.x86_64
perl-version-0.77-141.el6_7.1.x86_64
pcre-7.8-6.el6.x86_64
perl-Pod-Simple-3.13-141.el6_7.1.x86_64
lua-5.1.4-4.1.el6.x86_64
libcom_err-1.41.12-22.el6.x86_64
libidn-1.18-2.el6.x86_64
freetype-2.3.11-17.el6.x86_64
fontconfig-2.8.0-5.el6.x86_64
elfutils-libelf-0.152-1.el6.x86_64
keyutils-libs-1.4-5.el6.x86_64
libgpg-error-1.7-4.el6.x86_64
kpathsea-2007-60.el6_7.x86_64
findutils-4.4.2-6.el6.x86_64
libSM-1.2.1-2.el6.x86_64
checkpolicy-2.0.22-1.el6.x86_64
jasper-libs-1.900.1-16.el6_6.3.x86_64
tcp_wrappers-libs-7.6-57.el6.x86_64
libXfont-1.5.1-2.el6.x86_64
pth-2.0.7-9.3.el6.x86_64
ghostscript-fonts-5.50-23.2.el6.noarch
device-mapper-persistent-data-0.1.4-1.el6.x86_64
keyutils-libs-devel-1.4-5.el6.x86_64
grubby-7.0.15-3.el6.x86_64
python-docutils-0.6-1.el6.noarch
e2fsprogs-libs-1.41.12-22.el6.x86_64
python-setuptools-0.6.10-3.el6.noarch
libusb-0.1.12-23.el6.x86_64
python-babel-0.9.4-5.1.el6.noarch
MAKEDEV-3.24-6.el6.x86_64
libtasn1-2.3-6.el6_5.x86_64
procps-3.2.8-25.el6.x86_64
lcms-libs-1.19-1.el6.x86_64
psmisc-22.6-15.el6_0.1.x86_64
openjpeg-libs-1.3-11.el6.x86_64
db4-utils-4.7.25-17.el6.x86_64
mpfr-2.4.1-6.el6.x86_64
psutils-1.17-34.el6.x86_64
diffutils-2.8.1-28.el6.x86_64
libxcb-1.11-2.el6.x86_64
m4-1.4.13-5.el6.x86_64
cups-libs-1.4.2-74.el6.x86_64
cloog-ppl-0.15.7-1.2.el6.x86_64
ncurses-5.7-3.20090208.el6.x86_64
centos-indexhtml-6-2.el6.centos.noarch
less-436-10.el6.x86_64
poppler-0.12.4-10.el6.x86_64
libX11-1.6.3-2.el6.x86_64
cracklib-dicts-2.8.16-4.el6.x86_64
libXrender-0.9.8-2.1.el6_8.1.x86_64
pam-1.1.1-13.el6.x86_64
libXext-1.3.3-1.el6.x86_64
hwdata-0.233-7.9.el6.noarch
netpbm-progs-10.47.05-11.el6.x86_64
plymouth-scripts-0.8.3-27.el6.centos.x86_64
libsepol-devel-2.0.41-4.el6.x86_64
logrotate-3.7.8-16.el6.x86_64
krb5-devel-1.10.3-57.el6.x86_64
texlive-texmf-dvips-2007-39.el6_7.noarch
texlive-2007-60.el6_7.x86_64
libcap-ng-0.6.4-3.el6_0.1.x86_64
texlive-utils-2007-60.el6_7.x86_64
ethtool-3.5-1.el6.x86_64
texlive-latex-2007-60.el6_7.x86_64
zlib-devel-1.2.3-29.el6.x86_64
glibc-headers-2.12-1.192.el6.x86_64
gcc-4.4.7-17.el6.x86_64
rpm-libs-4.8.0-32.el6.x86_64
lynx-2.8.6-27.el6.x86_64
gnupg2-2.0.14-4.el6.x86_64
e2fsprogs-1.41.12-22.el6.x86_64
python-devel-2.6.6-66.el6_8.x86_64
fipscheck-1.2.0-7.el6.x86_64
lrzsz-0.12.20-27.1.el6.x86_64
libsemanage-2.0.43-4.2.el6.x86_64
bzip2-devel-1.0.5-7.el6_0.x86_64
libffi-3.0.5-3.2.el6.x86_64
libcurl-7.19.7-52.el6.x86_64
libxslt-1.1.26-2.el6_3.1.x86_64
rpm-python-4.8.0-32.el6.x86_64
autoconf-2.63-5.1.el6.noarch
pygpgme-0.1-18.20090824bzr68.el6.x86_64
libidn-devel-1.18-2.el6.x86_64
python-urlgrabber-3.9.1-8.el6.noarch
libgcrypt-devel-1.4.5-12.el6_8.x86_64
yum-3.2.29-40.el6.centos.noarch
libcurl-devel-7.19.7-52.el6.x86_64
newt-0.52.11-3.el6.x86_64
libxml2-python-2.7.6-21.el6_8.1.x86_64
plymouth-core-libs-0.8.3-27.el6.centos.x86_64
centos-release-6-4.el6.centos.10.x86_64
iptables-1.4.7-9.el6.x86_64
device-mapper-libs-1.02.77-9.el6.x86_64
device-mapper-event-libs-1.02.77-9.el6.x86_64
lvm2-libs-2.02.98-9.el6.x86_64
plymouth-0.8.3-27.el6.centos.x86_64
dracut-004-303.el6.noarch
rsyslog-5.8.10-6.el6.x86_64
cyrus-sasl-2.1.23-13.el6_3.1.x86_64
cronie-anacron-1.4.4-7.el6.x86_64
crontabs-1.10-33.el6.noarch
dhclient-4.1.1-34.P1.el6.centos.x86_64
system-config-firewall-base-1.2.27-5.el6.noarch
lvm2-2.02.98-9.el6.x86_64
iwl5150-firmware-8.24.2.2-1.el6.noarch
iwl6050-firmware-41.28.5.1-2.el6.noarch
iwl6000g2a-firmware-17.168.5.3-1.el6.noarch
iwl6000-firmware-9.221.4.1-1.el6.noarch
authconfig-6.1.12-13.el6.x86_64
efibootmgr-0.5.4-10.el6.x86_64
sudo-1.8.6p3-7.el6.x86_64
attr-2.4.44-7.el6.x86_64
iwl5000-firmware-8.83.5.1_1-1.el6_1.1.noarch
ivtv-firmware-20080701-20.2.noarch
xorg-x11-drv-ati-firmware-6.99.99-1.el6.noarch
atmel-firmware-1.3-7.el6.noarch
iwl4965-firmware-228.61.2.24-2.1.el6.noarch
iwl3945-firmware-15.32.2.9-4.el6.noarch
rt73usb-firmware-1.8-7.el6.noarch
ql23xx-firmware-3.03.27-3.1.el6.noarch
rootfiles-8.1-6.1.el6.noarch
coreutils-8.4-19.el6_4.2.x86_64
libuuid-2.17.2-12.9.el6_4.3.x86_64
util-linux-ng-2.17.2-12.9.el6_4.3.x86_64
kernel-2.6.32-358.6.2.el6.x86_64
mysql-libs-5.1.69-1.el6_4.x86_64
gzip-1.3.12-19.el6_4.x86_64
gpm-libs-1.20.6-12.el6.x86_64
module-init-tools-3.9-21.el6_4.x86_64

**Comment by epsylon** [comment]
Look something wrong on your path. You are executing ufonet from here:   "/usr/local/bin/ufonet" so cannot found main UFONet code.

Try to run tool from same path than package. For example:
1) unzip ufonet-master.zip
2) cd ufonet
3) ./ufonet (or python ufonet.py)
