### ISSUE TITLE
Error when running ./ufonet

### ISSUE THREAD

**Issue by CrimedTK** [epsylon/ufonet#60]
I get this error, i did not before, but after i did this. i was getting the GEOIP error so i did this command and it broke it how do i fix it?
"sudo apt-get install python-pycurl python-geoip python-crypto"

Code: https://hastebin.com/suwizegute.sql

Im kinda new to this stuff, so some specific steps would help, thanks <3
Operation System: Kali Linux

**Comment by epsylon** [comment]
`ImportError: No module named _ssl`

http://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl

check that you are using: **python > 2.7.9**

try this: **sudo apt-get install libssl-dev** 
---------
How to install: http://ufonet.03c8.net/#installation

If you are using Kali, remember also to launch this commands:

       pip install geoip 
       pip install requests
       pip install pycrypto

**Comment by CrimedTK** [comment]
is the setup.py the python 2.7.9 install file?
also i still get the error, im just going to reinstall linux because it was working before

**Comment by CrimedTK** [comment]
Reinstalled now working
