### ISSUE TITLE
ufonet error

### ISSUE THREAD

**Issue by joselini** [epsylon/ufonet#61]
Hello very good to all I wanted to do a query i am trying to get ufonet..but i several errors since I am from Spain and i do not know much English I think it's a little more complicated apart that I am fond of computer security left them a photo or the lines of what I said when I run both with or without proxychains tor and tor.to k without tor i launches the messages from the end of the attack.MANY THANKS

[Error] Local port: NO | Report :Something wrong on your port:8080

[Error] From exterior: NO | Report:Cannot access to mothership on -public- url:

[Error] Your NAT/Network is not correctly configurated

These are the errors that i get when it launched the attack with tor and Proxychains

![img_20170304_022047](https://cloud.githubusercontent.com/assets/26199487/23587094/c40fca64-01a4-11e7-851b-a16da3e28f55.jpg)

This is when it launched the attack without using Tor and proxichayns

my email..... joselini1974@hotmail.com..........thank

**Comment by epsylon** [comment]
Hi,
This is because your are trying **--attack-me** test from TOR so zombies cannot found you (for NAT traffic to your mothership). You cannot launch that test by using a proxy.
Cheers.

**Comment by joselini** [comment]
Hello very good i don't know why i have closed the question i don't know if I made a mistake because as I said I am from Spain and i have to go with the translator for not mistaken

________________________________
De: psy <notifications@github.com>
Enviado: domingo, 5 de marzo de 2017 15:54:50
Para: epsylon/ufonet
Cc: joselini; Author
Asunto: Re: [epsylon/ufonet] ufonet error (#61)


Closed #61<https://github.com/epsylon/ufonet/issues/61>.

**Comment by joselini** [comment]
Excuse me because right now between and not gave the translator and something I added and i did wrong...sorry..." I said before if i did something wrong too so I closed the comment

________________________________
De: psy <notifications@github.com>
Enviado: domingo, 5 de marzo de 2017 15:54
Para: epsylon/ufonet
Cc: joselini; Author
Asunto: Re: [epsylon/ufonet] ufonet error (#61)


Closed #61<https://github.com/epsylon/ufonet/issues/61>.

**Comment by epsylon** [comment]
@joselini no te funciona utilizando TOR, porque estás usando la opción --attack-me, que se utiliza para que los zombies te "ataquen" a ti. Es una manera que tiene UFONet de comprobar que actuán de manera correcta, así como, de obtener algunas estadísticas.

Para poder usar esa opción, necesitas además tener bien configurada la NAT de tu router (en caso de que lo hagas desde casa). Tienes que poder tener una IP pública para la "nave madre" de UFOnet, donde los zombies se conecten. Por tanto, si usas un proxy, por ejemplo TOR, los zombies van a conectarse a ese lugar y obviamente, al no encontrar ahí la "nave madre", pues falla. 

Aquí te dice porque lo hace:

**[Error] Your NAT/Network is not correctly configurated**

En resumen, no puedes usar la opción para probar tu botnet --attack-me desde un proxy externo.

**Comment by joselini** [comment]
Many thanks for the quick reply and the detail of send it to me in Spanish ... thanks ... if I do it from my computer to a page of my cousin who sells dogs. Gave me the permission to do tests. I do everything from a virtual machine vmware a card alfha awus036nha and kali linux 2.0 last version .la atacck me option refers to the photo that I send. Also the browser that has kali firefox I do not know how Configure it in the advanced NAT or RED part of Spanish. Then to launch an attack should I leave tor and proxychains? Or how could you configure it well? I told you the ip publish I understood it but what I did not understand is if I should put it at the time of acer the attack I apologize for so many questions because I saw many tutorials but I think they were not the correct ones .. could send me a tutorial that is correct ?

THANK YOU VERY MUCH



________________________________
De: psy <notifications@github.com>
Enviado: lunes, 6 de marzo de 2017 14:05
Para: epsylon/ufonet
Cc: joselini; Mention
Asunto: Re: [epsylon/ufonet] ufonet error (#61)


@joselini<https://github.com/joselini> no te funciona utilizando TOR, porque estás usando la opción --attack-me, que se utiliza para que los zombies te "ataquen" a ti. Es una manera que tiene UFONet de comprobar que actuán de manera correcta, así como, de obtener algunas estadísticas.

Para poder usar esa opción, necesitas además tener bien configurada la NAT de tu router (en caso de que lo hagas desde casa). Tienes que poder tener una IP pública para la "nave madre" de UFOnet, donde los zombies se conecten. Por tanto, si usas un proxy, por ejemplo TOR, los zombies van a conectarse a ese lugar y obviamente, al no encontrar ahí la "nave madre", pues falla.

Aquí te dice porque lo hace:

[Error] Your NAT/Network is not correctly configurated

En resumen, no puedes usar la opción para probar tu botnet --attack-me desde un proxy externo.

**Comment by epsylon** [comment]
> Then to launch an attack should I leave tor and proxychains?

**-a** -> you can attack with or without Tor
**--attack-me** -> you only can try this test without Tor (and a correct NAT conf)

http://ufonet.03c8.net/FAQ.html

**Comment by joselini** [comment]
Thank you for your quick response.i apologize if any word not put it well in english .I just wanted to ask the last question sent him a photo that is the firefox browser in kali linux 2.0 in NAT as i have it configured because this step i mess..once again many thanks not upset since
![img_20170307_072133](https://cloud.githubusercontent.com/assets/26199487/23644564/2f4af3a8-0308-11e7-8717-de9633ceef8d.jpg)
