### ISSUE TITLE
Missing dependency on docs

### ISSUE THREAD

**Issue by yleme** [epsylon/ufonet#62]
Hello, to install on Debian-based systems (ex: Ubuntu) it also needs the requests libs, so it's needed to run as follow:

```sudo apt-get install python-requests```

Thanks in advance.

**Comment by epsylon** [comment]
Hi, for Ubuntu, that dependency it is documented but by using pip:

https://ufonet.03c8.net/#docs
https://ufonet.03c8.net/FAQ.html

```
 On other systems such as: Kali, Ubuntu, ArchLinux, ParrotSec, Fedora, etc... also run:

       pip install geoip 
       **pip install requests**
       pip install pycrypto
```
