### ISSUE TITLE
On ubuntu cant connected to tor.

### ISSUE THREAD

**Issue by gmod74** [epsylon/ufonet#63]
I am running ubuntu and no matter what I do I cant connect UFONET to tor 

=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

UFONet - DDoS Botnet via Web Abuse - by psy 

===========================================================================

Sending request to: https://check.torproject.org

Cannot reach TOR checker system!. Are you correctly connected?

**Comment by epsylon** [comment]
How are you spelling UFOnet to use tor?

**Comment by anonymousmask** [comment]
hi @epsylon how to fix this

Sending request to: https://check.torproject.org

It seems that Tor is not properly set.

Your IP address appears to be: 112.198.69.98

root@localhost:~/ufonet#



im using gnuroot debian  android please help me


thanks

**Comment by epsylon** [comment]
@anonymousmask this is not a bug... 

UFONet is telling you that you haven't configurated your Tor connection properly, on your OS.

Review how you have installed TOR, and next time, add also which command have you used for that output results. This that you wrote, haven't any sense as an issue.

**Comment by anonymousmask** [comment]
i configured my tor in my linux its say



It seems that Tor is not properly set.


i use 127.0 0.1:8118 but not work

**Comment by epsylon** [comment]
Try to change port to: 9050 (8118 is used by privoxy

**Comment by epsylon** [comment]
Try to change port to: 9050

**Comment by muricawashere** [comment]
Mine doesnt work on port 9050 do I need to configure tor at all. I have it running in the background also
