### ISSUE TITLE
Sending request to: https://check.torproject.org  It seems that Tor is not properly set.  Your IP address appears to be: 112.198.69.98  root@localhost:~/ufonet#

### ISSUE THREAD

**Issue by anonymousmask** [epsylon/ufonet#65]
hi too how to fix this im using gnuroot debian android and IDK to fix this please help

thanks

**Comment by anonymousmask** [comment]
@epsylon

**Comment by anonymousmask** [comment]
@tosible

please help

**Comment by anonymousmask** [comment]
@epsylon

**Comment by anonymousmask** [comment]
its say 
It seems that Tor is not properly set.



but i configured this i use 127.0.0.1:8118

**Comment by anonymousmask** [comment]
im using gnuroot debian

**Comment by anonymousmask** [comment]
@epsylon

**Comment by epsylon** [comment]
1. This is not a bug. UFONet is telling you that you haven't your TOR app correctly configurated.
2. You are showing your real IP on the title for this public Internet issue. Remove it, inmediately.
3. You have requested attention also on this other thread: https://github.com/epsylon/ufonet/issues/63#issuecomment-292996744
4. Please review your levels of cafeine in blood. This attitude doesn't looks healthy.

**Comment by epsylon** [comment]
Btw,
> but i configured this i use 127.0.0.1:8118
Tor is using port: 9050 (8118 is for privoxy+tor configurtions). Try to change 8118 and use 9050.

**Comment by epsylon** [comment]
Btw,
> but i configured this i use 127.0.0.1:8118
Tor is using port: 9050 (8118 is for privoxy+tor). Try to use 9050.

**Comment by epsylon** [comment]
Tor is using by default port:9050 (port 8118 is used by Privoxy). 
So, if you haven't privoxy, try to change port to: 127.0.0.1:9050

./ufonet --check-tor --proxy=http://127.0.0.1:9050

**Comment by anonymousmask** [comment]
thanks to your help  i try it later

**Comment by anonymousmask** [comment]
what do you mean about this




Please review your levels of cafeine in blood. This attitude doesn't looks healthy.

**Comment by epsylon** [comment]
Look at this thread, you are not supporting to others with this issue. You just want attention, for example, by invoking my name a lot of times...like if I haven't any other stuff on my life that to teach you how to use proxy mechanisms propertly. Don't waste my time and remove your real IP from title...

**Comment by anonymousmask** [comment]
sorry for that @epsylon

**Comment by anonymousmask** [comment]
:)

**Comment by anonymousmask** [comment]
the ip is not real  i put for example

**Comment by epsylon** [comment]
@anonymousmask no problem ;-)
Btw, remove that IP... We can have problems with terms of service from GitHub... Can you do that, please?

**Comment by anonymousmask** [comment]
ok thanks for your help

**Comment by anonymousmask** [comment]
how to edit

**Comment by epsylon** [comment]
This IP is real:

address:        4/F Globe Tlecom Plaza
address:        Pioneer cor Madisons Sts.
address:        Mandaluyong City
address:        Philippines
