### ISSUE TITLE
UFONet: My zombies arent loading in? (0/2109) Need Help!

### ISSUE THREAD

**Issue by A1Lunatic** [epsylon/ufonet#69]
I downloaded UFONet yesterday and I am trying to test my uncle's website, and every time i hit "Attack" i wait about a min and try and refresh the page but it is still up and running? I also enabled "Generate Map" and I I noticed that it does not load my zombies in at all!

Pictures below!

![zombies not loading pic](https://user-images.githubusercontent.com/29659664/27485226-e893f120-57f9-11e7-8f51-6e19a928023e.PNG) 
 
![kali linux error when running attack](https://user-images.githubusercontent.com/29659664/27485233-efa18450-57f9-11e7-8650-88b65c6ef947.PNG)

![info below when i run the attack](https://user-images.githubusercontent.com/29659664/27485234-f2007652-57f9-11e7-909d-3488000c6373.PNG)

Can anyone explain to me what the second picture means? Also, any help with be appreciated, please! I am not too technical so please explain the solution simply thanks, xd!

**Comment by epsylon** [comment]
Hi,
First time you run this feature, you need to wait a bit (a box on right-down corner provides you some debug msg about process status) until maps and geoip db are downloaded. 

But, take a look to the picture 2). You are missing a main library to complete that process: python-geoip

To fix that, you only need to spell: **sudo apt-get install python-geoip** (or pip install geoip). After that, you will start to see a plotting deployment with all your zombies.

Btw, if the map is not working doesn't means that the attack is not proceeded. It just means that the attack cannot be represented visually. You can see that on picture 3).

**Comment by Awar1234** [comment]
How to get this library?

**Comment by trollmad3** [comment]
@A1Lunatic What library are you looking for?

**Comment by epsylon** [comment]
Try:
sudo apt-get install python-geoip 
or
pip install geoip
