### ISSUE TITLE
Dorks, search engine improvement and -t dorks.txt improvement

### ISSUE THREAD

**Issue by knightgats** [epsylon/ufonet#7]
Hi Psy,

Firstly It's very sad have not properly support from you.

I have testing  from last 3 days exhaustively to ensure that tool is compliance about is supposed to perform.

The way as the tool perform searches using engines must be improved.

That`s amazing tool called INURLBR SCANNER ( it`s found here in GitHub ) that perform dorks in many engines ( is wrote in PHP ) and has many honorable features. ( Take a look )

Also, during dorks validation ( -t option ) need better improvement.

Just trying to help a better improvement of your tool which as very cool.

If you don`t want any external support for improvement let me know,  I will not bother you in any way.

Regards,

**Comment by epsylon** [comment]
Hey guy, if you gonna cry, please go to another place... 
You told me to go to IRC to talk with you as an imposition...not asking where is the best place for me.
After that, you wrote me an email, using a commercial email provider and I told you to uses GPG/MIME encryption to reply your answers and you just pass of it,
What more do you want?. 
Do you think that i am not supporting your technical problems on a good way after providing you a patch on less than 3 hours?. 
Your suggestion is to improve INURLRB dorking systme to Ufonet. Are you kidding me?...

**Comment by knightgats** [comment]
Along all years I have contributed for many tools bug/fixes and improviments of important projects that I `m sure you heard about .

Sincerely, your comments was a little aggressive than usual.
I wasn`t able to import your pgp key. 

All allegations you Did have no sense. It`s a very very sad read something like that

Best regards,

**Comment by epsylon** [comment]
I heard about a lot of projects.. but if you are sure that I am not ready to know about yours, I have nothing more to say.
Not aggresive, man. I am just telling to you that you need to be more patient to expose your probably really nice ideas and that I prefer to use another communication systems to share it. But you just not listen and comes here to say publicaly that I am not supporting you...
You have my GPG public (almost from some years ago) for example, here: https://03c8.net/gpg.php
Kisses!

**Comment by knightgats** [comment]
I was able to import from https://03c8.net/gpg.php

Your signature.asc is probably corrupt !

Sincerely, after each word you said here in your e-mail, without any respect . Better no talk anymore.

You need practice your education, learn to be polite and receive the things  in a better way.

As said before, I wish for you bests !

**Comment by epsylon** [comment]
So at the end all this comments are because you think that "probably" my GPG signature is corrupt.. and I am an evil person who is not enougth patient with your mistakes... I see. ;-)
Btw, thanks for teach me modals and education, how to be polite and how do I should recieve egoistic tasks provided by third party people that doesn't listen me when I am talking about how I feel better to expres my ideas. 
God blesh you for that knowledge and thanks for your whishes!

**Comment by knightgats** [comment]
So at the end all this comments are because you think that "probably" my
GPG signature is corrupt.. and I am an evil person who is not enougth
patient with your mistakes... I see. ;-)
> No mistake I sent you my signature and you was able to start using PGP,
BTW, I had advised you about cannot import and I received any reply.
Btw, thanks for teach me modals and education, how to be polite and how do
I should recieve egoistic tasks provided by third party people that doesn't
listen me when I am talking about how I feel better to expres my ideas.
> Welcome, just say nothing stupid like you I `m sure that was I great
demonstration.
God blesh you for that knowledge and thanks for your whishes!
> Do the best aways and don`t care about who !

Kisses **********:

**Comment by epsylon** [comment]
Hi again, knightgats!
I will take a look to your suggestions. Thanks for share it.
Parameter: "t" is used to "tests" zombies not for dorking but I understand whats your reference about. Actually it uses a really simple verification code that as you said probably can be better implemented. For example, now is checking with a static injection code to verify that the "open redirect" is happening and probably to complement it with some heuristic methods is a good idea.
Best regards,

**Comment by knightgats** [comment]
You welcome mate ! Count on me for anything you need.

Thanks 

:*

**Comment by epsylon** [comment]
Btw, to use an external API (for dorking) is not secure. Is not a good idea to provide IDs, fingerprints and metadata to Big Data IT search engines...So, I am not agree with that suggestion.

UFONet is a really nice ninja tool, so think about it. Take a look to the code more in deep and try to send better suggestions...

**Comment by knightgats** [comment]
One of the things that is blocking searches is capchas, is there any way to
improve that ? Not sure about api's , since we can use through proxies.

2016-01-06 18:23 GMT-02:00 psy <notifications@github.com>:
