### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by DarkGohst** [epsylon/ufonet#70]
open ssl is instaled
My Error:
Traceback (most recent call last):
  File "ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/phoenix/Downloads/ufonet-v0.7/ufonet/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
ImportError: No module named requests

What can i do? Thanks for support!

**Comment by epsylon** [comment]
> ImportError: No module named requests

_sudo apt-get install python-requests_ or _sudo pip install requests_

**Comment by DarkGohst** [comment]
Yeaaa ist Working, Thank you!
