### ISSUE TITLE
Ufonet NO FUNCIONA!

### ISSUE THREAD

**Issue by diegopenhap** [epsylon/ufonet#73]
![ee](https://user-images.githubusercontent.com/20995913/28925319-88b855d0-7832-11e7-821e-0fd4cfba0627.png)
  

Segun dice que el ataque fue un exito pero ni cosquillas le hace a la pagina, ayuda por favor o caso esto es una mentira?

**Comment by epsylon** [comment]
Vamos a ver, como te lo explico:
0- La captura que has subido muestra la herramienta funcionando CORRECTAMENTE. Si te crees que puedes tirar un sitio web enviando 8 peticiones, desde luego demuestras que no tienes mucha idea.
1- Respeta los hilos de otra gente (sobre todo si están en otros idiomas)
2- Deja de escribir en mil sitios "NO FUNCIONA", cuando siquiera comprendes como funciona
3- Si te parece que UFONet no cumple con lo que buscas, no lo utilices...
4- No des la turra...
