### ISSUE TITLE
[Bug] Kali Doesn’t See Libraries

### ISSUE THREAD

**Issue by zero77** [epsylon/ufonet#74]
I am running the newest ufonet and the newest version of kali Linux and I have check to see if the required libraries are installed and that kali is up to date.

But when running ufonet I get errors saying the libraries are not installed also, I am not able to use everything in ufonet like search for zombies etc because, it thinks the libraries are not installed.

Thanks

**Comment by epsylon** [comment]
Hey!
You have a python script called "setup.py" with main package that tries to install all required libs.
Try to use it like: python setup.py install
Also you have a step by step tutorial (to install libs) at FAQ: https://ufonet.03c8.net/FAQ.html

**Comment by zero77** [comment]
Thanks but, I have already tried that. After trying different things to get the search to work I have found yahoo seems to work the longest before returning an error.

These are the different  errors I am getting:


![errors](https://user-images.githubusercontent.com/16563034/29969860-0acb287e-8f1a-11e7-9b9d-2495e72cc1e9.jpg)

**Comment by epsylon** [comment]
Ok. I see.

If you are using GUI, probably you want to have geoip lib. For Kali try: pip install geoip

For whois lib, looks that is not present on sources for this version. I will commit a fix for that soon.

Thanks for your report.

**Comment by zero77** [comment]
Ok, thank you for the help.
Also I think the search engines may need updating and can you add duckduckgo.com, as a new search engine.
Thanks

**Comment by epsylon** [comment]
I will check if regex are working correctly. Are you using TOR?. 
About DuckDuckGo, it was supported until "inurl" keyword string was removed from their API, which means, not more dorking allowed.

**Comment by zero77** [comment]
thanks, no i am not using tor.
