### ISSUE TITLE
Something wrong 

### ISSUE THREAD

**Issue by DreadKIngsK** [epsylon/ufonet#76]
When I try to use ./ufonet --auto-search,it says to me something wrong (auto-searching),I have python up-to-date,with ./ufonet -s... it works but i can't do this forever.Help ?
![screenshot from 2017-09-07 12-49-00](https://user-images.githubusercontent.com/31740431/30175006-01cdfa70-93cb-11e7-94a2-6a3ae0fe6789.png)

**Comment by DreadKIngsK** [comment]
What can I do ?

**Comment by epsylon** [comment]
Is that happening always with same seach engine?

**Comment by DreadKIngsK** [comment]
No,this error occurs when I search with bing/yahoo/yandex/autosearch,I don't use proxy.

**Comment by epsylon** [comment]
Yes, I understand that. I mean, when you are launching "autosearch", you have a sequence of search engines that are announced before to start their searching process. That means that you can know exactly which search engine is failing, just following UFONet messages...  For example, on the image that you attached, you have positive results, but I cannot see which search engine is stopping the task. And remember that results are different depending of your geoip, etc.. I have check it here and is working correctly.
Try to add -v (verbose mode) to your output results.

**Comment by DreadKIngsK** [comment]
the engine which is stopping the process is bing

**Comment by DreadKIngsK** [comment]
Now when i try to use mothership for attack or botnet and sent the command to terminal from ms it says "Error Proxy Malformed !" and now when I try to search zombies it gives me errors

**Comment by epsylon** [comment]
I have made some test by using different exit nodes and I realized that Bing is blocking some IP geolocation origins that search for "instream" keywords. 
./ufonet --autosearch (and 'bing' specific dorking engine) is working correctly, for example, when using a TOR node exit located at Amsterdam.
Also regex magics for Bing (and others) are working fine...
Yandex for example is asking for some captcha when have a lot of results (more than 30), but UFONet is working correctly to exit looping processes and exposing results.
---------
"Error proxy malformed" means that you have a syntax problem. UFONet should message you with that and telling you how to fix it. Please, read tool output results before to come here and wake up to Cthulhu... ;-)
You can use a "mothership board" topic related with BUGS that you have implemented by default and in which other users also can support you.... OK?.
Thanks, btw...
