### ISSUE TITLE
Ufonet/Python

### ISSUE THREAD

**Issue by clowndll** [epsylon/ufonet#78]
Recently I installed a older version of python an then a got an error executing ufonet so I got back for the version that I were using and then this happened : (I'm using Linux)
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/root/Documents/ufonet/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
ImportError: No module named requests

**Comment by Astrades** [comment]
pip install requests

**Comment by clowndll** [comment]
already did it, didnt work but ty

**Comment by epsylon** [comment]
Hi,
You can get that library by using some of this methods:
- python setup.py install
- pip install requests
- sudo apt-get install python-requests
