### ISSUE TITLE
largest file

### ISSUE THREAD

**Issue by ph1ex0n** [epsylon/ufonet#8]
ufonet can not find the largest file

**Comment by epsylon** [comment]
Ufonet is using for search largest file a defined pattern of extensions: .png, .mov, .webm, .avi, .swf, .mpg, .mpeg, .mp3, .ogg, .ogv, .wmv, .css, .js, .xml, .php, .html, .jsp, .asp, .txt...

Take a loot to code to understand it. If your target has a largest file with others it cannot be found. You can implement it easily or just report your needs to be implemented on future versions.
