### ISSUE TITLE
How to configure TOR?

### ISSUE THREAD

**Issue by Astrades** [epsylon/ufonet#80]
Hey guys .So, I have TOR running on port 9050. How do I make ufonet run through TOR?

**Comment by Astrades** [comment]
Currently, I'm trying to use the command:
`./ufonet --proxy=https://127.0.0.1:9050 --check-tor`
Sadly, I get the error that I can't connect to TOR checker.

**Comment by Tosible** [comment]
Try having the Tor Browser open, and set the port to 9150 instead of 9050

**Comment by mrayushh** [comment]
@epsylon hey my tor have this configuration 
![image](https://user-images.githubusercontent.com/44119024/46963701-f9073780-d0c3-11e8-93f7-cee4e86c146e.png)
and i am using this command
./ufonet --proxy=socks5://127.0.0.1:9150 --check-tor 
But it is giving error
proxy malformed

 bcz i have used this command with other softwares while connecting with tor and they just worked fine.

**Comment by epsylon** [comment]
Hi,
You don't need to specify which protocol version are you using (socks5) for connect your proxy. 
So, let's try with:
--proxy=http://127.0.0.0.1:9150 --check-tor
Btw, you will need also a transparent proxy to have it working such as: polipo, privoxy...
Take a look to this video that I have published recienctly about how to configure a "secure" exit method for your connections: https://03c8.net/

**Comment by ShadowWoIf** [comment]
Hi

**Comment by ShadowWoIf** [comment]
Hi,
I tried using all of ./ufonet --proxy=http://127.0.0.1:8118 --check-tor
./ufonet --proxy=http://127.0.0.1:9050 --check-tor
.Turning on the tor browser and /ufonet --proxy=http://127.0.0.1:9150 --check-tor
but the result is always same: 

Sending request to: https://check.torproject.org/
It seems that Tor is not properly set.
IP address appears to be: xx.xxx.xxx.159

I also checked sudo netstat -plnt fgrep 9050 and it shows that Tor is listening on port 9050. How do i solve this?

**Comment by epsylon** [comment]
Hi,

@ShadowWoIf This is basics on networking (and I think I have explained it many times). 

>"Tor cannot connect directly to any tool as a transparent proxy" 

You need one to complement it, as for example: privoxy, polipo, burp...
Please, review some docs about that (I have made a video-tutorial here: https://03c8.net, setting up an example) and try to difference that issues from UFONet code issues.

Greetings.

**Comment by ShadowWoIf** [comment]
Hi, I have a question. Can I launch an attack, the basic one "-a <url>" without properly configuring privoxy/complementary proxy with ufonet? Because I tried doing so but I keep getting "Failed" Messages.

![image](https://user-images.githubusercontent.com/49546386/56075458-f38b6100-5d77-11e9-87f3-26c6bd89fd76.png)

**Comment by trollmad3** [comment]
@ShadowWoIf If you want someone to reply to your question, then make a new issue.

**Comment by epsylon** [comment]
> Error in "Segmentation fault"

https://serverfault.com/a/458789

**Comment by ShadowWoIf** [comment]
> > Error in "Segmentation fault"
> 
> https://serverfault.com/a/458789
I followed the link and found out the details of seg fault from dmesg but I can not interpret any head or tails about it :( 
I tried googling it, but nothing showed up. Not a single result. I am feeling very stressed out at the moment and I'd give anything just to perform a single basic attack.
![image](https://user-images.githubusercontent.com/49546386/56090161-f8711300-5e52-11e9-9608-e52e6099043e.png)

segfault at 78 ip b6703dc3 sp adcf3080 error 6 in libtasn1.so.6.5.1[b66f8000+13000]

**Comment by ShadowWoIf** [comment]
Dear Epsylon, is there any way I can communicate with you in realtime? If that's possible I would be greatly obliged.

Thank You

**Comment by trollmad3** [comment]
@ShadowWoIf His email is `epsylon@riseup.net`

**Comment by epsylon** [comment]
@ShadowWoIf This is not related with UFONet code, and I am not here to fix computers of everyone just using that escuse... Try to manage&understand your computer and search on the internet for tutorials... this is not the 90's..

I will try to help you on a private way just because of brotherhood, but this is not my roleplay here (neither my time).

**Comment by ElBrujo** [comment]
Hola psy, voy a tratar de darle seguimiento a esta cadena para hacer un nuevo videotutorial, estoy activamente siguiendo tu trabajo, me gustaría una invitación para una cuenta para riseup para poder darle continuidad a esa conversación en privado, espero no quitarte mucho de tu valioso tiempo, estoy revisando y ejecutando los programas que han compartido y estoy muy interesado en ayudar en toda forma que pueda, cuando tenga el video listo, compartiré el enlace aquí. Gracias por tu dedicación y esfuerzo, Saludos desde México. Alex Mora.

**Comment by epsylon** [comment]
@ElBrujo genial, será un placer ver el video. Avisa cuando lo tengas!. Del resto, hablamos en privado. Un saludo.
