### ISSUE TITLE
is slow or just me ?

### ISSUE THREAD

**Issue by bozoweed** [epsylon/ufonet#82]
hello i have try ufonet on kali 2.02 and i found it low ( i get 12 core with 16 go ram and ssd ) but ufonet don't use all the power of my pc and i don't know why ... when i try to attack me the bot net make 5 minute for start ddos and make request so slowly. my ping is 23 with 8.8.8.8 and when try to ddos me i go to 24 ... ufonet net send 10kbs ... i seen on dstat and htop and monitor ( default gui monitor systeme of kali )

**Comment by epsylon** [comment]
I think this is more related with python as interpreter than from Ufonet as code, almost that part related with your machine rates. 

By the way, try to extend your report with more data...

**Comment by bozoweed** [comment]
what more you need ?

**Comment by epsylon** [comment]
@bozoweed if you want to check your traffic related with UFONet, you can try to record some _wireshark_ logs and send to me via email for analize them.
