### ISSUE TITLE
[Error] Something went wrong with searching: bing

### ISSUE THREAD

**Issue by trollmad3** [epsylon/ufonet#83]
This litterally happens everytime i search for zombies. I tried "everything" to fix it but it still says the error. 

![virtualbox_2017-11-24_17-00-45](https://user-images.githubusercontent.com/7843719/33225228-07d59846-d139-11e7-9925-5850465c660a.png)

Also if you know. How would i attack IP's not hostnames? Example: 127.0.0.1 not www.google.com

**Comment by cyph4r** [comment]
I'm having this same issue, no matter the SE, @epsylon

**Comment by epsylon** [comment]
@trollmad3 @cyph4r 

> Also if you know. How would i attack IP's not hostnames? Example: 127.0.0.1 not www.google.com

Same way as domains, but using IP's after protocol, like: **http://127.0.0.1 or https://127.0.0.1**

About HEAD Check error, that depends on different reasons. Are you using Tor?. Is that happening always at same point?

Btw, I will try to review/patch it soon...

**Comment by trollmad3** [comment]
@epsylon 

> Are you using Tor?

No. I am not using Tor When i look for zombies this error pops up when i have a big dork list. It would be  really awesome if you patched this. Thanks.

**Comment by cyph4r** [comment]
Yeah, I emailed him, but it got detected by my custom spam filter and deleted from my inbox, it’s probably because he doesn’t use a real name so after I read it, it got detected and wiped, but still @epsylon and help with this error would be appreciated, I as well don’t have tor running

**Comment by epsylon** [comment]
I think this error comes becaure there are some changes at some search engines (bing, etc..) used by UFOnet (a classic for this tool and this features). I will review regular expressions related to patch it. 

Just stay tunned...
