### ISSUE TITLE
Error importing: pygeoip lib

### ISSUE THREAD

**Issue by purplekush187** [epsylon/ufonet#84]
Hey ive just installed ufonet and did
Pip install pycurl
Pip install geoip 
And that stuff...
So im running ./ufonet --gui and then go on botnet
So now im clicking generate map and than the error shows up:
Error importing: pygeoip lib
Thanks for your help :)
Ps:
My friend told me that i need to connect to ufonet or something but i just do ./ufonet -a Url -r 1000 
Edit:
Never mind my freind said me that he connected his bots from a server to ufonet (he edited the ufonet file) so now i know why websites dont lag 1%

**Comment by epsylon** [comment]
Hi,

You have a script near UFONet executable on main folder named _setup.py_ that will try to help you to install all required libs. 

Launch it with: **python setup.py install**

Also you can try to install that libs by using OS repositories. For example, to have geoip required lib you should try to run: 

**sudo apt-get install python-geoip**

+info -> FAQ: https://ufonet.03c8.net/FAQ.html

To see if geoip is working, please try it with a clean installation (with a few zombies on your army).
