### ISSUE TITLE
Traffic not logged

### ISSUE THREAD

**Issue by Drk97** [epsylon/ufonet#85]
Hello,
when I use ufonet to attack my server the logs won't show more than 10-20 entries, and this same result can be seen while running a sniffer like wireshark. There are very very few HTTP requests recorded compared to the number of HITs registered by ufonet. Why is that?

**Comment by epsylon** [comment]
Hi @Drk97 ,
UFOnet cannot controls if requests are received by target, almost, without checking some other related data, such as loading time, response time, etc...  
When you have a HIT (using DoS/DDoS modes) means that almost your part of the request is correctly formed and sent. 
Mostly of non-hits are related with your list of zombies. Probably if you try with a clean installation something like this spelling and record it by using wireshark:
./ufonet -a "target.com" --loic 50
You will see how the different zombies and your 50 loic requests are received by target correctly. 
By the moment, we haven't any other way than this one to have a reference of that the process is correctly ongoing. UFONet is checking 200 HTTP codes (and some others) and takes that as a "HIT"..

**Comment by epsylon** [comment]
I will code something that way for next release...
