### ISSUE TITLE
Ufonet on macOS High Sierra

### ISSUE THREAD

**Issue by cyph4r** [epsylon/ufonet#87]
I am attempting to run Ufonet in a computer running macOS High Sierra. Whenever I try to run it, I get an error (as shown the screen capture below). I have all the required libraries, I believe it’s an issue with PyCurl, and I tried reinstalling said library, and I have scoured the internet looking for a solution,  a few people have had the same issue, except they were able to fix it. Is Ufonet even compatible with macOS?

@epsylon 
Any help would be greatly appreciated,

cy4

![719b9a70-6f36-4235-8063-6ef1d52bb485](https://user-images.githubusercontent.com/35050991/34642750-6a845f30-f2e6-11e7-8e50-a76e084df726.jpeg)

**Comment by epsylon** [comment]
@chip4r try this: https://stackoverflow.com/questions/21096436/ssl-backend-error-when-using-openssl
