### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by Dylan433447** [epsylon/ufonet#89]
pip install geoip
Requirement already satisfied: geoip in /usr/lib/python2.7/dist-packages
...
pip install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages
..
pip install requests
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
...........

in other terminal 
./ufonet --gui
                                             0========================================0
                '' '----' ''                 ||                                      ||
             .'_.- (    ) -._'.              ||  * Class: UFONet -ViPR404-           ||
           .'.'    |'..'|    '.'.            ||                                      ||
    .-.  .' /'--.__|____|__.--'\ '.  .-.     ||  * Type: Scout/Transporter           ||
   (O).)-| |  \    |    |    /  | |-(.(O)    ||                                      ||
    `-'  '-'-._'-./      \.-'_.-'-'  `-'     ||  * Botnet (featured):                ||
       _ | |   '-.________.-'   | | _        ||                                      ||
    .' _ | |     |   __   |     | | _ '.     ||    -Zombies: HTTP GET bots           ||
   / .' ''.|     | /    \ |     |.'' '. \    ||    -Droids : HTTP GET (+params) bots ||
   | |( )| '.    ||      ||    .' |( )| |    ||    -Aliens : HTTP POST bots          ||
   \ '._.'   '.  | \    / |  .'   '._.' /    ||    -UCAVs  : Web Abusing bots        ||
    '.__ ______'.|__'--'__|.'______ __.'     ||    -X-RPCs : XML-RPC bots            ||
   .'_.-|                          |-._'.    ||                                      ||
                                             0|======================================|0

Error importing: pygeoip lib. 

 On Debian based systems:

 $ 'sudo apt-get install python-geoip' or 'pip install geoip')

Error importing: pygeoip lib. 

 On Debian based systems:

 $ 'sudo apt-get install python-geoip' or 'pip install geoip')

Error importing: pygeoip lib. 

 On Debian based systems:

 $ 'sudo apt-get install python-geoip' or 'pip install geoip')

Error importing: pygeoip lib. 

 On Debian based systems:

 $ 'sudo apt-get install python-geoip' or 'pip install geoip')

**Comment by trollmad3** [comment]
Do `pip install pygeoip` instead of `pygeoip lib`

**Comment by epsylon** [comment]
@Dylan433447 firstly, it is recommended to use a script provided with main UFONet package that automatically download/install all required dependencies... you can invoke it from package root folder using:

python setup.py install

If is not working, you can try to install geoip libs by using pip, but also on a OS layer, for example:

sudo apt-get install python-geoip

Also remember that after install it, if you have UFONet open, you should re-start it to apply changes. I am sure that after that you will have your copy working.

Thanks @trollmad3 for your assistance.
