### ISSUE TITLE
I can't connect to google.

### ISSUE THREAD

**Issue by Lucario2** [epsylon/ufonet#9]
When I reboot my computer, UFONet will sometimes connect to Google. Now I rebooted my computer 12 more times, and it flat out, just won't connect to Google. I think I should re-Install my kali linux.

**Comment by epsylon** [comment]
This is not a problem of UFONet... As I explained a lot of times, Google will blocks Tor connections after some of them asking you to fill a captcha (that UFOnet cannot resolve by itselfs). 
You have 2 options if this happens, you can fill captcha visiting for example: google.com or you can create a different relay for your tor onion (ex: /etc/init.d/tor restart) expecting a non blocked exit.

**Comment by Lucario2** [comment]
I am not using tor

**Comment by epsylon** [comment]
Reboot a computer to use a tool doesn't sound a good practice... I close your ticket.

**Comment by Lucario2** [comment]
How did you just help me solve my problem?

**Comment by Lucario2** [comment]
You are the developer of this. Are you not experiencing this problem?

**Comment by Lucario2** [comment]
Look- I need help really bad...

**Comment by epsylon** [comment]
If you need attention, go to other forums.., ok?
I am here to solve code problem with UFONet (and a bunch of other projects) and I am telling you that because of your description I can see that this you said is not a problem of the tool. 
I am not here to teach you how to manage your computer.
Don't waste my time...

**Comment by Lucario2** [comment]
You know what. This is a bug in your code. Fuck you.
