### ISSUE TITLE
Why error ?

### ISSUE THREAD

**Issue by Dylan433447** [epsylon/ufonet#90]
[Info] Firing from: http://www.websiteoptimization.com/services/analyze/wso.php?url=mt2beast.com/
[Error] Droid: http://www.websiteoptimization.com/services/analyze/wso.php?url=mt2beast.com/ -> FAILED (cannot connect!)
[Info] Firing from: http://www.statscrop.com/www/mt2beast.com/
[Info] Firing from: http://www.siteworthtraffic.com/report/mt2beast.com/
[Info] Firing from: http://www.opensiteexplorer.org/links?site=mt2beast.com/
[Info] Firing from: http://www.wholinks2me.com/details.php?url=mt2beast.com/
[Info] Firing from: https://whois.domaintools.com/mt2beast.com/
[Info] Firing from: http://validator.w3.org/mobile/check?docAddr=mt2beast.com/&async=false
[Error] Droid: http://validator.w3.org/mobile/check?docAddr=mt2beast.com/&async=false -> FAILED (cannot connect!)
[Info] Firing from: http://valet.webthing.com/access/htnorm?url=http%3A%2F%2Fmt2beast.com/&suite=WCAG3&xslt=listed
[Info] Firing from: https://research.domaintools.com/research/screenshot-history/mt2beast.com/

WHY FAILED TO CONNECT !!

**Comment by trollmad3** [comment]
![opera_2018-01-19_17-42-59](https://user-images.githubusercontent.com/7843719/35176658-31d7f822-fd40-11e7-885a-d42b1667c50e.png)

The site got suspended (for now). Before you make a issue about this please figure it out before you type all caps.

**Comment by epsylon** [comment]
@Dylan433447 That means that some of your zombies aren't replying correctly to your orders or that they aren't online. I recommend you to pass a test to update your 'army', by using:

`./ufonet -t 'botnet/zombies.txt'`
