### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#91]
Is there any chance there will be any updates to fix the many many bugs and issues with the software? I love ufonet but it has become practically unusable over the past few months. I cant get more dorks or anything because of the timeout errors and inconsistent chance of scan completion at less that 2.5%. Please give us some updates!!!

**Comment by trollmad3** [comment]
He is currently working on a update. These updates take time y'know.

**Comment by Clon3d** [comment]
If you need really good updated list of 2018 google dorks, let me know, anything I can do to help the project.

**Comment by trollmad3** [comment]
@Clon3d Why would he need google dorks? Hes fixing the bug fixes not asking for dorks.

**Comment by Clon3d** [comment]
@trollmad3 was just an offer, never hurts to have better and more up to date dorks seeing as that's a pretty big part of this programs performance outcome

**Comment by epsylon** [comment]
@trollmad3 not only fixing bugs... I am adding another nice HTTP deception technique to "Extra attacks" ;-)

@Clon3d any positive income is welcome... you can pull it

@LulzRose be patient... btw, Board is up!!

**Comment by LulzRose** [comment]
@epsylon any chance we will end up getting an eta in the next month?

**Comment by trollmad3** [comment]
@epsylon Wont you fix the [Error] Cant connect to bing?

**Comment by epsylon** [comment]
@trollmad3 dorker is fixed and working nice. New release have a restoration system implented in which you can manage zombies in another way.. Also have a system to re-continue autosearch in case of crashing or voluntary stop. Don't worry, I am doing nice work on that way.

@LulzRose time is so relative. As life. Btw, try to send me some btc, probably this can motivate me especially-.. 🖌
