### ISSUE TITLE
Needs python to run

### ISSUE THREAD

**Issue by TheBootTester** [epsylon/ufonet#93]
I downloaded python and all the things needed to run this, but it says "requires python" but I have it...

**Comment by trollmad3** [comment]
@TheBootTester Are you doing this on windows or linux?

**Comment by TheBootTester** [comment]
Windows

**Comment by trollmad3** [comment]
@TheBootTester Dont use this program on windows. It is known to glitch and f*ck up on windows. It is way easier to use on linux.
