### ISSUE TITLE
UFONet doesn't want to update.

### ISSUE THREAD

**Issue by trollmad3** [epsylon/ufonet#95]
I noticed UFONet got a updated. I typed the command

`./ufonet --update`

and it showed this: 

> Trying to update automatically to the latest stable version
> Your UFONET doesn't need to be updated....

Is there a way to update it with `git`?

**Comment by epsylon** [comment]
I think so... Did you cloned your package from git?. 
Btw, put here your output to be checked. Now with the new release looks interesting to have it working perfectly.

**Comment by epsylon** [comment]
I have commited a fix for this issue.
