### ISSUE TITLE
search engine is asking for a captcha...

### ISSUE THREAD

**Issue by qq529879477** [epsylon/ufonet#96]
command:
./ufonet --se 'yandex' --sd 'botnet/droks.txt' -v --threads 2000 --force-yes

error：
Query used: https://yandex.ru/search/?text=inurl%3A%22proxy.php%3Furl%3D%22&lr=213&p=0

[Info] - This search engine is asking for a captcha...

[Error] - Something wrong searching using: yandex

**Comment by epsylon** [comment]
Yandex is not longer supported. 
I have reciently commited a fix for this issue. 
Please download an UFONet copy again.
