### ISSUE TITLE
Unable to run GUI 

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#97]
I am running parrot OS which has worked fine in the past with ufonet but with the new version I am unable to run the gui because sudo ./ufonet --gui gives off Dont run this as root but when I run ./ufonet --gui I get: 

`Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/rose/ufonet/core/main.py", line 154, in run
    self.start_ship_engine()
  File "/home/rose/ufonet/core/main.py", line 139, in start_ship_engine
    self.update_flying_stats() # update flying time stats
  File "/home/rose/ufonet/core/main.py", line 965, in update_flying_stats
    stats_json_file = open(self.mothership_stats_file, "w+")
IOError: [Errno 13] Permission denied: 'core/json/stats.json'
`

**Comment by epsylon** [comment]
> IOError: [Errno 13] Permission denied: 'core/json/stats.json'

You are running UFONet on a folder in which your user hasn't permissions. Fix that and try to report here only code related bugs.
