### ISSUE TITLE
Never ending autosearch

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#98]
Hello,
I was having major issues in which the autosearch function never ends. It has found hundreds of thousand of possible zombies in the past 4 days but it never gives any options to attempt to add them to the botnet. Is there any way around this? Love the project and love the most recent updates but this is really killing its usability.

**Comment by mrxardas** [comment]
Hi, if you use autoserach your zombies is writing in /ufonet/botnet/human.txt U mast coppy all links to zombies.txt or rename file. If u run it u see all searched zombies. Do you have success with ddos? I use it but site is online :( sorry for mistakes my English is bad

**Comment by epsylon** [comment]
Hi,
With new AI mode coded at last release, UFONet will not repeat zombies on searching tasks, which means that has an ending, but it can takes some time. Just leave it and soon you will have a huge army ;-)

@mrxardas yep, this is a nice trick. Btw, remember that success depends on different factors. Take a look to the FAQ to understand it a bit better: 

https://ufonet.03c8.net/FAQ.html

Thanks for your report. I close it...

**Comment by bootkiller420** [comment]
no it does seem like it but i dont think it is.. im still learning the program myself been too long for me..  but maybe u can add a debug packet so we can see how many are pending and how many are complete , etc.. just something to add..

**Comment by bootkiller420** [comment]
but why do i keep getting this '
Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/root/Desktop/ufonet/core/main.py", line 905, in run
    self.create_web_interface()
  File "/root/Desktop/ufonet/core/main.py", line 1690, in create_web_interface
    tcpsock.bind((host,port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@kali:~/Desktop/ufonet#

**Comment by trollmad3** [comment]
The `socket.error: [Errno 98] Address already in use` error is because you _likely_ have something bound to that port already.
